### PR TITLE
remove @exception from documentation.

### LINKED ISSUE #3684: [Doxygen docs] Fix API documentation to match libbpf doxygen docs
### Describe the bug

- The API documentation in ebpf-for-windows/include/bpf/bpf.h comments are different from the libbpf doc https://github.com/libbpf/libbpf/blob/master/src/bpf.h#L191.
Also, there are incorrect exception keywords.

This issue is created to investigate and match libbpf doxygen documentation.

Details in https://github.com/microsoft/ebpf-for-windows/pull/3652

### OS information

Windows 10 and above.

### Steps taken to reproduce bug

Check 
https://microsoft.github.io/ebpf-for-windows/bpf_2bpf_8h.html,
https://microsoft.github.io/ebpf-for-windows/libbpf_8h.html

### Expected behavior

No exception keyword should be present.

### Actual outcome

Exception keyword is present in each API.
Docs do not match to libbpf.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by shankarseal**
## Description

_Describe the purpose of and changes within this Pull Request._
Closes #3684. Removes `@exception` keyword from documentation. Fixes documentation of return values to be negative. Changed wording about return status value to be consistent with Linux libbpf documentation.

Fixed spelling mistakes in a few files.

## Testing

_Do any existing tests cover this change? Are new tests needed?_
N/A.

## Documentation

_Is there any documentation impact for this change?_
Documentation only change.

## Installation

_Is there any installer impact for this change?_
N/A.

### CODE REVIEW

**Comment by shankarseal** [comment]
Note that the issue #3684 suggested changing all documentation to be same with Linux libbpf. There are several functions (such as `bpf_prog_attach`) do not have any documentation in Linux libbpf. For some other functions, the behavior change in the 2 platforms warrant slight change in wording. For instance the `pin` functions in Linux talk about the BPF FS which is not applicable to Windows. Also, it is expensive to go function by function and compare the documentation. So the documentation of most functions were not changed.

File: include/bpf/bpf.h [hunk 1]
```diff
@@ -13,10 +13,10 @@
  *
  * @param[in] link_fd File descriptor of link to detach.
  *
- * @retval 0 The operation was successful.
- * @retval <0 An error occured, and errno was set.
+ * @return 0, on success; negative error code, otherwise (errno is also set to
+ * the error code)
```
Comment (dthaler) [inline include/bpf/bpf.h:17]: Should not use both `@return` and `@retval`.  Switch back to just using retval.

**Review by dthaler — CHANGES_REQUESTED** [review]

File: include/bpf/bpf.h (hunk 1 above)
Comment (shankarseal) [reply include/bpf/bpf.h]: Fixed.

**Review by dthaler — APPROVED** [review]

**Review by saxena-anurag — APPROVED** [review]
