### PR TITLE
Fix memory leak

### LINKED ISSUE #5054: Workflow failed - fault_injection_full
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/22478457981)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/6926e944907ddbebe384d8f7374f2ef552fbb088)
Test name - `fault_injection_full`
Event - schedule

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #5054

## Description

**Issue**
Following is the sequence of steps when an update elem is called for a custom map that stores modified values in the map.
1. ebpfcore calls `provider->process_map_add_element` to get actual value to store in the map.
2. ebpfcore calls `_update_hash_map_entry_operation_context` to store the actual value in the map.
3. If memory allocation inside `_update_hash_map_entry_operation_context` fails, ebpfcore should ideally call `provider->process_map_delete_element` to let provider clean up any context / memory.

The issue is that ebpfcore fails to call `provider->process_map_delete_element`.
There is another issue in the code that invocation of `process_map_add_element` and `process_map_delete_element` is somewhat asymmetric and hard to debug.

**Fix:**
Update hash table `notification_callback` logic to also take `notification_flags` as input. This tells hash table what all notification types are enabled for a particular hash table.

Custom maps now only enable DELETE notification, and all other notifications are handled outside the hash table implementation. This fixes the original issue, and also makes invoking provider dispatch functions symmetric.

## Testing

Existing tests cover this.

## Documentation

No.

## Installation

No.

### CODE REVIEW

File: libs/execution_context/ebpf_maps.c [hunk 1]
```diff
@@ -4477,6 +4499,19 @@ _ebpf_custom_map_update_hash_map_entry(
     ebpf_custom_map_operation_context_t operation_context = {flags, true};
```
Comment (Alan-Jowett) [inline libs/execution_context/ebpf_maps.c:4499]: Bug: This rollback fires whenever `_update_hash_map_entry_operation_context` fails and `process_map_delete_element != NULL`. But if `process_map_add_element` was NULL (line 4451), the provider was never notified of an add, so calling delete here would be incorrect — it would undo an add that never happened.

Guard should also check that the add path was taken:
```c
if (result != EBPF_SUCCESS &&
    custom_map->provider_dispatch->process_map_add_element != NULL &&
    custom_map->provider_dispatch->process_map_delete_element != NULL) {
```
Or use a `bool add_succeeded` flag set inside the add block.

File: libs/runtime/ebpf_hash_table.c [hunk 2]
```diff
@@ -812,6 +816,7 @@ ebpf_hash_table_create(_Out_ ebpf_hash_table_t** hash_table, _In_ const ebpf_has
     table->supplemental_value_size = options->supplemental_value_size;
     table->notification_context = options->notification_context;
     table->notification_callback = options->notification_callback;
```
Comment (Alan-Jowett) [inline libs/runtime/ebpf_hash_table.c:821]: Suggestion: Consider adding a debug assert in `ebpf_hash_table_create` to catch future misuse where someone sets a `notification_callback` but forgets to set `notification_flags`:
```c
ebpf_assert(!options->notification_callback || options->notification_flags);
```
Without this, a non-null callback with zero flags would silently do nothing — a subtle trap for future callers.

File: libs/execution_context/ebpf_maps.c (hunk 1 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_maps.c:4499]: When provider intends to modify the map values, at map creation time it is validated that none of the dispatch functions (find_element, add_element, delete_element) are NULL. They (or some of them) are allowed NULL only if the provider does not modify the values.

One thing we could simplify is that ebpfcore always requires all these dispatch functions to be non-NULL.

Thoughts?

Comment (Alan-Jowett) [reply libs/execution_context/ebpf_maps.c:4499]: Good point — I see the validation at line 4647 enforces all three non-NULL when `UPDATE_ORIGINAL_VALUE_FLAG_PRESENT`. Since the `process_map_add_element` block (line 4451) only runs when it's non-NULL, and the only path that reaches the rollback after a successful add is through that block, you're right that in the current code this is safe for the UPDATE_ORIGINAL_VALUE path.

That said, the validation at 4647 is scoped to `UPDATE_ORIGINAL_VALUE_FLAG_PRESENT` — without that flag, a provider could theoretically have `add == NULL && delete != NULL`, and the rollback would call delete without a prior add. It's unlikely today, but the check is free.

Re: requiring all dispatch functions to always be non-NULL — I think that's a clean simplification if it doesn't break any existing providers. It removes a whole class of partial-dispatch edge cases. Worth doing as a follow-up if you want to keep this PR focused.

**Review by mikeagun — APPROVED** [review]
