### PR TITLE
Fix bpf_map_get_next_key "key not found" bug.

### LINKED ISSUE #2942: bpf_map_get_next_key should return the first key if key not found
As per information from the Isovalent folks, the bpf_map_get_next_key should start the iteration of the BPF map at the beginning of the map if the key is not found.

### PR DESCRIPTION
**Pull request by gtrevi**
Fixes #2942

## Description

This PR fixes the behavior of `bpf_map_get_next_key` in the following use case:

Ref: https://man7.org/linux/man-pages/man2/bpf.2.html
*(...) If key is not found, the operation returns zero and sets the next_key pointer to the key of the first element. (...)*

## Testing

Added specific test in CI/CD.

## Documentation

n.a.

## Installation

n.a.

### CODE REVIEW

File: tests/unit/libbpf_test.cpp [hunk 1]
```diff
@@ -2765,6 +2765,32 @@ TEST_CASE("BPF_MAP_GET_NEXT_KEY etc.", "[libbpf]")
...
+    // Add 3 entries into the now empty map.
+    for (key = 100; key < 400; key += 100) {
+        value = 0;
+        memset(&attr, 0, sizeof(attr));
+        attr.map_fd = map_fd;
+        attr.key = (uintptr_t)&key;
+        attr.value = (uintptr_t)&value;
+        REQUIRE(bpf(BPF_MAP_UPDATE_ELEM, &attr, sizeof(attr)) == 0);
+    }
+    // Lookup the first key in the map, so to check it's returned later.
```
Comment (dthaler) [inline tests/unit/libbpf_test.cpp:2778]:
```suggestion

    // Look up the first key in the map, so we can check that it's returned later.
```

File: tests/unit/libbpf_test.cpp [hunk 2]
```diff
@@ -2765,6 +2765,32 @@ TEST_CASE("BPF_MAP_GET_NEXT_KEY etc.", "[libbpf]")
...
+    memset(&attr, 0, sizeof(attr));
+    attr.map_fd = map_fd;
+    attr.key = NULL;
+    attr.next_key = (uintptr_t)&next_key;
+    REQUIRE(bpf(BPF_MAP_GET_NEXT_KEY, &attr, sizeof(attr)) == 0);
+    uint64_t first_key = next_key;
+    // Lookup a key that is not present in the map, and check that the first key is returned.
```
Comment (dthaler) [inline tests/unit/libbpf_test.cpp:2785]:
```suggestion

    // Look up a key that is not present in the map, and check that the first key is returned.
```

**Review by dthaler — APPROVED** [review]
Ok modulo comment nits

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
