### PR TITLE
Return module handle on native module load

### LINKED ISSUE #1303: EBPF_OPERATION_LOAD_NATIVE_MODULE should return a handle to the native module
### Describe the feature you'd like supported

Native module load is a 2-step process from user mode:
1. Call `EBPF_OPERATION_LOAD_NATIVE_MODULE` IOCTL
2. Call `EBPF_OPERATION_LOAD_NATIVE_PROGRAMS` IOCTL

If the user mode application only calls first IOCTL above, and never calls the second IOCTL (or crashes before calling the second IOCTL), the native module will remain loaded till either:
1. ebpfcore is stopped.
2. the native module driver service is stopped manually.

### Proposed solution

To solve the above problem, call to `EBPF_OPERATION_LOAD_NATIVE_MODULE` should return a handle to the native module.
This will ensure that if the user mode application exits without calling IOCTL `EBPF_OPERATION_LOAD_NATIVE_PROGRAMS`, the native module will get unloaded.

### Additional context

_No response_

### LINKED ISSUE #1664: Workflow failed - unit_tests
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/3491988798)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/145933af13e40e4614917203a4823022c9e7908d)
Test name - `unit_tests`

### PR DESCRIPTION
**Pull request by saxena-anurag**
## Description

This PR adds returning a module handle for the native module that are loaded.

Changes:
1. Add ebpf_base_object which is used for creating handles.
2. Refactor code so that both ebpf_core_object ebpf_native_module derive from ebpf_base_object.
3. Return module handle when EBPF_OPERATION_LOAD_NATIVE_MODULE is called.

## Testing

Both existing tests and new tests cover this.

## Documentation

NA

Fixes #1303
Fixes #1664

### CODE REVIEW

File: libs/api/ebpf_api.cpp [hunk 1]
```diff
@@ -1397,6 +1397,14 @@ _clean_up_ebpf_object(_In_opt_ ebpf_object_t* object) noexcept
         clean_up_ebpf_programs(object->programs);
         clean_up_ebpf_maps(object->maps);
 
+        if (object->native_module_handle != ebpf_handle_invalid) {
+            // TODO: Investigate this.
```
Comment (dthaler) [inline libs/api/ebpf_api.cpp:1401]: is there an issue number?

File: libs/execution_context/ebpf_native.h [hunk 2]
```diff
@@ -36,6 +36,7 @@ extern "C"
      * @param[in] service_name Name of the service for the native module.
      * @param[in] service_name_length Length of service_name.
      * @param[in] module_id Identifier of the native eBPF module to load.
+     * @param[in] module_handle Handle to the loaded native module.
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.h:39]: Line 55 says it's out not in
```suggestion
     * @param[out] module_handle Handle to the loaded native module.
```

File: libs/platform/ebpf_object.c [hunk 3]
```diff
@@ -326,3 +329,35 @@ ebpf_object_dereference_by_id(ebpf_id_t id, ebpf_object_type_t object_type)
     ebpf_lock_unlock(&_ebpf_object_tracking_list_lock, state);
     return return_value;
 }
+
+ebpf_result_t
+ebpf_object_reference_by_handle(
+    ebpf_handle_t handle, ebpf_object_type_t object_type, _Outptr_ ebpf_core_object_t** object)
```
Comment (dthaler) [inline libs/platform/ebpf_object.c:335]: To me it seems confusing to have two APIs with almost identical names:
ebpf_object_reference_by_handle and ebpf_reference_object_by_handle.   That is, it seems too easy
to confuse one for the other.   It seems the difference is whether it passes in a type or not.  Suggest putting that in the function name, like `ebpf_object_reference_by_handle_and_type`

File: libs/platform/ebpf_object.c [hunk 4]
```diff
@@ -326,3 +329,35 @@ ebpf_object_dereference_by_id(ebpf_id_t id, ebpf_object_type_t object_type)
...
+        __analysis_assume(local_object != NULL);
+        if (local_object->base.marker != _ebpf_object_marker) {
+            result = EBPF_INVALID_OBJECT;
+            goto Exit;
+        }
+
+        if ((object_type != EBPF_OBJECT_UNKNOWN) && (ebpf_object_get_type(local_object) != object_type)) {
+            result = EBPF_INVALID_OBJECT;
+            goto Exit;
+        }
```
Comment (dthaler) [inline libs/platform/ebpf_object.c:352]: By moving this check outside ebpf_reference_object_by_handle, it entails an extra interlocked increment and decrement.
What are we buying by doing it outside instead of inside?

File: libs/api/ebpf_api.cpp (hunk 1 above)
Comment (saxena-anurag) [reply libs/api/ebpf_api.cpp:1401]: I will remove this comment once PR #1548 is merged.

File: libs/platform/ebpf_object.c (hunk 4 above)
Comment (saxena-anurag) [reply libs/platform/ebpf_object.c:352]: `ebpf_reference_object_by_handle()` is now generic as it is used for both `ebpf_core_object_t` and `ebpf_native_module_t` objects
An "object_type" is only applicable to objects derived from `ebpf_core_object_t` (`ebpf_core_map`, `ebpf_core_program`, etc.)

Hence I had to move this check out of `ebpf_reference_object_by_handle`.

File: libs/execution_context/ebpf_native.h (hunk 2 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.h]: Fixed.

File: libs/execution_context/ebpf_native.c [hunk 5]
```diff
@@ -592,7 +597,7 @@ _ebpf_native_validate_map(_In_ const ebpf_native_map_t* map, ebpf_handle_t origi
     ebpf_core_object_t* object;
     ebpf_handle_t inner_map_handle = ebpf_handle_invalid;
     uint16_t info_size = (uint16_t)sizeof(info);
-    ebpf_result_t result = ebpf_reference_object_by_handle(original_map_handle, EBPF_OBJECT_UNKNOWN, &object);
+    ebpf_result_t result = ebpf_object_reference_by_handle_and_type(original_map_handle, EBPF_OBJECT_UNKNOWN, &object);
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.c:600]: Shouldn't `EBPF_OBJECT_UNKNOWN` be `EBPF_OBJECT_MAP`?

File: libs/platform/ebpf_object.c (hunk 4 above)
Comment (dthaler) [reply libs/platform/ebpf_object.c:352]: Can this happen in a hot path?  (If so, I'd prefer leaving a variation that doesn't require extra interlocked operations)

File: libs/platform/ebpf_object.c (hunk 3 above)
Comment (saxena-anurag) [reply libs/platform/ebpf_object.c:354]: Renamed one of them to `ebpf_reference_base_object_by_handle`.

File: libs/platform/ebpf_object.c (hunk 4 above)
Comment (saxena-anurag) [reply libs/platform/ebpf_object.c:372]: Changed the code to first validate the type and then acquire reference on the object.

File: libs/api/ebpf_api.cpp (hunk 1 above)
Comment (saxena-anurag) [reply libs/api/ebpf_api.cpp]: Removed this.

File: libs/execution_context/ebpf_native.c (hunk 5 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c]: Changed to EBPF_OBJECT_MAP

File: libs/api/ebpf_api.cpp [hunk 6]
```diff
@@ -1397,6 +1397,13 @@ _clean_up_ebpf_object(_In_opt_ ebpf_object_t* object) noexcept
         clean_up_ebpf_programs(object->programs);
         clean_up_ebpf_maps(object->maps);
 
+        if (object->native_module_handle != ebpf_handle_invalid) {
+            ebpf_assert(
+                object->execution_type == EBPF_EXECUTION_NATIVE || object->execution_type == EBPF_EXECUTION_ANY);
```
Comment (dthaler) [inline libs/api/ebpf_api.cpp:1402]: when would you store a native module handle but store execution_type of ANY?  Seems like we should always store the real one (NATIVE)

File: libs/execution_context/ebpf_core.c [hunk 7]
```diff
@@ -230,7 +230,7 @@ ebpf_core_load_code(
     EBPF_LOG_ENTRY();
     ebpf_result_t retval;
     ebpf_program_t* program = NULL;
-    retval = ebpf_reference_object_by_handle(program_handle, EBPF_OBJECT_PROGRAM, (ebpf_core_object_t**)&program);
+    retval = ebpf_object_reference_by_handle(program_handle, EBPF_OBJECT_PROGRAM, (ebpf_core_object_t**)&program);
```
Comment (dthaler) [inline libs/execution_context/ebpf_core.c:233]: Can we keep the original name, to minimize diffs?  Or is there a real reason to rename?

File: libs/execution_context/ebpf_native.c [hunk 8]
```diff
@@ -11,6 +11,8 @@
 #define DEFAULT_PIN_ROOT_PATH "/ebpf/global"
 #define EBPF_MAX_PIN_PATH_LENGTH 256
 
+static const uint32_t _ebpf_native_marker = 'enat';
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.c:14]:
```suggestion
static const uint32_t _ebpf_native_marker = 'entv';
```
just a suggestion to avoid confusion with NAT

File: libs/platform/ebpf_object.h [hunk 9]
```diff
@@ -20,14 +20,25 @@ extern "C"
         EBPF_OBJECT_PROGRAM,
     } ebpf_object_type_t;
 
+    typedef struct _ebpf_base_object ebpf_base_object_t;
+    typedef void (*ebpf_base_release_reference_t)(void* base_object);
+    typedef void (*ebpf_base_acquire_reference_t)(void* base_object);
```
Comment (dthaler) [inline libs/platform/ebpf_object.h:25]:
```suggestion
    typedef void (*ebpf_base_release_reference_t)(_Inout_ void* base_object);
    typedef void (*ebpf_base_acquire_reference_t)(_Inout_ void* base_object);
```

File: tests/api_test/api_test.cpp [hunk 10]
```diff
@@ -649,3 +650,48 @@ TEST_CASE("bpf_get_current_pid_tgid", "[helpers]")
...
+    fd_t map1_fd = bpf_object__find_map_fd_by_name(object, "process_map");
+    fd_t map2_fd = bpf_object__find_map_fd_by_name(object, "limits_map");
+    REQUIRE(map1_fd != ebpf_fd_invalid);
+    REQUIRE(map2_fd != ebpf_fd_invalid);
+
+    _close(program_fd);
+    _close(map1_fd);
+    _close(map2_fd);
+
+    // Try to load the same native module again, it should fail.
```
Comment (dthaler) [inline tests/api_test/api_test.cpp:679]:
```suggestion
    // Try to load the same native module again, which should fail.
```

File: tests/end_to_end/end_to_end.cpp [hunk 11]
```diff
@@ -2491,6 +2506,42 @@ TEST_CASE("load_native_program_invalid5-non-preemptible", "[end-to-end]")
 }
 #endif
 
+// Load native module and then use module handle for different purpose.
```
Comment (dthaler) [inline tests/end_to_end/end_to_end.cpp:2509]:
```suggestion
// Load native module and then use module handle for a different purpose.
```

File: tests/end_to_end/end_to_end.cpp [hunk 12]
```diff
@@ -2491,6 +2506,42 @@ TEST_CASE("load_native_program_invalid5-non-preemptible", "[end-to-end]")
...
+    // Create a valid service with valid driver.
+    _create_service_helper(L"droppacket_um.dll", NATIVE_DRIVER_SERVICE_NAME, &provider_module_id, &service_handle);
+
+    // Load native module. It should succeed.
+    service_path = service_path + NATIVE_DRIVER_SERVICE_NAME;
+    REQUIRE(
+        test_ioctl_load_native_module(
+            service_path, &provider_module_id, &module_handle, &count_of_maps, &count_of_programs) == ERROR_SUCCESS);
+
+    // Create a fd for the module handle.
```
Comment (dthaler) [inline tests/end_to_end/end_to_end.cpp:2533]:
```suggestion
    // Create an fd for the module handle.
```

File: libs/execution_context/ebpf_core.c (hunk 7 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_core.c:233]: Earlier, there was only one function `ebpf_reference_object_by_handle` which was present in ebpf_handle.c and this function was used everywhere because there was only one object type which was used to create handles (ebpf_core_object_t). With this PR, now handles can be created for ebpf_native_module_t objects also. 

Hence a new wrapper function `ebpf_object_reference_by_handle` is added in ebpf_object.c which should be used to ref the objects derived from ebpf_core_object_t. All the functions in ebpf_object.c have a prefix "ebpf_object_", so the new added function also follows the same pattern.

File: libs/api/ebpf_api.cpp (hunk 6 above)
Comment (saxena-anurag) [reply libs/api/ebpf_api.cpp:1402]: I agree. Just that `ebpf_object_set_execution_type()` allowed `EBPF_EXECUTION_ANY` to be set for a native module, so I included that option also in the assert.

Will create a separate PR to update API `ebpf_object_set_execution_type()` and update the assert here.

Comment (saxena-anurag) [reply libs/api/ebpf_api.cpp:1402]: On second thought, I think EBPF_EXECUTION_ANY should be allowed so that a user can set this execution type, without worrying about the actual file type being used (`.o` vs. `.sys`). By setting EBPF_EXECUTION_ANY, a user is agreeing to whatever is the default execution type based on the file type and a system wide policy, if any.

Comment (dthaler) [reply libs/api/ebpf_api.cpp:1402]: Sure, but when setting EBPF_EXECUTION_ANY on a native file, it should store EBPF_EXECUTION_NATIVE.  In other words, we should never store EBPF_EXECUTION_ANY in my view, the default should be stored.  So if you call ebpf_object_set_execution_type(EBPF_EXECUTION_ANY) then ebpf_object_get_execution_type() you should be able to see what the default is based on what is returned.

Comment (saxena-anurag) [reply libs/api/ebpf_api.cpp:1402]: Created PR#1561 to fix the behavior.

Comment (saxena-anurag) [reply libs/api/ebpf_api.cpp]: Fixed the assert here.

**Comment by shankarseal** [comment]
Why not make native module an ebpg_object_type and continue to use core_object as the base type?

**Comment by saxena-anurag** [comment]
> Why not make native module an ebpg_object_type and continue to use core_object as the base type?

`ebpf_core_object_t` and `ebpf_native_module_t` have different ref / deref logic (see `ebpf_object_release_reference` vs. `ebpf_native_release_reference`).

Also, all the ebpf_core_objects have an `id` and are tracked through a global id table (`_ebpf_id_table`), which is not applicable for native module.

**Review by dthaler — DISMISSED** [review]

**Comment by dthaler** [comment]
The PR description says "This PR adds returning a module handle for the native module that are loaded." but references no github issue.  What problem is this solving?  (update PR description)

File: libs/execution_context/ebpf_native.c [hunk 13]
```diff
@@ -38,9 +40,10 @@ typedef struct _ebpf_native_program
 
 typedef struct _ebpf_native_module
 {
+    ebpf_base_object_t base;
     GUID client_id;
     metadata_table_t* table;
-    volatile int32_t reference_count;
+    bool initializing;
```
Comment (Alan-Jowett) [inline libs/execution_context/ebpf_native.c:46]: Can a native module be in more than one state at a time? I.e. is initializing + unloading a valid state combination? 

If not, can we define a set of valid states and make the state machine more explicit?

File: libs/platform/ebpf_object.c [hunk 14]
```diff
@@ -155,30 +158,30 @@ ebpf_object_initialize(
...
 {
     uint32_t new_ref_count;
 
     if (!object)
         return;
 
-    ebpf_assert(object->marker == _ebpf_object_marker);
-    ebpf_assert(object->reference_count != 0);
+    ebpf_assert(object->base.marker == _ebpf_object_marker);
+    ebpf_assert(object->base.reference_count != 0);
```
Comment (Alan-Jowett) [inline libs/platform/ebpf_object.c:175]: Assert on the return from the interlocked decrement as this read is not atomic (no guarantees about what version it sees).

File: libs/execution_context/ebpf_native.c (hunk 13 above)
Comment (dthaler) [reply libs/execution_context/ebpf_native.c:46]: I agree a state enum would be better than a bunch of independent bools.

**Review by Alan-Jowett — DISMISSED** [review]
Looks good to me, but there are a few things we should probably eventually improve.

**Comment by saxena-anurag** [comment]
> The PR description says "This PR adds returning a module handle for the native module that are loaded." but references no github issue. What problem is this solving? (update PR description)

It does mention "Fixes #1301" at the end (after Documentation section)

File: libs/execution_context/ebpf_native.c (hunk 13 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c:46]: Filed Issue #1586 to track this.

**Comment by dthaler** [comment]
> > The PR description says "This PR adds returning a module handle for the native module that are loaded." but references no github issue. What problem is this solving? (update PR description)
> 
> It does mention "Fixes #1301" at the end (after Documentation section)

Got it, thanks!  (actually #1303)

File: libs/platform/ebpf_object.c (hunk 14 above)
Comment (saxena-anurag) [reply libs/platform/ebpf_object.c]: Fixed here, and at other places in the code.

**Review by dthaler — APPROVED** [review]

**Review by dthaler — DISMISSED** [review]

**Review by Alan-Jowett — DISMISSED** [review]

**Review by dthaler — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Comment by dthaler** [comment]
@saxena-anurag several tests hit a 60 minute timeout

**Comment by dthaler** [comment]
@saxena-anurag several tests hit a 60 minute timeout and so don't pass

**Comment by dthaler** [comment]
@saxena-anurag looks like a driver crash in the CI/CD test

**Comment by dthaler** [comment]
@saxena-anurag please rebase and check if the driver crash is fixed

**Review by dthaler — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
