### PR TITLE
Wait for preemptible work items to complete in UM mock.

### LINKED ISSUE #2411: Workflow failed - fault_injection_full
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/4840767792)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/a3cf9369d75e8181d1c5a59f6ebe9e2f720f0bf9)
Test name - `fault_injection_full`

### LINKED ISSUE #2413: Workflow failed - unit_tests
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/4846382234)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/20ce8bf4156a885980d8338d2007c2b99e96544e)
Test name - `unit_tests`

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #2411
Fixes #2413 

## Description

This PR fixes random test failures which are caused due to timing issue. In kernel, IO_WORKITEMS guarantee that the driver will not be unloaded until all the queued work items are completed. In the user mode mock though, there is no such guarantee currently. This causes the memory leak and other checks to be executed _before_ all the queued work items have completed.

This PR adds a wait where the `test_helper` dtor waits for all preemptible work items to complete before performing various checks.

## Testing

Existing CI/CD

## Documentation

NA

### CODE REVIEW

File: tests/end_to_end/test_helper.cpp [hunk 1]
```diff
@@ -51,6 +51,9 @@ static GUID _ebpf_native_provider_id = {/* 5e24d2f5-f799-42c3-a945-87feefd930a7
                                         0x42c3,
                                         {0xa9, 0x45, 0x87, 0xfe, 0xef, 0xd9, 0x30, 0xa7}};
 
+void
+ebpf_platform_wait_for_preemptible_work_items();
+
```
Comment (shankarseal) [inline tests/end_to_end/test_helper.cpp:56]: Please wrap any statement that can throw with a try catch since an exception in dtor will cause the process to exit.

Comment (saxena-anurag) [reply tests/end_to_end/test_helper.cpp:56]: Done.

**Review by dthaler — DISMISSED** [review]

**Review by shankarseal — DISMISSED** [review]

**Review by dthaler — APPROVED** [review]

**Review by shankarseal — APPROVED** [review]

File: tests/end_to_end/test_helper.cpp [hunk 2]
```diff
@@ -677,39 +677,32 @@ _test_helper_end_to_end::~_test_helper_end_to_end()
 
         // Run down duplicate handles, if any.
         _duplicate_handles.rundown();
-    } catch (Catch::TestFailureException&) {
-    }
 
-    // Verify that all maps were successfully removed.
-    uint32_t id;
-    if (!ebpf_fuzzing_enabled) {
-        REQUIRE(bpf_map_get_next_id(0, &id) < 0);
```
Comment (saxena-anurag) [inline tests/end_to_end/test_helper.cpp:686]: Deliberately removed this check:

1. Since maps handles can be closed aynchronously in a work-item, there is no guarantee all maps have been deleted by this time.
2. There are some tests which pin and unpin objects, but in fault injection, they do not unpin the objects. That causes rundown ref leak, hence we cannot wait for work item rundown to go to 0 here.
3. If any object is leaked, memory leak detection will anyways catch the leak.

**Review by Alan-Jowett — APPROVED** [review]

**Review by shankarseal — APPROVED** [review]
