### PR TITLE
Fixes for kernel mode multi-threaded test

### LINKED ISSUE #3453: Workflow failed - km_mt_stress_tests
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/8685581797)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/86c81cd58476f66bba24e86ab3f0559064fb605b)
Test name - `km_mt_stress_tests`

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

This PR fixes bugs in the existing kernel-mode multi-threaded stress test. Specifically:

1. Ensure that the NetEbpfExt extension is restarted only if specified on the command line.
2. Ensure that native programs are consistently marked as such.
3. Ensure successful generation and loading of unique native program files where required.

## Testing

Tested locally and via CI/CD runs on a private self-hosted runner.

## Documentation

No doc changes.

## Installation

No installer impact.

Fixes #3453

### CODE REVIEW

File: tests/stress/km/stress_tests_km.cpp [hunk 1]
```diff
@@ -1428,15 +1429,12 @@ TEST_CASE("native_load_attach_detach_unload_random_v4_test", "[native_mt_stress_
     //   all threads executing in parallel with the bare minimum synchronization between them.
     //
     // - Addition of a dedicated thread continuously unloading/reloading the provider extension.
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:1431]:
```suggestion
    // - Addition of a dedicated thread continuously unloading/reloading the provider extension
```
nit: remove extra period

File: tests/stress/km/stress_tests_km.cpp [hunk 2]
```diff
@@ -1485,16 +1480,14 @@ TEST_CASE("native_invoke_v4_v6_programs_restart_extension_test", "[native_mt_str
     //      number of times.  A stalled counter is a fatal bug and the test should return failure.
     //
     // 3. In parallel, start the 'extension restart' thread to continuously restart the netebpf extension.
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:1482]:
```suggestion
    // 3. In parallel, start the 'extension restart' thread to continuously restart the netebpf extension
```

**Review by dthaler — APPROVED** [review]

File: tests/stress/km/stress_tests_km.cpp [hunk 3]
```diff
@@ -681,18 +681,19 @@ _mt_prog_load_stress_test(ebpf_execution_type_t program_type, const test_control
             }
 
             if (program_type == EBPF_EXECUTION_NATIVE) {
+                context_entry.is_native_program = true;
                 if (test_control_info.use_unique_native_programs && context_entry.role == thread_role_type::CREATOR) {
 
                     // Create unique native programs for 'creator' threads only.
-                    _make_unique_file_copy(program_attribs.native_file_name, (compartment_id - 1));
-                    context_entry.is_native_program = true;
+                    context_entry.file_name =
```
Comment (Alan-Jowett) [inline tests/stress/km/stress_tests_km.cpp:688]: Some reason why you aren't using the std::filesytem classes for paths etc?

**Review by Alan-Jowett — APPROVED** [review]
