### PR TITLE
KM Multi-threaded stress tests - Code clean-up, duplicate code refactoring

### LINKED ISSUE #2463: code clean-up - kernel mode multi-threaded stress tests
### Describe the bug

The kernel mode multi-threaded stress test code needs clean-up.  Specifically:
- The test startup prints incorrect value for the '-er' (extension restart) commandline option for tests where it is enforced internally.

### OS information

_No response_

### Steps taken to reproduce bug

Run the test with this commandline (note that the `-er` switch is _NOT_  specified as it is internally enforced):
`.\ebpf_stress_tests_km -tt=32 -td=30 native_load_attach_detach_unload_random_v4_test`

### Expected behavior

The test startup output should show the 'extension restart' option as 'true' as it is internally enforced.

### Actual outcome

The test startup output shows the 'extension restart' option as 'false'.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

Code clean-up and common code refactoring of the tests in the 'Kernel mode Multi-threaded stress tests' suite. 

## Testing

clean-up of existing test collateral.

## Documentation

No doc changes.

Fixes #2463

### CODE REVIEW

File: tests/stress/km/stress_tests_km.cpp [hunk 1]
```diff
@@ -210,6 +197,44 @@ _restart_extension(const std::string& extension_name, uint32_t timeout)
     return status;
 }
 
+static std::thread
+_start_extension_restart_thread(const std::string& extension_name, uint32_t restart_delay, uint32_t thread_lifetime)
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:201]: recommend changing variable names to make the units clear.  Is `restart_delay` in seconds?  ms?
What about thread_lifetime?  I suspect it should be restart_delay_ms and thread_lifetime_minutes

File: tests/stress/km/stress_tests_km.cpp [hunk 2]
```diff
@@ -210,6 +197,44 @@ _restart_extension(const std::string& extension_name, uint32_t timeout)
...
+{
+    return std::thread(
+        [&](uint32_t local_restart_delay, uint32_t local_thread_lifetime) {
+            // Delay the start of this thread for a bit to allow the ebpf programs to attach successfully. There's a
+            // window where if the extension is unloading/unloaded, an incoming attach might fail.
+            std::this_thread::sleep_for(std::chrono::seconds(3));
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:207]: This implies the test is non-deterministic and if the CPU is pegged then the test can fail, is that correct?  If so, there's probably a better solution in the future than introducing an arbitrary delay.

File: tests/stress/km/stress_tests_km.cpp [hunk 3]
```diff
@@ -639,43 +664,13 @@ _mt_prog_load_stress_test(ebpf_execution_type_t program_type, const test_control
...
-                        program_attribs.extension_name,
-                        test_control_info.extension_restart_delay);
-                    std::this_thread::sleep_for(std::chrono::milliseconds(test_control_info.extension_restart_delay));
-                }
-                LOG_INFO("**** Extension restart thread done. Exiting. ****");
-            }));
+            auto restart_thread = _start_extension_restart_thread(
+                std::ref(program_attribs.extension_name),
+                test_control_info.extension_restart_delay,
+                test_control_info.duration);
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:672]: Same comments here about understandability... rename fields so the units are part of the field name.
(BTW that's part of Windows API design guidelines, not unique to ebpf)

File: tests/stress/km/stress_tests_km.cpp [hunk 4]
```diff
@@ -930,41 +923,15 @@ _mt_invoke_prog_stress_test(ebpf_execution_type_t program_type, const test_contr
...
-            while (sc::now() < endtime) {
-                LOG_VERBOSE("Toggling extension state for '{}' extension...", extension_name.c_str());
-
-                // Drivers can sometimes take some time to stop and (re)start and we need to poll until we can
-                // determine the final status. 10 (ten) seconds seems a reasonable timeout for this polling.
-                constexpr uint32_t RESTART_TIMEOUT_SECONDS = 10;
-                if (!_restart_extension(extension_name, RESTART_TIMEOUT_SECONDS)) {
-                    exit(-1);
-                }
+    // Another table for the 'extension restart' thread.
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:926]:
```suggestion
    // Another table for the 'extension restart' threads.
```

File: tests/stress/readme.md [hunk 5]
```diff
@@ -8,36 +8,34 @@ _This application requires the `ebpfapi.dll` to be present in the DLL load path
...
 
 *Test specific command-line options (all optional, defaults used if not specified):*
-- `-tt=NNNN`: Number of test threads to create.
-- `-td=NNNN`: Test run-time in minutes.
-- `-vo=<true|false>`: Enable verbose output (default: false).
-- `-er=<true|false>`: Restart extension.
+- `-tt=NNNN`: Number of test threads to create. (Default: hard-coded.)
+- `-td=NNNN`: Test run-time in minutes. (Default: hard-coded.)
+- `-vo=<true|false>`: Enable verbose output (Default: false).
+- `-er=<true|false>`: Restart extension. (default: false, where supported).
```
Comment (dthaler) [inline tests/stress/readme.md:14]:
```suggestion
- `-er=<true|false>`: Restart extension (default: false, where supported).
```

File: tests/stress/km/stress_tests_km.cpp (hunk 2 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:207]: No, the test _itself_ wouldn't fail. It would just carry on with the start of the 'extension restart' thread delayed even further.  Given that the minimum test runtime is 1 minute, IMO it's more than enough for the restart thread to start running eventually.   In any case, system load affecting thread scheduling would affect the test threads as well, so their delays would balance out.

FWIW, I _did_ think of synchronizing this thread with the test threads but thought it was overkill given the 'test only' nature of this code.  But I can certainly file an issue to revisit that synchronization if it is seen to cause issues during actual testing.

File: tests/stress/km/stress_tests_km.cpp (hunk 1 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed

File: tests/stress/km/stress_tests_km.cpp (hunk 3 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed

File: tests/stress/km/stress_tests_km.cpp (hunk 4 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed

File: tests/stress/ebpf_mt_stress.h [hunk 6]
```diff
@@ -53,8 +53,8 @@ struct test_control_info
     // The number of threads allocated per jit program.
     uint32_t threads_count{0};
 
-    // The run time for each jit program test thread in seconds.
-    uint32_t duration{0};
+    // The run time for each jit program test thread in minutes.
+    uint32_t duration_min{0};
```
Comment (dthaler) [inline tests/stress/ebpf_mt_stress.h:57]: Coding conventions are to avoid abbreviations. Acronyms like "ms" are ok but not "min", which could be "minimum" or "minutes".

Comment (dv-msft) [reply tests/stress/ebpf_mt_stress.h]: fixed

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
