### PR TITLE
Fix the IOCTL numbers so that ebpfapi.dll for x64 and x64-NativeOnly are cross-compatible.

### LINKED ISSUE #3126: Fix the IOCTL numbers so that ebpfapi.dll for x64 and x64-NativeOnly  are cross-compatible.
This is to triage our new requirements, in terms of:

- Artifacts being defined and built from the `cicd.yml` & `reusable-build.yml`.
- Artifacts to be published for Releases.

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #3126

## Description

This PR fixes the IOCTL numbers so that ebpfapi.dll for x64 and x64-NativeOnly are cross-compatible.

Changes:
1. Enable all the IOCTL numbers and block the JIT / interpret related IOCTLs in ebpfcore.
2. Add new tests for the new enabled IOCTL paths. Since these tests are in `unit_tests`, and `unit_tests` are today not run for `NativeOnly*` builds, added `unit_tests` execution for `NativeOnly*` builds also.
3. Some other minor fixes.

## Testing

Added new tests.

## Documentation

No

## Installation

No.

### CODE REVIEW

File: libs/execution_context/ebpf_core.c [hunk 1]
```diff
@@ -2424,12 +2418,9 @@ typedef struct _ebpf_protocol_handler
 } const ebpf_protocol_handler_t;
 
 #define PROTOCOL_NATIVE_MODE 1
-// #if !defined(CONFIG_BPF_JIT_DISABLED)
```
Comment (dthaler) [inline libs/execution_context/ebpf_core.c]: I understand all the changes before this line, which are fine.
But I don't understand why 2427-2423 are changed.
Can you either explain or revert these lines?

Comment (saxena-anurag) [reply libs/execution_context/ebpf_core.c]: So there are 2 parts for the changes in this section.

Part 1: The protocol handlers that are defined today use `PROTOCOL_*_MODE` flags to define in what modes can they be called. Since we are uncommenting JIT IOCTLs for native mode also, we need to at least define these macros (looks like `PROTOCOL_INTERPRET_MODE` does not really need to be defined, and I have disabled that back for native mode).

Part 2: We have 2 flags `CONFIG_BPF_JIT_DISABLED` and `CONFIG_BPF_INTERPRETER_DISABLED` which theoretically creates 4 possible combinations. Currently we were only handling 3 combinations (case of `!defined(CONFIG_BPF_INTERPRETER_DISABLED)` was not being handled). So this PR adds that case also.

There was another bug I think where we are using `||` instead of `&&` when we are defining `PROTOCOL_JIT_OR_INTERPRET_MODE` to be `(PROTOCOL_JIT_MODE | PROTOCOL_INTERPRET_MODE)`

File: libs/execution_context/ebpf_core.c [hunk 2]
```diff
@@ -2475,17 +2503,11 @@ ALIAS_TYPES(get_handle_by_id, get_map_handle_by_id)
 ALIAS_TYPES(get_handle_by_id, get_program_handle_by_id)
 
 static ebpf_protocol_handler_t _ebpf_protocol_handlers[] = {
-#if !defined(CONFIG_BPF_JIT_DISABLED)
     DECLARE_PROTOCOL_HANDLER_VARIABLE_REQUEST_VARIABLE_REPLY(resolve_helper, helper_id, address, PROTOCOL_JIT_MODE),
     DECLARE_PROTOCOL_HANDLER_VARIABLE_REQUEST_VARIABLE_REPLY(resolve_map, map_handle, address, PROTOCOL_JIT_MODE),
-#endif
```
Comment (dthaler) [inline libs/execution_context/ebpf_core.c:2481]: I don't think we need the actual prototypes or structs do we? 
It seems like just empty entries in the table should be sufficient to fix the IOCTL numbers.
And then the place where they're accessed should just check for a null function pointer.

File: libs/execution_context/ebpf_protocol.h [hunk 3]
```diff
@@ -87,6 +79,7 @@ typedef struct _ebpf_operation_resolve_helper_reply
     struct _ebpf_operation_header header;
     uintptr_t address[1];
 } ebpf_operation_resolve_helper_reply_t;
+#endif
```
Comment (dthaler) [inline libs/execution_context/ebpf_protocol.h:82]: Why was this moved up from line 103?

File: libs/execution_context/unit/execution_context_unit_test.cpp [hunk 4]
```diff
@@ -16,6 +16,64 @@
 #include <optional>
 #include <set>
 
+// Define the JIT and INTERPRETER related IOCTL structs here for testing, as they
+// will not be defined in ebpf_protocol.h when the JIT and INTERPRETER are disabled.
```
Comment (dthaler) [inline libs/execution_context/unit/execution_context_unit_test.cpp:20]: Why do you need them defined here when the functions don't exist?
Can't you simply use struct _ebpf_operation_header as the request and reply structs in the test?

Comment (saxena-anurag) [reply libs/execution_context/unit/execution_context_unit_test.cpp]: Removed these, and using `_ebpf_operation_header` now.

**Review by dthaler — APPROVED** [review]
Looks good now, thanks!

**Review by gtrevi — APPROVED** [review]
