### PR TITLE
Fixes for program info hash computation in online mode

### LINKED ISSUE #2763: Convert-BpfToNative.ps1 produces wrong program info hash when run on machine with ebpfcore.sys running
Seeing a strange issue, not sure the root cause yet.

Repro steps:
1) Install eBPF for Windows MSI.
2) Build https://github.com/Alan-Jowett/bpf_performance.
3) Attempt to run tests.

Expected result:
Test should pass.

Actual result:
Test fails and logs show:
```
[5]14BC.1850::2023-08-16 10:49:26.681623900 [EbpfForWindowsProvider]_ebpf_program_compute_program_information_hash
[5]14BC.1850::2023-08-16 10:49:26.681660400 [EbpfForWindowsProvider]_ebpf_program_compute_program_information_hash returned success
[5]14BC.1850::2023-08-16 10:49:26.681661700 [EbpfForWindowsProvider]Program information provider hash mismatch.,{f1832a85-85d5-45b0-98a0-7069d63013b0}
```

Taking a look at the generated binaries, the program info hash produced by the machine with ebpfcore.sys running is wrong.

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #2763

## Description

This PR fixes the below issues:

1. Bug in ebpf_serialize where it does not pass `bpf_prog_type` from ebpfcore to user mode. This causes wrong hash computation when ebpfcore is running.
2. Bug in ebpfapi where it cleans up TLS cache post verification. This breaks 2 things:
	1. When ebpfcore is running, during verification, program info from ebpfcore is saved in TLS. But when TLS is cleared post verification, `get_program_info_type_hash()` in bpf2c fails, as it attempts to get info from TLS.
	2. It breaks the assumption in bpf2c that program info hash should be computed from the info present in TLS, which is the info used by verifier.
3. In case of offline verification, `get_program_info_type_hash()` was still querying program info from the `global` copy of program info (populated from ebpf store). This PR fixes the logic where program info used in verification step is also duplicated and cached in TLS.
4.  Renamed `get_program_type_info()` to `get_program_type_info_from_tls()` and tightened the logic that this function only gets info from TLS, else it fails.

## Testing

Existing CICD. Also manually tested that with ebpfcore running, the hash is identical to the hash generated in offline verification mode.

## Documentation

No

## Installation

No

### CODE REVIEW

File: libs/api/Verifier.cpp [hunk 1]
```diff
@@ -773,9 +769,14 @@ static _Success_(return == 0) uint32_t _verify_section_from_string(
...
-    struct _thread_local_storage_cache tls_cache;
+
+    // Clear thread local storage before calling into the verifier.
+    // Note that TLS should be cleared here *before* calling into the verifier, not after.
+    // Post verification, bpf2c relies on the TLS cache to compute program info hash.
+    ebpf_clear_thread_local_storage();
+
     set_global_program_and_attach_type(program_type, nullptr);
-    set_verification_in_progress(true);
+    _verification_in_progress_helper helper;
```
Comment (saxena-anurag) [inline libs/api/Verifier.cpp:779]: This change is to ensure that `_verification_in_progress` is reset to `false` when this function returns.

File: libs/api_common/windows_platform_common.cpp [hunk 2]
```diff
@@ -246,13 +329,24 @@ get_program_type_windows(const GUID& program_type)
 
     // Failed to query from execution context. Consult static cache.
     if (use_ebpf_store) {
-        auto it2 = _windows_program_types.find(program_type);
-        if (it2 != _windows_program_types.end()) {
-            return *it2->second.get();
+        auto it2 = _windows_program_information.find(program_type);
```
Comment (saxena-anurag) [inline libs/api_common/windows_platform_common.cpp:332]: this function now stores program info from store also in TLS

**Review by dthaler — APPROVED** [review]

File: libs/api_common/windows_platform_common.cpp [hunk 3]
```diff
@@ -123,6 +123,88 @@ set_program_under_verification(ebpf_handle_t program)
...
+{
+    ebpf_result_t result = EBPF_SUCCESS;
+    ebpf_program_info_t* program_info = nullptr;
+    ebpf_helper_function_prototype_t* global_helpers = nullptr;
+    ebpf_helper_function_prototype_t* program_type_specific_helpers = nullptr;
+    ebpf_program_type_descriptor_t* program_type_descriptor = nullptr;
+    ebpf_context_descriptor_t* context_descriptor = nullptr;
+
+    program_info = (ebpf_program_info_t*)ebpf_allocate(sizeof(ebpf_program_info_t));
+    if (program_info == nullptr) {
```
Comment (Alan-Jowett) [inline libs/api_common/windows_platform_common.cpp:137]: This allocation is leaked if the next allocation fails?

Comment (saxena-anurag) [reply libs/api_common/windows_platform_common.cpp:137]: There is a call to `ebpf_program_info_free(program_info);` at 203 which should free this memory in case of any subsequent failure.

**Comment by Alan-Jowett** [comment]
Copilot summary:

This pull request includes changes to the `libs/api/Verifier.cpp`, `libs/api/ebpf_api.cpp`, `libs/api_common/api_common.hpp`, `libs/api_common/windows_helpers.cpp`, `libs/api_common/windows_platform_common.cpp`, `libs/service/api_service.cpp`, and `libs/shared/ebpf_serialize.c` files. The changes primarily focus on improving thread-local storage handling, simplifying codebase, and enhancing program information retrieval. 

Improvements to thread-local storage handling:
* Removed the `_thread_local_storage_cache` struct and replaced it with direct calls to `ebpf_clear_thread_local_storage()` in the `ebpf_api_elf_enumerate_sections()`, `ebpf_api_elf_disassemble_section()`, `_ebpf_api_elf_verify_section_from_stream()`, and `_verify_section_from_string()` functions. [[1]](diffhunk://#diff-c7cabf550a3d7ec7f53d5aaf8ea0e8a77d949e886b3c0f492ebd75228756b40fL57-L61) [[2]](diffhunk://#diff-c7cabf550a3d7ec7f53d5aaf8ea0e8a77d949e886b3c0f492ebd75228756b40fL561-R562) [[3]](diffhunk://#diff-c7cabf550a3d7ec7f53d5aaf8ea0e8a77d949e886b3c0f492ebd75228756b40fL631-R632) [[4]](diffhunk://#diff-c7cabf550a3d7ec7f53d5aaf8ea0e8a77d949e886b3c0f492ebd75228756b40fL675) [[5]](diffhunk://#diff-c7cabf550a3d7ec7f53d5aaf8ea0e8a77d949e886b3c0f492ebd75228756b40fL776-R779)

Codebase simplification:
* Replaced the `set_verification_in_progress(true);` call with the `_verification_in_progress_helper` struct in the `ebpf_verify_and_load_program()` and `_verify_section_from_string()` functions. [[1]](diffhunk://#diff-40d7b76a1d8818e9da36e35e697efcd39362a8d43f04d38c32d9bed0d5b36ccbR205-R210) [[2]](diffhunk://#diff-4b05db47f30b730880202628e554484a25835ea2ef9c897e50dbfabe67538b85L309-R315)

Enhancements to program information retrieval:
* Replaced the `get_program_type_info(&info);` call with `get_program_type_info_from_tls(&info);` in the `ebpf_get_program_info_from_verifier(_Outptr_ const ebpf_program_info_t** program`, `is_helper_usable_windows(int32_t n)`, and `get_helper_prototype_windows(int32_t n)` functions. [[1]](diffhunk://#diff-5838f7744d41bcd6c7dc0e9b88628baa36b2a2645824c76aa15f01955ac9cefeL4046-R4046) [[2]](diffhunk://#diff-4061bc714b352ee0b7df376572d799c3c14bc1799c4de97d1dab9050f4ea98fcL32-R32) [[3]](diffhunk://#diff-4061bc714b352ee0b7df376572d799c3c14bc1799c4de97d1dab9050f4ea98fcL44-R44)
* Added the `_duplicate_program_info(_In_ const ebpf_program_info_t* info, _Outptr_ ebpf_program_info_t** new_info)` function to duplicate program info.
* Modified the `get_program_type_windows(const GUID& program_type)` function to retrieve program information from the thread-local storage cache. [[1]](diffhunk://#diff-f12baeab92e497de9ca73c9ae3ca602cef38c21e55c30f5c68e6ddcd65e45117R305) [[2]](diffhunk://#diff-f12baeab92e497de9ca73c9ae3ca602cef38c21e55c30f5c68e6ddcd65e45117L249-L255)
* Replaced the `get_program_type_info(_Outptr_ const ebpf_program_info_t** info)` function with `get_program_type_info_from_tls(_Outptr_ const ebpf_program_info_t** info)` to get program information from the thread-local storage cache. [[1]](diffhunk://#diff-f12baeab92e497de9ca73c9ae3ca602cef38c21e55c30f5c68e6ddcd65e45117L753-R860) [[2]](diffhunk://#diff-c78bc8847d670319445178c4f9ae6d43db93d641621885fe53dab9e1b62c1e1fL46-R47)

Additional changes:
* Added the `uint32_t bpf_prog_type` member to the `_ebpf_serialized_program_type_descriptor` struct and updated the `ebpf_serialize_program_info()` and `ebpf_deserialize_program_info()` functions to handle this new member. [[1]](diffhunk://#diff-904e501ad3e5fa211890ac45d476bcfc28f51c17209263fbd023de5670128727R18) [[2]](diffhunk://#diff-904e501ad3e5fa211890ac45d476bcfc28f51c17209263fbd023de5670128727R431) [[3]](diffhunk://#diff-904e501ad3e5fa211890ac45d476bcfc28f51c17209263fbd023de5670128727R522)

**Review by Alan-Jowett — APPROVED** [review]
