### PR TITLE
fix CICD script to throw on test failure.

### LINKED ISSUE #740: CICD Kernel test execution script does not result in job failure even if individual catch tests are failing.
Even though `Invoke-Test` function running in test VM checks for error and throws an exception, the script does not seem to catch it.

```
    # Check for errors.
    if ($LASTEXITCODE -ne 0) {
        throw ("$TestName failed.")
    } else {
        Write-Log "$TestName passed" -ForegroundColor Green
    }
```
But `Invoke-CICDTests` catches and ignores this exception.

This is the reason why some regression in map tests were not reported.

### PR DESCRIPTION
**Pull request by shankarseal**
This fixes #740.

- Change PS script to re-throw exception raised due to test failure.
- Add temporary workaround for #739 .
- Fix ring buffer API test bug (which too was hidden due to the script issue).

### CODE REVIEW

File: libs/execution_context/ebpf_maps.c [hunk 1]
```diff
@@ -183,8 +183,10 @@ _create_array_map(
     ebpf_handle_t inner_map_handle,
     _Outptr_ ebpf_core_map_t** map)
 {
-    if (inner_map_handle != ebpf_handle_invalid)
-        return EBPF_INVALID_ARGUMENT;
+
+    // Temporarily removing check for inner map handle until
```
Comment (dthaler) [inline libs/execution_context/ebpf_maps.c:187]: Assuming we expect the old code to be put back in, we should reference it somehow. Currently the
"check for inner map handle" in the commend doesn't make sense without this context.

Comment (shankarseal) [reply libs/execution_context/ebpf_maps.c:187]: Won't the file history be sufficient to restore the code? I could put back the old code and comment it out. Would you prefer that?

**Review by saxena-anurag — APPROVED** [review]

File: libs/execution_context/ebpf_maps.c (hunk 1 above)
Comment (dthaler) [reply libs/execution_context/ebpf_maps.c:187]: In this case, yes because it's temporary and you already have the issue number in the comment.

**Review by dthaler — APPROVED** [review]
Approving though I would prefer the comment be updated before merging.
