### PR TITLE
Fix memory leak in `_duplicate_program_descriptor()`

### LINKED ISSUE #3418: Workflow failed - fault_injection_full
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/8519466444)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/f75fffc82e4e0cf76a8e88f69c3faffebe8c777e)
Test name - `fault_injection_full`

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #3418

## Description

This PR fixes memory leak in `_duplicate_program_descriptor()` that was caught by fault injection tests.

## Testing

Existing CICD

## Documentation

No

## Installation

No

### CODE REVIEW

File: libs/shared/shared_common.c [hunk 1]
```diff
@@ -252,7 +252,10 @@ _duplicate_program_descriptor(
     program_type_descriptor_copy = NULL;
 
 Exit:
-    ebpf_free(program_type_descriptor_copy);
+    if (program_type_descriptor_copy != NULL) {
+        ebpf_free((void*)program_type_descriptor_copy->name);
+        ebpf_free(program_type_descriptor_copy);
+    }
```
Comment (dthaler) [inline libs/shared/shared_common.c:258]: Lines 320-324 also have multiple free lines.  To help avoid more such bugs in the future, I'd recommend creating an ebpf_program_type_descriptor_free() function that is called from here and there.

**Review by matthewige — APPROVED** [review]

**Review by dthaler — APPROVED** [review]
