### PR TITLE
Fix OOB access in _initialize_ebpf_programs_native on program count mismatch

### LINKED ISSUE #5151: Missing bounds check in _initialize_ebpf_programs_native causes crash on program count mismatch
## Summary

`_initialize_ebpf_programs_native` in `libs/api/ebpf_api.cpp` (line ~2208) iterates using `count_of_programs` from a kernel IOCTL reply without validating it against `programs.size()` (populated from user-mode PE parsing). When these counts disagree, the function reads past the `std::vector` bounds, dereferences a NULL pointer, and crashes with `EXCEPTION_ACCESS_VIOLATION` (0xC0000005).

## Root Cause

The function receives two independently-sourced values:

1. **`count_of_programs`** — from the kernel via `_load_native_module()` IOCTL reply (`reply.count_of_programs`). The kernel gets this from the `.sys` driver's `_get_programs()` export, which returns `sizeof(_programs)/sizeof(_programs[0])`, a compile-time constant from bpf2c.

2. **`programs`** — a `std::vector<ebpf_program_t*>` populated by `_initialize_ebpf_object_from_native_file()`, which parses the PE file's `"programs"` section via `_ebpf_pe_get_section_names()` and then filters for code sections in `_ebpf_pe_add_section()`.

Both *should* agree, but they use different code paths to count programs:

- **Kernel path**: `_get_programs(&progs, &count)` returns a compile-time array size.
- **User-mode path**: `_ebpf_pe_get_section_names()` calculates `(VirtualSize - program_offset) / sizeof(program_entry_t)` then `_ebpf_pe_add_section()` filters for PE code sections that match the parsed program entries.

If the PE section layout causes the user-mode calculation to produce a different count, the loop overflows the vector:

```cpp
for (int i = 0; i < count_of_programs; i++) {
    ebpf_program_t* program = programs[i];   // OUT OF BOUNDS when i >= programs.size()
    if (!program->autoload) {                 // CRASH: NULL dereference at offset 0x54
```

## Concrete Case That Exposed This

This was discovered loading Cilium BPF programs that include an unreferenced `BPF_MAP_TYPE_PROG_ARRAY` map (declared with `__attribute__((section(".maps"), used))` but with no `bpf_tail_call` references). The unreferenced prog array map changes the string table alignment in the bpf2c-generated PE `"programs"` section, causing the user-mode offset calculation in `_ebpf_pe_get_section_names()` to land at a different `program_offset`. The result: user-mode PE parsing discovers fewer programs than the kernel's compile-time array reports.

### Crash details

- **Instruction**: `cmp byte ptr [rsi+54h], 0` where `rsi` = NULL
- **Field**: `autoload` at offset 0x54 in `ebpf_program_t` (`api_internal.h`)

## Proposed Fix

Add bounds validation at the top of the loop:

```cpp
if (count_of_programs != programs.size()) {
    EBPF_LOG_MESSAGE_UINT64(
        EBPF_TRACELOG_LEVEL_ERROR,
        EBPF_TRACELOG_KEYWORD_API,
        "_initialize_ebpf_programs_native: program count mismatch",
        count_of_programs);
    result = EBPF_INVALID_ARGUMENT;
    goto Exit;
}
```

## Regression Test

A regression test is available on branch [`test/native-program-count-mismatch-oob`](https://github.com/microsoft/ebpf-for-windows/tree/test/native-program-count-mismatch-oob). The test:

1. Opens a valid native module via `bpf_object__open()` (populates `object->programs` from PE parsing).
2. Empties `object->programs` to simulate the count mismatch.
3. Calls `bpf_object__load()` inside an SEH `__try/__except` block.
4. Detects the access violation, confirming the bug.

After the fix, the test should pass without any crash (the function returns an error code instead).

## Impact

Without the fix, any metadata layout difference between the kernel-parsed and user-mode-parsed program counts causes an unrecoverable crash instead of a diagnosable error return. This makes root-cause analysis significantly harder — the crash at offset 0x54 from NULL gives no indication that a count mismatch is the underlying issue.

### PR DESCRIPTION
**Pull request by abeltrano**
## Problem

`_initialize_ebpf_programs_native` in `libs/api/ebpf_api.cpp` iterates using `count_of_programs` obtained from a kernel IOCTL reply without first validating it against `programs.size()` (populated from user-mode PE section parsing). When these two independently-sourced counts disagree, the loop reads past the `std::vector` bounds, dereferences a NULL/garbage pointer, and crashes with `EXCEPTION_ACCESS_VIOLATION` (0xC0000005) at offset 0x54 (the `autoload` field in `ebpf_program_t`).

### Two independent code paths produce the program count

| Source | Code path | How the count is derived |
|--------|-----------|--------------------------|
| **Kernel** (`count_of_programs`) | `_load_native_module()` → IOCTL `EBPF_OPERATION_LOAD_NATIVE_MODULE` → `_get_programs()` export | `sizeof(_programs)/sizeof(_programs[0])` — a **compile-time constant** from bpf2c-generated code |
| **User-mode** (`programs.size()`) | `_initialize_ebpf_object_from_native_file()` → `_ebpf_enumerate_native_programs()` → `_ebpf_pe_get_section_names()` + `_ebpf_pe_add_section()` | `(VirtualSize - program_offset) / sizeof(program_entry_t)`, then filtered by code sections with matching names |

Both should agree, but the user-mode path uses heuristic offset scanning (scanning for 16-byte-aligned zero markers in the PE `"programs"` section) followed by a code-section filter, while the kernel path uses a simple compile-time array size. Any change in PE section layout that shifts the string table alignment can cause the user-mode calculation to produce a different count.

### Concrete case that exposed this

Loading Cilium BPF programs that include an unreferenced `BPF_MAP_TYPE_PROG_ARRAY` map (declared with `__attribute__((section(".maps"), used))` but with no `bpf_tail_call` references). The unreferenced prog array map changes the string table size in the bpf2c-generated PE `"programs"` section, shifting the `program_offset` computed by `_ebpf_pe_get_section_names()`. The result: user-mode PE parsing discovers fewer programs than the kernel's compile-time array reports.

### The crash

```
for (int i = 0; i < count_of_programs; i++) {
    ebpf_program_t* program = programs[i];   // OOB when i >= programs.size()
    if (!program->autoload) {                 // deref NULL → AV at offset 0x54
```

## Fix

Add a bounds check at the top of `_initialize_ebpf_programs_native` that validates `count_of_programs == programs.size()` before entering the loop. On mismatch, the function logs the discrepancy and returns `EBPF_INVALID_ARGUMENT` instead of crashing:

```cpp
if (count_of_programs != programs.size()) {
    EBPF_LOG_MESSAGE_UINT64(
        EBPF_TRACELOG_LEVEL_ERROR,
        EBPF_TRACELOG_KEYWORD_API,
        "_initialize_ebpf_programs_native: program count mismatch",
        count_of_programs);
    result = EBPF_INVALID_ARGUMENT;
    goto Exit;
}
```

This is the minimal, correct fix because:

1. **Both counts must agree by design** — a mismatch means the PE file's metadata is inconsistent with the loaded driver, which is an unrecoverable state.
2. **The `Exit` label already handles cleanup** — `clean_up_ebpf_programs(programs)` is called on any non-success result, so no resource leaks.
3. **No behavioral change for correct inputs** — when counts agree (the normal case), execution proceeds exactly as before.

## Testing

A regression test (`native_program_count_mismatch_oob_access`) is included in this PR. The test:

1. Opens a valid native module via `bpf_object__open("droppacket_um.dll")` — populates `object->programs` from PE parsing.
2. Swaps `object->programs` to empty to simulate the kernel/PE count mismatch.
3. Calls `bpf_object__load()` inside an SEH `__try/__except` block to catch any access violation.
4. **Before fix**: detects `EXCEPTION_ACCESS_VIOLATION` → reports `FAIL("BUG: ...")`.
5. **After fix**: no crash, function returns error code → `REQUIRE(result < 0)` passes.

The test handles both debug builds (MSVC STL iterator debugging via custom `_invalid_parameter_handler`) and release builds (raw NULL-page access violation via SEH).

### Test results

| Configuration | Before fix | After fix |
|--------------|-----------|----------|
| Release x64 | `FAIL: access violation` | `All tests passed (20 assertions in 1 test case)` |

Resolves #5151

### CODE REVIEW

File: tests/unit/libbpf_test.cpp [hunk 1]
```diff
@@ -4489,4 +4492,147 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+    int result = _try_bpf_object_load_detect_av(object, &access_violation_detected);
+
+    // Phase 5: Restore state.
+    _set_invalid_parameter_handler(old_handler);
+#ifdef _DEBUG
+    _CrtSetReportMode(_CRT_ASSERT, old_assert_mode);
+    _CrtSetReportMode(_CRT_ERROR, old_error_mode);
+#endif
+    SetErrorMode(old_error_flags);
+    object->programs.swap(saved_programs);
```
[the remark this answers is not in the document]
Comment (abeltrano) [reply tests/unit/libbpf_test.cpp:4603]: Fixed in 6519312f. Now saves `get_native_module_failures()` before the test and restores it afterward.

File: tests/unit/libbpf_test.cpp [hunk 2]
```diff
@@ -4489,4 +4492,147 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+    // - Release: operator[] on empty vector reads from nullptr -> AV.
+    // - Debug: STL iterator debugging fires _invalid_parameter before
+    //   the memory access. Our custom handler converts it to an AV.
+    auto old_handler = _set_invalid_parameter_handler(_test_oob_invalid_parameter_handler);
+
+    // Suppress the CRT assertion dialog in debug builds so it doesn't
+    // block the test. Route assertions to debugger output only.
+#ifdef _DEBUG
+    int old_assert_mode = _CrtSetReportMode(_CRT_ASSERT, 0);
+    int old_error_mode = _CrtSetReportMode(_CRT_ERROR, 0);
```
[the remark this answers is not in the document]
Comment (abeltrano) [reply tests/unit/libbpf_test.cpp]: Fixed in 6519312f. Changed to `_CRTDBG_MODE_DEBUG` as suggested, so assertions go to debugger output rather than being fully suppressed.

File: tests/unit/libbpf_test.cpp [hunk 3]
```diff
@@ -4489,4 +4492,147 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+#endif
+
+    // Suppress Windows Error Reporting dialogs and Watson dumps.
+    UINT old_error_flags = SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
+    _set_abort_behavior(0, _WRITE_ABORT_MSG | _CALL_REPORTFAULT);
+
```
[the remark this answers is not in the document]
Comment (abeltrano) [reply tests/unit/libbpf_test.cpp:4585]: Fixed in 6519312f. Previous abort behavior is now captured and restored after the test.

File: tests/unit/libbpf_test.cpp [hunk 4]
```diff
@@ -4489,4 +4492,147 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+             "at the top of the loop in ebpf_api.cpp.");
+    } else {
+        // No crash. Either the bug is fixed (returns error code) or the
+        // OOB access did not crash (extremely unlikely with an empty
+        // vector whose data() is nullptr).
+        REQUIRE(result < 0);
+    }
+
+    bpf_object__close(object);
+}
```
[the remark this answers is not in the document]
Comment (abeltrano) [reply tests/unit/libbpf_test.cpp]: Fixed in 6519312f. Moved `bpf_object__close(object)` before the assertion block so cleanup always runs regardless of which path is taken.

File: tests/unit/libbpf_test.cpp [hunk 5]
```diff
@@ -4489,4 +4492,150 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+    //       ebpf_program_t* program = programs[i];   // OOB at i=0!
+    //       if (!program->autoload) { ...            // deref of null -> AV
+    //
+    bool old_native_failures = get_native_module_failures();
+    set_native_module_failures(true);
+    bool access_violation_detected = false;
+    int result = _try_bpf_object_load_detect_av(object, &access_violation_detected);
+
+    // Phase 5: Restore state.
+    set_native_module_failures(old_native_failures);
```
[the remark this answers is not in the document]
Comment (abeltrano) [reply tests/unit/libbpf_test.cpp]: Good catch on the round-trip semantics. Fixed in b1b2d016, but with a simpler approach than the RAII guard.

**The problem you identified**: `get_native_module_failures()` returns `_expect_native_module_load_failures || cxplat_fault_injection_is_enabled()`. If fault injection is active, the getter returns `true` regardless of the underlying flag, and `set_native_module_failures(true)` would permanently contaminate `_expect_native_module_load_failures`.

**The fix**: unconditionally restore to `false` instead of round-tripping through the getter:
```cpp
set_native_module_failures(false);
```

This is correct (and simpler than an RAII guard) because:
1. The underlying flag `_expect_native_module_load_failures` is initialized to `false` (test_helper.cpp line 42)
2. It is reset to `false` on every `_test_helper_end_to_end` initialization (test_helper.cpp line 799)
3. No test expects it to be `true` at entry — callers always explicitly set it before use
4. The RAII guard's destructor would do the same thing (`set_native_module_failures(false)`), just with more indirection

So we get the same correctness guarantee without introducing a new type.

**Comment by saxena-anurag** [comment]
With this fix, does it mean such a program cannot be loaded?

**Comment by abeltrano** [comment]
> With this fix, does it mean such a program cannot be loaded?

Yes. The program has to be put under a unique pe section name to be able to load it (at least, that's what was necessary in the scenario this was discovered in).

File: tests/unit/libbpf_test.cpp [hunk 6]
```diff
@@ -4489,4 +4492,149 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+    // Phase 6: Clean up and verify results.
+    bpf_object__close(object);
+
+    if (access_violation_detected) {
+        // BUG CONFIRMED: _initialize_ebpf_programs_native crashed because
+        // it accessed programs[i] where i >= programs.size() without first
+        // checking that count_of_programs <= programs.size().
+        //
+        // After the fix (adding a bounds check that returns
+        // EBPF_INVALID_ARGUMENT when counts disagree), this test should
```
Comment (dthaler) [inline tests/unit/libbpf_test.cpp]: Comments should not refer to bugs that no longer exist.

File: tests/unit/libbpf_test.cpp [hunk 7]
```diff
@@ -4489,4 +4492,149 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+        *access_violation_detected = true;
+        result = -1;
+    }
+    return result;
+}
+
+TEST_CASE("native_program_count_mismatch_oob_access", "[native][regression]")
+{
+    // This test verifies the bug in _initialize_ebpf_programs_native
+    // (ebpf_api.cpp line ~2208): the function iterates using
```
Comment (dthaler) [inline tests/unit/libbpf_test.cpp]: Comments should not refer to bugs that no longer exist.
They should also not refer to specific filenames or line numbers, since those can change
and leave comments like this pointing to nothing.

Comment (abeltrano) [reply tests/unit/libbpf_test.cpp]: Good point -- removed all references to the bug as if it still exists, stripped out specific file names, line numbers, and quoted code snippets. Comments now describe the test scenario generically (validates that a kernel/PE program count mismatch is rejected with an error). Fixed in 7645e971.

File: tests/unit/libbpf_test.cpp (hunk 6 above)
Comment (abeltrano) [reply tests/unit/libbpf_test.cpp]: Good point -- removed all references to the bug as if it still exists, stripped out specific file names, line numbers, and quoted code snippets. Comments now describe the test scenario generically (validates that a kernel/PE program count mismatch is rejected with an error). Fixed in 7645e971.

File: tests/unit/libbpf_test.cpp (hunk 7 above)
Comment (dthaler) [reply tests/unit/libbpf_test.cpp]: Unresolved since changes have not been pushed to github

Comment (dthaler) [reply tests/unit/libbpf_test.cpp]: @abeltrano the commit you reference is in the native-program-count-mismatch-oob branch but this PR is for the fix/native-program-count-bounds-check branch, so this comment is not yet resolved on this PR.

Comment (abeltrano) [reply tests/unit/libbpf_test.cpp]: Thanks for catching that, my topic branches for this fix got mixed up. Changes pushed to proper branch now, so moving this back to resolved.

File: tests/unit/libbpf_test.cpp [hunk 8]
```diff
@@ -4489,4 +4492,125 @@ _program_flags_test(ebpf_execution_type_t execution_type)
...
+    // - Release: operator[] on empty vector reads from nullptr -> AV.
+    // - Debug: STL iterator debugging fires _invalid_parameter before
+    //   the memory access. Our custom handler converts it to an AV.
+    auto old_handler = _set_invalid_parameter_handler(_test_oob_invalid_parameter_handler);
+
+    // Suppress the CRT assertion dialog in debug builds so it doesn't
+    // block the test. Route assertions to debugger output only.
+#ifdef _DEBUG
+    int old_assert_mode = _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_DEBUG);
+    int old_error_mode = _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_DEBUG);
```
Comment (saxena-anurag) [inline tests/unit/libbpf_test.cpp:4579]: nit: Should this use RAII so that even if the test fails, the old state is restored?
