### PR TITLE
Fix race condition between ebpf_epoch_terminate() and _ebpf_epoch_stale_worker()

### LINKED ISSUE #849: ebpf_epoch_terminate() frees _ebpf_flush_timer while the epoch stale worker is still running
### Describe the bug

Sometimes while stopping `ebpfcore`, there is a race between running `_ebpf_epoch_stale_worker` and `ebpf_epoch_terminate`.
`ebpf_epoch_terminate` cleans up _ebpf_flush_timer workitem, and in parallel `_ebpf_epoch_stale_worker` tries to access it, causing bugcheck.

### Affected OS

- [ ] Windows Server 2022
- [ ] Windows Server 2019
- [ ] Windows 11
- [ ] Windows 10
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Other (specify below)

### Additional OS information

_No response_

### Steps taken to reproduce bug

1. Run api_test.exe in a loop and immediately after that stop ebpfcore.

### Expected behavior

The machine should not bugcheck.

### Actual outcome

The machine bugchecks with below call stack:

```
5: kd> k
 # Child-SP          RetAddr               Call Site
00 ffffad09`1aa918b8 fffff806`373652c2     nt!DbgBreakPointWithStatus [minkernel\ntos\rtl\amd64\debugstb.asm @ 134] 
01 ffffad09`1aa918c0 fffff806`373649b3     nt!KiBugCheckDebugBreak+0x12 [minkernel\ntos\ke\bugcheck.c @ 692] 
02 ffffad09`1aa91920 fffff806`37248f17     nt!KeBugCheck2+0xba3 [minkernel\ntos\ke\bugcheck.c @ 2237] 
03 ffffad09`1aa92090 fffff806`3725bda9     nt!KeBugCheckEx+0x107 [minkernel\ntos\ke\amd64\procstat.asm @ 237] 
04 ffffad09`1aa920d0 fffff806`37257ce8     nt!KiBugCheckDispatch+0x69 [minkernel\ntos\ke\amd64\trap.asm @ 3895] 
05 ffffad09`1aa92210 fffff806`3705a114     nt!KiPageFault+0x468 [minkernel\ntos\ke\amd64\trap.asm @ 1668] 
06 (Inline Function) --------`--------     nt!KiAcquireKobjectLockSafe+0xb [minkernel\ntos\ke\waitsup.c @ 3225] 
07 (Inline Function) --------`--------     nt!KiAcquireKobjectLock+0xb [minkernel\ntos\ke\waitsup.c @ 3266] 
08 (Inline Function) --------`--------     nt!KiCancelTimer+0x1d [minkernel\ntos\ke\timersup.c @ 538] 
09 ffffad09`1aa923a0 fffff806`373ca35c     nt!KiSetTimerEx+0xa4 [minkernel\ntos\ke\timersup.c @ 2198] 
0a (Inline Function) --------`--------     nt!KeSetTimer+0x16 [minkernel\ntos\ke\timerobj.c @ 1229] 
0b ffffad09`1aa92480 fffff805`6b64b839     nt!DifKeSetTimerWrapper+0xdc [minkernel\ntos\dif\difx64wrappers.c @ 10496] 
0c ffffad09`1aa92500 fffff805`6b650169     ebpfcore!ebpf_schedule_timer_work_item+0x39 [E:\git\github\ebpf-for-windows-1\libs\platform\kernel\ebpf_platform_kernel.c @ 519] 
0d ffffad09`1aa92540 fffff805`6b6508ee     ebpfcore!_ebpf_epoch_release_free_list+0xd9 [E:\git\github\ebpf-for-windows-1\libs\platform\ebpf_epoch.c @ 432] 
0e ffffad09`1aa925b0 fffff805`6b650228     ebpfcore!ebpf_epoch_exit+0x14e [E:\git\github\ebpf-for-windows-1\libs\platform\ebpf_epoch.c @ 282] 
0f ffffad09`1aa925f0 fffff805`6b6493b5     ebpfcore!_ebpf_epoch_stale_worker+0x18 [E:\git\github\ebpf-for-windows-1\libs\platform\ebpf_epoch.c @ 131] 
10 ffffad09`1aa92620 fffff806`37120729     ebpfcore!_ebpf_deferred_routine+0x45 [E:\git\github\ebpf-for-windows-1\libs\platform\kernel\ebpf_platform_kernel.c @ 435] 
11 ffffad09`1aa92660 fffff806`3711ffcf     nt!KiExecuteAllDpcs+0x529 [minkernel\ntos\ke\dpcsup.c @ 2727] 
12 ffffad09`1aa929b0 fffff806`3724cd9e     nt!KiRetireDpcList+0xeff [minkernel\ntos\ke\dpcsup.c @ 3175] 
13 ffffad09`1aa92c40 00000000`00000000     nt!KiIdleLoop+0x9e [minkernel\ntos\ke\amd64\idle.asm @ 173] 
```

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by saxena-anurag**
## Description
Fixes #849

### Issue
If ebpfcore is stopped while a DPC is executing `_ebpf_epoch_stale_worker`, there is a race condition between `ebpf_epoch_terminate` cleaning up `_ebpf_flush_timer` workitem and the DPC using this workitem to queue another DPC.

### Fix
In function `ebpf_epoch_exit`, if `_ebpf_epoch_rundown` is set, do not call `_ebpf_epoch_release_free_list`. Once `ebpf_epoch_terminate` is called, it sets `_ebpf_epoch_rundown` to true and calls `_ebpf_epoch_release_free_list` for each CPU, so any pending epoch free items will anyways be cleaned up.

## Testing
Ran multiple iterations of following, and the issue did not repro.

1. Run api_test.exe in a loop and immediately after that stop ebpfcore.

It requires api_test changes done in PR https://github.com/microsoft/ebpf-for-windows/pull/840

## Documentation

NA

### CODE REVIEW

**Comment by shankarseal** [comment]
what is the effect of the race?

**Comment by saxena-anurag** [comment]
> what is the effect of the race?

We hit a bugcheck. I have provided the call stack also in the related bug (#849)

File: libs/platform/ebpf_epoch.c [hunk 1]
```diff
@@ -216,10 +216,8 @@ ebpf_epoch_terminate()
     EBPF_LOG_ENTRY();
     uint32_t cpu_id;
 
-    ebpf_free_timer_work_item(_ebpf_flush_timer);
-    _ebpf_flush_timer = NULL;
-
     _ebpf_epoch_rundown = true;
+
```
Comment (Alan-Jowett) [inline libs/platform/ebpf_epoch.c:220]: I don't think this fix is correct. Even if _ebpf_epoch_rundown is marked volatile, there is no guarantee that the DPC running the timer will have completed.

**Review by Alan-Jowett — APPROVED** [review]

**Review by shankarseal — APPROVED** [review]
