### PR TITLE
Fix fault injection crash in NmrRegisterClient

### LINKED ISSUE #5174: Workflow failed - fault_injection_full
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/24389580395)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/e3ea0f30492fe0abf44b90baa0d95622c822ecb2)
Test name - `fault_injection_full`
Event - schedule

### PR DESCRIPTION
**Pull request by nmlud21**
## Description

Fixes #5174 

 When fault injection causes an allocation failure inside ``NmrRegisterClient``, the function returns a failing ``NTSTATUS``. The code used ``assert(NT_SUCCESS(status))`` which calls ``abort()`` and produces a crash dump instead of allowing the test to fail gracefully.

 ### Root Cause
When ``REQUIRE()`` was replaced with ``assert()`` in ``_preprocess_load_native_module()`` for thread-safety, that introduced a bug. Previously, the ``REQUIRE()`` throw was silently caught by the ``catch(...)`` block in ``_preprocess_ioctl()``, masking the missing error handling. The switch to ``assert()`` exposed the latent bug since ``abort()`` cannot be caught.

## Fix
Follow the same pattern used elsewhere in the function for handling fault injection failures: check the return status, assert fault injection is enabled via ``get_native_module_failures()``, and return early without setting ``context->loaded``.                   

## Testing

No

## Documentation

No

## Installation

No

### CODE REVIEW

**Review by Alan-Jowett — DISMISSED** [review]

File: tests/end_to_end/test_helper.cpp [hunk 1]
```diff
@@ -410,8 +410,10 @@ _preprocess_load_native_module(_Inout_ service_context_t* context)
     assert(context->table != nullptr);
 
     NTSTATUS status = NmrRegisterClient(&context->nmr_client_characteristics, context, &context->nmr_client_handle);
-    assert(NT_SUCCESS(status));
-    UNREFERENCED_PARAMETER(status);
+    if (!NT_SUCCESS(status)) {
+        assert(get_native_module_failures());
+        return;
```
Comment (mikeagun) [inline tests/end_to_end/test_helper.cpp:420]:
```suggestion
        FreeLibrary(context->dll);
        context->dll = nullptr;
        context->table = nullptr;
        return;
```
Clean up handles on failure.

Also needed above in the `if (get_function == nullptr)` check.

**Review by mikeagun — APPROVED** [review]

**Review by saxena-anurag — APPROVED** [review]
