### PR TITLE
km_stress_test fixes

### LINKED ISSUE #4129: Workflow failed - km_mt_stress_tests
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/12722566338)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/d3fd4407675b77993b3e4a2a7c96f983432d532e)
Test name - `km_mt_stress_tests`

### PR DESCRIPTION
**Pull request by matthewige**
## Description
NetEbpfExt product changes:
- BUGFIX: Moved provider rundown initialization to before NMR registration, as the NMR registration could immediately trigger  NMR attach, therefore utilizing the not-yet-initialized rundown object.
- The zombie list logic was removed, as it's no longer needed. There were also issues with the zombie list logic, as the zombie list was accessed after the providers were cleaned up (the WFP notify callbacks were coming in after the provider unregister was invoked). [The issues with the zombie logic may have been only seen due to the bug]
- Minor refactoring of the rundown logic, to centralize rundown related code in a helper function.
- rundown_initialized flag added, which was largely used for debugging this issue. Left in place as it may be helpful if we run into similar issues in the future.

Issues found and fixed in tests:
- Test timeout for km_stress_test was far too low - this has been increased.
- Program files were being re-used across testcases. This was causing known issues with files being marked as in use, or issues where loading shortly after the program was unloaded was failing. To keep each testcase separate, this logic was modified to ensure that each test utilized a new copy of the program.
- Test scripts were updated to ensure that testcase failure results in a thrown exception, which properly marks the testcase as failed (this was not previously occurring, which could have led to false positives).
- With the updated Catch2, REQUIRE cannot be called in worker threads. Logic in the stress tests were updated to only call REQUIRE in the main thread, and pass back information to the main thread via the thread_context.

Closes #4129 #3602

## Testing
km_stress_tests were updated.

## Documentation
n/a

## Installation
n/a

### CODE REVIEW

File: netebpfext/net_ebpf_ext_hook_provider.c [hunk 1]
```diff
@@ -95,12 +110,17 @@ _ebpf_ext_attach_init_rundown(net_ebpf_extension_hook_client_t* hook_client)
...
  */
 static void
-_ebpf_ext_attach_wait_for_rundown(_Inout_ net_ebpf_ext_hook_rundown_t* rundown)
+_ebpf_ext_wait_for_rundown(_Inout_ net_ebpf_ext_hook_rundown_t* rundown)
 {
     NET_EBPF_EXT_LOG_ENTRY();
 
-    ExWaitForRundownProtectionRelease(&rundown->protection);
-    rundown->rundown_occurred = TRUE;
+    if (rundown->rundown_initialized == TRUE) {
```
Comment (matthewige) [inline netebpfext/net_ebpf_ext_hook_provider.c:117]: It looks to me like this is the crux of the fix. I haven't been able to reason out why this resolves the issue though.

Based on the test failure crash dump hang, we are waiting (forever) on DriverUnload. In that code path, I can't find a place where we would be invoking this function on an uninitialized rundown object.

File: scripts/run_driver_tests.psm1 [hunk 2]
```diff
@@ -460,7 +459,7 @@ function Invoke-ConnectRedirectTest
 function Invoke-CICDStressTests
 {
     param([parameter(Mandatory = $true)][bool] $VerboseLogs,
-          [parameter(Mandatory = $false)][int] $TestHangTimeout = 3600,
+          [parameter(Mandatory = $false)][int] $TestHangTimeout = (45*60),
```
Comment (matthewige) [inline scripts/run_driver_tests.psm1:462]: The stress tests were NOT passing any timeout value, which would mean a default of 10 minutes. However, there are multiple stress test cases, which each utilize the -td=5 (5 minutes) test parameter. So surely this is insufficient.

This looks like it might be the RCA of the km_stress_test failures, but NOT the RCA of the km_stress_test with restart extension failures.

File: netebpfext/net_ebpf_ext_hook_provider.c [hunk 3]
```diff
@@ -743,8 +771,7 @@ net_ebpf_extension_hook_provider_register(
     memset(local_provider_context, 0, sizeof(net_ebpf_extension_hook_provider_t));
     ExInitializePushLock(&local_provider_context->lock);
     InitializeListHead(&local_provider_context->filter_context_list);
-    ExInitializePushLock(&local_provider_context->zombie_list_lock);
-    InitializeListHead(&local_provider_context->zombie_filter_context_list);
+    _ebpf_ext_init_hook_rundown(&local_provider_context->rundown);
```
Comment (matthewige) [inline netebpfext/net_ebpf_ext_hook_provider.c:774]: On my testing, this looked to be the root cause of the issues - sometimes, the NMR register was immediately triggering the attach callback, which (without this change) was causing us to use an uninitialized rundown struct.

This fix resolves this issue by moving initialization to before NMR register, ensuring that only valid access is guaranteed.

**Comment by matthewige** [comment]
Currently, the km stress tests are only executed on scheduled builds. See previous commit of this change, which enabled them for testing purposes: https://github.com/microsoft/ebpf-for-windows/actions/runs/13187224523/job/36812126043?pr=4117

Both km_stress_tests and the restart extension versions validated 3 times.

File: tests/stress/km/stress_tests_km.cpp [hunk 4]
```diff
@@ -1550,4 +1751,4 @@ TEST_CASE("bindmonitor_tail_call_invoke_program_test", "[native_mt_stress_test]"
     _print_test_control_info(local_test_control_info);
     _mt_bindmonitor_tail_call_invoke_program_test(local_test_control_info);
 }
-#endif
+#endif // ENABLE_TAIL_CALL_STRESS_TEST
```
Comment (matthewige) [inline tests/stress/km/stress_tests_km.cpp:1754]: NOTE: This PR does NOT resolve the issues with this testcase. It still appears to be broken/failing.

**Review by Alan-Jowett — APPROVED** [review]

**Review by mikeagun — APPROVED** [review]
