### PR TITLE
Fix `bpf obj get()` behavior.

### LINKED ISSUE #3234: `bpf_obj_get()` should set correct `errno`
Currently `bpf_obj_get()` returns the object fd if it succeeds, `ebpf_fd_invalid` otherwise.
Internally `bpf_obj_get()` calls `ebpf_object_get()`.

Since `ebpf_object_get()` does not return any error code, it is difficult to determine if the entry was not found, or the API call failed due to some other reasons.

Proposal:

Update `ebpf_object_get()` API to return error code, and then `bpf_obj_get()` can set the correct `errno` before returning.

### PR DESCRIPTION
**Pull request by gtrevi**
Fixes #3234

## Description
Fixes the behavior of `bpf_obj_get()` to comply with the official specs: https://docs.kernel.org/userspace-api/ebpf/syscall.html

## Testing

CI/CD

## Documentation

n.a.

## Installation

n.a.

### CODE REVIEW

File: libs/api/ebpf_api.cpp [hunk 1]
```diff
@@ -2958,8 +2963,9 @@ _ebpf_object_reuse_map(_Inout_ ebpf_map_t* map) NO_EXCEPT_TRY
 
     ebpf_assert(map);
 
-    // Check if a map is already present with this pin path.
-    fd_t map_fd = ebpf_object_get(map->pin_path);
+    // If there is no map at this pin path, then we can (re)use the map.
+    fd_t map_fd = ebpf_fd_invalid;
+    result = ebpf_object_get(map->pin_path, &map_fd);
     if (map_fd == ebpf_fd_invalid) {
```
Comment (dthaler) [inline libs/api/ebpf_api.cpp:2969]: Seems like this should check for a specific result value that means there's no map at this pin path.

File: tests/unit/libbpf_test.cpp [hunk 2]
```diff
@@ -529,6 +530,14 @@ TEST_CASE("libbpf program pinning", "[libbpf]")
     REQUIRE(result < 0);
     REQUIRE(errno == EEXIST);
 
+    // Test bpf_obj_get() to return the fd and correctly set 'errno'
```
Comment (dthaler) [inline tests/unit/libbpf_test.cpp:533]:
```suggestion
    // Test bpf_obj_get() to return the fd and correctly set 'errno'.
```

File: libs/api/ebpf_api.cpp (hunk 1 above)
Comment (gtrevi) [reply libs/api/ebpf_api.cpp:2969]: Agree, the previous code can b refactored.

File: libs/api/ebpf_api.cpp [hunk 3]
```diff
@@ -1424,19 +1426,22 @@ ebpf_object_get(_In_z_ const char* path) NO_EXCEPT_TRY
...
+        *fd = (fd_t)ebpf_fd_invalid;
+        EBPF_RETURN_RESULT(win32_error_code_to_ebpf_result(result));
     }
 
     ebpf_assert(reply.header.id == ebpf_operation_id_t::EBPF_OPERATION_GET_PINNED_OBJECT);
 
     ebpf_handle_t handle = reply.handle;
-    fd_t fd = _create_file_descriptor_for_handle(handle);
-    if (fd == ebpf_fd_invalid) {
+    *fd = _create_file_descriptor_for_handle(handle);
```
Comment (dthaler) [inline libs/api/ebpf_api.cpp:1436]: I believe _open_osfhandle sets errno.  Hence you could update the _create_file_descriptor_for_handle() prototype to return the EBPF error rather than simply assuming it's EBPF_NO_MEMORY.

Comment (gtrevi) [reply libs/api/ebpf_api.cpp:1436]: For coherence, I preserved the same behavior for all `_create_file_descriptor_for_handle` calls across the rest of the code, all returning EBPF_NO_MEMORY.

**Review by matthewige — APPROVED** [review]

**Review by dthaler — APPROVED** [review]
