### PR TITLE
perform a default action if the XDP program fails

### LINKED ISSUE #2002: XDP extension leaks cloned NBLs when eBPF program fails
### Describe the bug

If `net_ebpf_extension_hook_invoke_program` fails, the XDP extension fails to perform any action at all, causing the inspected NBL to be implicitly passed to the stack and any cloned NBL to be leaked.

### OS information

N/A.

### Steps taken to reproduce bug

N/A - spotted during code review.

### Expected behavior

NBLs should not be leaked by the XDP extension.

### Actual outcome

NBLs are leaked if the XDP program fails.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by mtfriesen**
## Description

Spotted during code review while working on a different bug: if the eBPF program fails, the XDP extension implicitly passes the packet to the stack and leaks any cloned NBL. Update the XDP extension to explicitly perform an `XDP_DROP` action. Also assert that any unexpected XDP action is not returned and `XDP_DROP` the packet if it does.
Resolves #2002 

## Testing

CI/CD.

## Documentation

N/A.

### CODE REVIEW

File: netebpfext/net_ebpf_ext_xdp.c [hunk 1]
```diff
@@ -667,42 +667,49 @@ net_ebpf_ext_layer_2_classify(
...
-            _net_ebpf_ext_handle_xdp_tx(&net_xdp_ctx, incoming_fixed_values);
-            // Absorb the original NBL.
-            classify_output->actionType = FWP_ACTION_BLOCK;
-            classify_output->rights &= ~FWPS_RIGHT_ACTION_WRITE;
-            classify_output->flags |= FWPS_CLASSIFY_OUT_FLAG_ABSORB;
-            break;
-        case XDP_DROP:
+    if (net_ebpf_extension_hook_invoke_program(attached_client, &net_xdp_ctx, &result) != EBPF_SUCCESS) {
+        // Perform a default action if the program fails.
+        result = XDP_PASS;
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext_xdp.c:672]: Shouldn't this be XDP_DROP by default, i.e., secure-by-default?

Comment (mtfriesen) [reply netebpfext/net_ebpf_ext_xdp.c:672]: Great question, and I tried to sidestep this by simply codifying the current "do-nothing-by-default" behavior. I had a few questions:

1. Is dropping every packet, which effectively takes the machine off the network, more secure than allowing all packets through to the machine? Is this a self-DoS?
2. What if the XDP program isn't intended for DDoS protection, e.g. a simple packet monitor, and the system may start experiencing transient packet loss with eBPF + XDP? Is this going to be disruptive, especially if the program may "fail" for nontrivial time intervals?
3. Should eBPF itself take responsibility for providing a default result if the program fails? In other words, should eBPF mask any internal failure and obviate the need for this check within a hook/extension? This doesn't affect _what_ action is returned, but moving this check to eBPF allows the default policy to be decoupled from the hook implementation.

Comment (saxena-anurag) [reply netebpfext/net_ebpf_ext_xdp.c:672]: Looking at the code, even though `net_ebpf_extension_hook_invoke_program` returns an error code (look at `_ebpf_link_instance_invoke`), it looks like should not fail in normal conditions. Also, we acquire rundown reference before invoking the program, so it is guaranteed that the program is not getting detached. In the case `net_ebpf_extension_hook_invoke_program` fails, I think we should drop the packet since there is an eBPF program attached to the hook, which execution context is failing to invoke.

Comment (dthaler) [reply netebpfext/net_ebpf_ext_xdp.c:672]: > Is dropping every packet, which effectively takes the machine off the network, more secure than allowing all packets through to the machine?

Definitely more secure if there is no network access.

> Should eBPF itself take responsibility for providing a default result if the program fails?

I agree with Anurag's answer.

Comment (mtfriesen) [reply netebpfext/net_ebpf_ext_xdp.c]: Fair enough; I've updated the default action to `XDP_DROP` and will take the same action within xdp-for-windows.

File: netebpfext/net_ebpf_ext_xdp.c [hunk 2]
```diff
@@ -667,42 +667,49 @@ net_ebpf_ext_layer_2_classify(
...
-            _net_ebpf_ext_handle_xdp_tx(&net_xdp_ctx, incoming_fixed_values);
-            // Absorb the original NBL.
-            classify_output->actionType = FWP_ACTION_BLOCK;
-            classify_output->rights &= ~FWPS_RIGHT_ACTION_WRITE;
-            classify_output->flags |= FWPS_CLASSIFY_OUT_FLAG_ABSORB;
-            break;
-        case XDP_DROP:
+    if (net_ebpf_extension_hook_invoke_program(attached_client, &net_xdp_ctx, &result) != EBPF_SUCCESS) {
+        // Perform a default action if the program fails.
+        result = XDP_DROP;
```
Comment (saxena-anurag) [inline netebpfext/net_ebpf_ext_xdp.c:672]: Should we add a trace stating that program invocation failed?

Comment (mtfriesen) [reply netebpfext/net_ebpf_ext_xdp.c:672]: Hmm, the precedent here isn't entirely clear. It's potentially going to be a noisy trace if the program fails for a long time, but it's also a critical trace if we're wondering why the eBPF program actions aren't taking effect. I'd lean towards not handling this here and hoping that eBPF core has logging that is useful without being noisy, e.g. throttled logs.

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
