### PR TITLE
Helper reallocate packet

### LINKED ISSUE #3090: eBPF does not support helper functions that modify direct packet data
### Describe the bug

On Linux, several BPF helpers are documented as potentially invalidating the direct packet access pointers (e.g. `data` and `data_end`), and so the verifier checks the pointers are re-validated by the program after the helper returns.

Is this implemented for Windows helpers? Would this be provided by the `reallocate_packet` field in the ebpf-verifier project?

Example from the Linux man pages for the `bpf_skb_pull_data` function:

> A call to this helper is susceptible to change the underlying packet buffer.
Therefore, at load time, all checks on pointers previously done by the
verifier are invalidated and must be performed again, if the helper is used
in combination with direct packet access.

### OS information

N/A.

### Steps taken to reproduce bug

Attempt to implement an extension that modifies the direct packet access pointers, and discover there is no characteristic to indicate the modification to the verifier.

### Expected behavior

A helper that modifies packet data should indicate to eBPF, and the verifier should require programs revalidate data after calling the helper.

### Actual outcome

There is no field that can be set to indicate this behavior to eBPF. Helpers today do not invalidate packet data by default.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by shankarseal**
## Description

This fixes #3090. A `reallocate_packet` flag is added to the helper function prototype metadata, to pass onto the PREVAIL verifier, to validate programs that uses any helper function that may change the packet pointers such as `xdp_adjust_head`.

## Testing

A new netsh tests is added that tries to load an unsafe XDP program and fails.

## Documentation

Updated extension documentation.

## Installation

No changes to installation.

### CODE REVIEW

File: tests/sample/unsafe/xdp_adjust_head_unsafe.c [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+SEC("xdp")
+int
+xdp_adjust_head_unsafe(xdp_md_t* ctx)
+{
+    int rc = XDP_PASS;
+
+    ETHERNET_HEADER* ethernet_header = NULL;
+    char* next_header = (char*)ctx->data;
+    if (next_header + sizeof(ETHERNET_HEADER) > (char*)ctx->data_end) {
```
Comment (mtfriesen) [inline tests/sample/unsafe/xdp_adjust_head_unsafe.c:23]: This program is unsafe even without the reallocate_packet check...

File: tests/sample/unsafe/xdp_adjust_head_unsafe.c [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+        goto Done;
+    }
+
+    // Adjust the head of the packet
+    if (bpf_xdp_adjust_head(ctx, sizeof(ETHERNET_HEADER) < 0)) {
```
Comment (saxena-anurag) [inline tests/sample/unsafe/xdp_adjust_head_unsafe.c:28]: Should this be

`if (bpf_xdp_adjust_head(ctx, sizeof(ETHERNET_HEADER)) < 0)) {` ?

File: tests/sample/unsafe/xdp_adjust_head_unsafe.c (hunk 1 above)
Comment (mtfriesen) [reply tests/sample/unsafe/xdp_adjust_head_unsafe.c:23]: specifically, the check here is that the ethernet header fits within ctx->data_end, and then the helper function gets called, and then the program tries to read past the original ctx->data_end. there's no need to advance or retreat the XDP buffer in the helper: the delta can be zero, and the program can try to read/write the pointer it safely used before the helper function, and the identical pointer (and identical packet, because delta == 0) should be treated as unsafe.

the more pointer arithmetic and deltas get added, the more convoluted the test becomes, with no additional safety.

File: include/ebpf_program_types.h [hunk 3]
```diff
@@ -7,12 +7,14 @@
...
 #include <guiddef.h>
 #if !defined(NO_CRT) && !defined(_NO_CRT_STDIO_INLINE)
+#include <stdbool.h>
 #include <stdint.h>
 #else
 typedef unsigned char uint8_t;
 typedef unsigned int uint32_t;
 typedef unsigned long long uint64_t;
 typedef unsigned short wchar_t;
+#define bool _Bool
```
Comment (dthaler) [inline include/ebpf_program_types.h:17]: I thought if you did line 10 you shouldn't need line 17

File: tests/sample/unsafe/xdp_adjust_head_unsafe.c (hunk 1 above)
Comment (shankarseal) [reply tests/sample/unsafe/xdp_adjust_head_unsafe.c:26]: > specifically, the check here is that the ethernet header fits within ctx->data_end, and then the helper function gets called, and then the program tries to read past the original ctx->data_end. there's no need to advance or retreat the XDP buffer in the helper: the delta can be zero, and the program can try to read/write the pointer it safely used before the helper function, and the identical pointer (and identical packet, because delta == 0) should be treated as unsafe.
> 
> the more pointer arithmetic and deltas get added, the more convoluted the test becomes, with no additional safety.

I modified the program to modify the ethernet type in lines 31 and 42. The verifier complains for line 42 and not line 31. Line 42 is indeed unsafe as there is no guarantee that post adjustment, the buffer length is at least as long as the ETHERNET_HEADER. I also verified that if I set `reallocate_packet` to false, then the entire program passes verification. Note that there are two sample programs (`encap_reflect_packet` and `decap_permit_packet`) that use the adjust_head helper and immediately checks for packet bounds before accessing it. Both those programs pass verifier.

File: include/ebpf_program_types.h (hunk 3 above)
Comment (shankarseal) [reply include/ebpf_program_types.h:17]: Dave they are in #if and #else respectively. `stdbool` is good for user mode binaries. Whereas the KM binaries cannot include stdbool.

File: tests/sample/unsafe/xdp_adjust_head_unsafe.c (hunk 1 above)
Comment (shankarseal) [reply tests/sample/unsafe/xdp_adjust_head_unsafe.c:26]: I modified the program to modify the ethernet type in lines 31 and 42. The verifier complains for line 42 and not line 31. Line 42 is indeed unsafe as there is no guarantee that post adjustment, the buffer length is at least as long as the ETHERNET_HEADER. I also verified that if I set reallocate_packet to false, then the entire program passes verification. Note that there are two sample programs (encap_reflect_packet and decap_permit_packet) that use the adjust_head helper and immediately checks for packet bounds before accessing it. Both those programs pass verifier.

**Review by mtfriesen — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
