### PR TITLE
Serialize "check and create" map logic in ebpf_native to fix race condition

### LINKED ISSUE #4398: Serialize "check and create" map logic in ebpf_native
Today, if 2 native programs are being loaded in parallel, and the map is "reused" using LIBBPF_PIN_BY_NAME, there is a race possible where both threads try to create the map and "reuse". This can be fixed by serializing the "test and set" for map pin path in ebpf native.

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #4398

This pull request introduces a new lock to serialize access to map pinning operations in the eBPF native execution context, addressing potential race conditions when multiple threads load programs in parallel. The changes focus on the safe creation and reuse of pinned maps and ensure proper lock management during initialization, termination, and error handling.

**Thread safety for map pinning:**

* Added a new lock variable `ebpf_lock_t _ebpf_native_map_pinning_lock` to serialize access to map pinning operations, preventing race conditions when multiple threads interact with pinned maps.
* Updated `_ebpf_native_create_maps` to acquire and release the new map pinning lock specifically when handling maps with `LIBBPF_PIN_BY_NAME`, ensuring atomic "check and create" logic for pinned maps. [[1]](diffhunk://#diff-c2246e5ec5594b061b298b0947eb7f2e3fd28fc8570d4ded49bb9ce50e7567e3R1489-R1490) [[2]](diffhunk://#diff-c2246e5ec5594b061b298b0947eb7f2e3fd28fc8570d4ded49bb9ce50e7567e3R1526-R1537) [[3]](diffhunk://#diff-c2246e5ec5594b061b298b0947eb7f2e3fd28fc8570d4ded49bb9ce50e7567e3R1571-R1582)

**Lifecycle management for new lock:**

* Ensured the new map pinning lock is created during initialization (`ebpf_native_initiate`) and destroyed during termination (`ebpf_native_terminate`), as well as on error paths, to prevent resource leaks. [[1]](diffhunk://#diff-c2246e5ec5594b061b298b0947eb7f2e3fd28fc8570d4ded49bb9ce50e7567e3R1028) [[2]](diffhunk://#diff-c2246e5ec5594b061b298b0947eb7f2e3fd28fc8570d4ded49bb9ce50e7567e3R670) [[3]](diffhunk://#diff-c2246e5ec5594b061b298b0947eb7f2e3fd28fc8570d4ded49bb9ce50e7567e3R1082)## Description

## Testing

Does not add tests, as this is race condition, and issue was found via code review.

## Documentation

No

## Installation

No

### CODE REVIEW

File: libs/execution_context/ebpf_native.c [hunk 1]
```diff
@@ -1516,11 +1523,18 @@ _ebpf_native_create_maps(_Inout_ ebpf_native_module_instance_t* instance)
...
+            // Serialize the "check and create" map logic for LIBBPF_PIN_BY_NAME maps
+            // to prevent race conditions when multiple threads load programs in parallel
+            pinning_lock_state = ebpf_lock_lock(&_ebpf_native_map_pinning_lock);
+            map_pinning_lock_acquired = true;
+
             result = _ebpf_native_reuse_map(native_map);
             if (result != EBPF_SUCCESS) {
                 break;
             }
             if (native_map->reused) {
```
Comment (Alan-Jowett) [inline libs/execution_context/ebpf_native.c:1535]: Won't this deadlock of the map is not re-used? It will loop around and try to acquire the lock recursively?

File: libs/execution_context/ebpf_native.c [hunk 2]
```diff
@@ -1516,11 +1523,18 @@ _ebpf_native_create_maps(_Inout_ ebpf_native_module_instance_t* instance)
         }
 
         if (native_map->entry.definition.pinning == LIBBPF_PIN_BY_NAME) {
+            // Serialize the "check and create" map logic for LIBBPF_PIN_BY_NAME maps
+            // to prevent race conditions when multiple threads load programs in parallel
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.c]:
```suggestion
            // to prevent race conditions when multiple threads load programs in parallel.
```

File: libs/execution_context/ebpf_native.c (hunk 1 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c:1535]: The lock is being released at line 1572 before this loop completes.

Comment (Alan-Jowett) [reply libs/execution_context/ebpf_native.c:1535]: You are correct. I misread the scope.

**Review by mikeagun — APPROVED** [review]
