### PR TITLE
Fix program info hash algorithm

### LINKED ISSUE #2560: program_info_hash is too strict in the case a new helper function is added
Currently, `program_info_hash` takes into account all the global and program type specific helper functions when creating a hash.

If a new global or program type specific helper function is added, this will invalidate the hash of any already existing native ebpf programs.

We cannot expect every consumer of eBPF to regenerate their native drivers whenever a new version of eBPF is released (as they will have no way to track if any new helper functions have been added in eBPF framework).

Same is applicable for any other changes done which can change the hash (the changes should be backward compatible)

### PR DESCRIPTION
**Pull request by saxena-anurag**
## Description

Fixes #2560

This PR fixes the program info hash algorithm. The algorithm now only includes the helper functions which are actually used by the ebpf program.

Following is the new flow for when the hash is computed and / or compared.

**JIT / Interpret**
1. eBPF service calls RESOLVE_HELPERS (This is now done even when there are 0 helpers for the program). 
2. RESOLVE_HELPERS sets the helper functions in the program object in ebpfcore, and also computes and stores the hash (if not already stored at program creation -- applicable for native mode).
3. When program info provider attaches, it checks if helper functions have been set. If yes, it recomputes the hash and compares with the stored value. If helper functions have not been set yet, skips hash comparison. 
4. eBPFsvc then queries program info for verification.
5. Once helpers have been set (and hash has been stored), any re-attach of the provider will cause re-check of the hash.

**Native Mode**
1. In native mode, hash is precomputed and stored in the native module.
2. Native module creates program object and passes the hash along with that.
3. Native module calls resolve_helpers() (This is now done even when there are 0 helpers for the program).
4. Since program hash is already set, resolve_helpers() recomputes the hash and compares with the value stored in the program object.

## Testing

Existing CICD. Since this is breaking change, regression test for `0.9.0` is removed.

## Documentation

No

## Installation

No.

### CODE REVIEW

**Review by Alan-Jowett — DISMISSED** [review]

File: libs/execution_context/ebpf_native.c [hunk 1]
```diff
@@ -1187,9 +1184,11 @@ _ebpf_native_resolve_helpers_for_program(
         goto Done;
     }
 
-    // Update the addresses in the helper entries.
-    for (uint16_t i = 0; i < helper_count; i++) {
-        helpers[i].address = helper_addresses[i];
+    if (helper_count > 0) {
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.c:1187]: This if test is not necessary since line 1189 will already do the check as part of the i<helper_count initial check.
Hence can revert the change to this block to keep code complexity lower.

File: libs/service/api_service.cpp [hunk 2]
```diff
@@ -80,11 +64,40 @@ _build_helper_id_to_address_map(
...
+    for (auto [helper_id, helper_address] : helper_id_to_address) {
+        helper_id_mapping[helper_id] = index++;
+    }
+
+    if (helper_id_mapping.size() == 0) {
+        return EBPF_SUCCESS;
+    }
+
+    // uBPF jitter supports a maximum of 64 helper functions
+    if (helper_id_mapping.size() > 64) {
```
Comment (dthaler) [inline libs/service/api_service.cpp:99]: does uBPF really provide no define macro that can be used instead of hard coding 64 here? 
@Alan-Jowett  If it doesn't then we should file an issue against uBPF.
Looks like right now it's an internal-only define:
```
vm\ubpf_vm.c:#define MAX_EXT_FUNCS 64
```
Either way, we should use a macro in our repo and not hard code 64 here.
So for now do something in this file like:
```
// TODO(<insert ubpf issue number here>): uBPF has a max number of helper functions hard coded,
// but doesn't expose the define to callers, so we define it here.
#define UBPF_MAX_EXT_FUNCS 64
```

File: libs/execution_context/ebpf_core.c [hunk 3]
```diff
@@ -423,17 +431,15 @@ _ebpf_core_protocol_resolve_helper(
...
-    }
-
-    request_helper_ids = (uint32_t*)ebpf_allocate_with_tag(count_of_helpers * sizeof(uint32_t), EBPF_POOL_TAG_CORE);
-    if (request_helper_ids == NULL) {
-        return_value = EBPF_NO_MEMORY;
-        goto Done;
-    }
-    for (helper_index = 0; helper_index < count_of_helpers; helper_index++) {
-        request_helper_ids[helper_index] = request->helper_id[helper_index];
+    if (count_of_helpers != 0) {
```
Comment (matthewige) [inline libs/execution_context/ebpf_core.c:434]: To check my understanding - in your change, when count_of_helpers is 0 we now need to invoke ebpf_core_resolve_helper() (when we previously didn't) because we need to ensure that ebpf_program_set_program_info_hash() is invoked?

File: tests/api_test/api_test.cpp [hunk 4]
```diff
@@ -1001,8 +1001,6 @@ test_sock_addr_native_program_load_attach(const char* file_name)
         test_sock_addr_native_program_load_attach((const char*)"cgroup_sock_addr2_"##version ".sys"); \
     }
 
-DECLARE_REGRESSION_TEST_CASE("0.9.0")
```
Comment (dthaler) [inline tests/api_test/api_test.cpp:1004]: Maybe comment it out with a TODO and an issue number to put it back in here in the next release?

File: libs/execution_context/ebpf_program.c [hunk 5]
```diff
@@ -1863,38 +2005,55 @@ _ebpf_program_compute_program_information_hash(
...
-        helper_id_to_index[helper_function_index].helper_id =
-            general_program_info->program_type_specific_helper_prototype[index].helper_id;
-        helper_id_to_index[helper_function_index].helper_function_prototype =
-            &general_program_info->program_type_specific_helper_prototype[index];
-        helper_function_index++;
-    }
+        // Copy global helpers to helper_id_to_index.
+        for (uint32_t index = 0; index < general_program_info->count_of_program_type_specific_helpers; index++) {
+            uint32_t helper_id = general_program_info->program_type_specific_helper_prototype[index].helper_id;
+            if (!_ebpf_contains_helper_id(actual_helper_ids, count_of_actual_helper_ids, helper_id)) {
```
Comment (matthewige) [inline libs/execution_context/ebpf_program.c:2023]: Is this (and the below) expensive in practice? Is there any way we can optimize this a bit? (I see below sorts the output for example. Is actual_helper_ids sorted at all?)

File: libs/service/api_service.cpp (hunk 2 above)
Comment (matthewige) [inline libs/service/api_service.cpp:99]: Can we check helper_id_to_address.size() as the first check and return error if > 64, as opposed to populating the map only to see it fail?

File: libs/execution_context/ebpf_program.c (hunk 5 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_program.c:2023]: Yes we could ideally try to optimize it. But this is in control path when the program is being loaded. `actual_helper_ids` may or may not be sorted today (for JIT modules, it is sorted, but for native, it is not).

File: tests/api_test/api_test.cpp (hunk 4 above)
Comment (saxena-anurag) [reply tests/api_test/api_test.cpp:1004]: Added.

File: libs/execution_context/ebpf_program.c [hunk 6]
```diff
@@ -1592,6 +1608,116 @@ ebpf_program_set_helper_function_ids(
...
+
+    general_program_information_data = (ebpf_program_data_t*)program->general_helper_provider_data->data;
+    type_specific_program_information_data = (ebpf_program_data_t*)program->info_extension_provider_data->data;
+    actual_helper_function_ids = program->helper_function_ids;
+    actual_helper_function_count = program->helper_function_count;
+
+    ebpf_lock_unlock(&program->lock, state);
+    lock_held = false;
+
+    // Compute the hash of the program information. This requires passive IRQL and must be done outside the lock.
```
[the remark this answers is not in the document]
Comment (saxena-anurag) [reply libs/execution_context/ebpf_program.c:1675]: Fixed.

File: libs/service/api_service.cpp (hunk 2 above)
Comment (saxena-anurag) [reply libs/service/api_service.cpp]: Done

File: libs/execution_context/ebpf_program.c [hunk 7]
```diff
@@ -1592,6 +1608,116 @@ ebpf_program_set_helper_function_ids(
...
+    } else {
+        // Set the program info hash.
+        program->parameters.program_info_hash_length = hash_length;
+        program->parameters.program_info_hash = hash;
+        hash = NULL;
+    }
+
+Exit:
+    ebpf_free(hash);
+    ebpf_free(hash_algorithm.value);
```
[the remark this answers is not in the document]
Comment (saxena-anurag) [reply libs/execution_context/ebpf_program.c]: Done

File: libs/service/api_service.cpp (hunk 2 above)
Comment (saxena-anurag) [reply libs/service/api_service.cpp]: Added.

File: libs/execution_context/ebpf_program.c [hunk 8]
```diff
@@ -1836,6 +1973,9 @@ _ebpf_helper_id_to_index_compare(const void* lhs, const void* rhs)
  * Notes on why this works:
  * 1) The user application creates an ebpf_program_t object and sets the program type.
  * 2) During initialization, the program binds to the program information provider.
+ * 3.1) For JIT and interpret mode, before verification, ebpfsvc resolves the helper functions for the program.
+ * 3.2) For native mode, hash from native module is set in the program object.
+ * 4) When helper addresses are resolved for this program, the program information is hashed and stored.
  * 3) During the attach callback, the program information is hashed and stored.
```
[the remark this answers is not in the document]
Comment (saxena-anurag) [reply libs/execution_context/ebpf_program.c]: Fixed the sequence.

File: libs/service/api_service.cpp [hunk 9]
```diff
@@ -80,11 +64,40 @@ _build_helper_id_to_address_map(
...
+    uint32_t index = 0;
+    for (auto [helper_id, helper_address] : helper_id_to_address) {
+        helper_id_mapping[helper_id] = index++;
+    }
+
+    if (helper_id_mapping.size() == 0) {
+        return EBPF_SUCCESS;
+    }
+
+    // uBPF jitter supports a maximum of 64 helper functions
```
[the remark this answers is not in the document]
Comment (saxena-anurag) [reply libs/service/api_service.cpp]: Fixed.

**Review by dthaler — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
