### PR TITLE
socket tests and redirection tests does not clean up bpf_object on failure

### LINKED ISSUE #2203: socket tests and redirection tests does not clean up bpf_object on failure
The socket and redirect tests allocate bpf object on heap during test variation setup. Since Catch2::REQUIRE throws an exception upon failure, the bpf_object does not get closed. This causes problem for the next variation that will fail to load the eBPF program as it is still loaded. So when one of these tests fail, all subsequent tests fail.

One solution could be to have a `std::unique_ptr` wrapper class around bpf_object used in these tests.

### PR DESCRIPTION
**Pull request by delaramamiri**
closes #2203 
## Description

The socket and redirect tests allocate bpf object on the heap during test variation setup. Since Catch2::REQUIRE throws an exception upon failure, the bpf_object does not get closed. This causes a problem for the next variation that will fail to load the eBPF program as it is still loaded. So when one of these tests fails, all subsequent tests fail.

One solution could be to have a std::unique_ptr wrapper class around bpf_object used in these tests.

## Testing

These tests are invoked in socket_tests.exe, inside sock_addr_invoke API.
Build the visual studio successfully without any error on local machine.
 socket_tests.exe passed on the VM. 

CICD build pipeline is not failing.
## Documentation

N/A

### CODE REVIEW

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 1]
```diff
@@ -296,15 +315,15 @@ _load_and_attach_ebpf_programs(_Outptr_ struct bpf_object** return_object)
...
+        bpf_program* connect_program_v6 = bpf_object__find_program_by_name(unique_object.get(), "connect_redirect6");
         REQUIRE(connect_program_v6 != nullptr);
 
         result = bpf_prog_attach(
             bpf_program__fd(const_cast<const bpf_program*>(connect_program_v6)), 0, BPF_CGROUP_INET6_CONNECT, 0);
         REQUIRE(result == 0);
     }
 
-    *return_object = object;
+    *return_object = unique_object.get();
```
Comment (dthaler) [inline tests/connect_redirect/connect_redirect_tests.cpp:326]: won't this close the object when unique_object goes out of scope on return?
Seems like you should need to do unique_object.reset(nullptr) to take ownership?

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 2]
```diff
@@ -536,21 +555,26 @@ connect_redirect_tests_common(_In_ const struct bpf_object* object, bool dual_st
 void
 test_common(ADDRESS_FAMILY family, IPPROTO protocol)
 {
+    bpf_object_ptr unique_object;
+    unique_object.reset(nullptr);
```
Comment (dthaler) [inline tests/connect_redirect/connect_redirect_tests.cpp:559]: See above comments/questions.

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 3]
```diff
@@ -536,21 +555,26 @@ connect_redirect_tests_common(_In_ const struct bpf_object* object, bool dual_st
...
     socket_family_t dual_stack_socket_family = (family == AF_INET) ? socket_family_t::Dual : socket_family_t::IPv6;
 
-    connect_redirect_tests_common(object, false, _globals.addresses[socket_family]);
-    connect_redirect_tests_common(object, true, _globals.addresses[dual_stack_socket_family]);
+    connect_redirect_tests_common(unique_object.get(), false, _globals.addresses[socket_family]);
+    connect_redirect_tests_common(unique_object.get(), true, _globals.addresses[dual_stack_socket_family]);
 
     // This should also detach the programs as they are not pinned.
-    bpf_object__close(object);
+    bpf_object__close(unique_object.release());
```
Comment (dthaler) [inline tests/connect_redirect/connect_redirect_tests.cpp:577]: If you just delete line 577, it would have the same effect, since the destructor of unique_object would do this, right?

File: tests/socket/socket_tests.cpp [hunk 4]
```diff
@@ -25,25 +25,44 @@
...
 connection_test(
     ADDRESS_FAMILY address_family,
     _Inout_ client_socket_t& sender_socket,
     _Inout_ receiver_socket_t& receiver_socket,
     uint32_t protocol)
 {
-    struct bpf_object* object = bpf_object__open("cgroup_sock_addr.o");
-    REQUIRE(object != nullptr);
+    bpf_object_ptr unique_object;
+    unique_object.reset(nullptr);
```
Comment (dthaler) [inline tests/socket/socket_tests.cpp:49]: See earlier comments

File: tests/socket/socket_tests.cpp [hunk 5]
```diff
@@ -239,7 +263,7 @@ TEST_CASE("attach_sock_addr_programs", "[sock_addr_tests]")
         0);
     REQUIRE(result == 0);
 
-    bpf_object__close(object);
+    bpf_object__close(unique_object.release());
```
Comment (dthaler) [inline tests/socket/socket_tests.cpp:266]: Again I think you can delete this line

File: tests/socket/socket_tests.cpp [hunk 6]
```diff
@@ -360,7 +389,7 @@ connection_monitor_test(
     // Unsubscribe.
     raw_context->unsubscribe();
 
-    bpf_object__close(object);
+    bpf_object__close(unique_object.release());
```
Comment (dthaler) [inline tests/socket/socket_tests.cpp:392]: See above comments

File: tests/connect_redirect/connect_redirect_tests.cpp (hunk 3 above)
Comment (delaramamiri) [reply tests/connect_redirect/connect_redirect_tests.cpp:577]: I am using the same flow as [PR # 2159 ](https://github.com/microsoft/ebpf-for-windows/pull/2192/files), where the unique_ptr is released at the time of closing. IF we checkout line 538 of [tests/end_to_end/end_to_end.cpp](https://github.com/microsoft/ebpf-for-windows/pull/2192/files#diff-f9ee921992a589d5643886350a4641e33e7902b7643a4983110219db80e660ee), it would work with removing bpf_object__close(unique_object.release()); but that PR still kept it for consistency.

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 7]
```diff
@@ -278,15 +292,20 @@ _validate_audit_map_entry(_In_ const struct bpf_object* object, uint64_t authent
 static void
 _load_and_attach_ebpf_programs(_Outptr_ struct bpf_object** return_object)
 {
+    bpf_object_ptr unique_object;
+    unique_object.reset(nullptr);
```
[the remark this answers is not in the document]
Comment (delaramamiri) [reply tests/connect_redirect/connect_redirect_tests.cpp:296]: Similar to release() comment, unique_object.reset(nullptr); was used in PR #2159 before taking ownership of the object created.

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 8]
```diff
@@ -278,15 +279,20 @@ _validate_audit_map_entry(_In_ const struct bpf_object* object, uint64_t authent
 static void
 _load_and_attach_ebpf_programs(_Outptr_ struct bpf_object** return_object)
 {
+    bpf_object_ptr unique_object;
```
Comment (shankarseal) [inline tests/connect_redirect/connect_redirect_tests.cpp:282]: suggest keep the name of the variable simply as `object`. For the raw pointer you may name it `raw_object`.

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 9]
```diff
@@ -482,84 +489,216 @@ connect_redirect_test_wrapper(
...
-    // Local non-loopback address.
-    printf("CONNECT: Local | %s | %s | %s\n", protocol_string, family_string, dual_stack_string);
-    authorize_test_wrapper(object, dual_stack, addresses.local_address);
-
-    // Second category is connection redirection tests.
-
-    // Remote -> Remote
-    printf("REDIRECT: Remote -> Remote | %s | %s | %s\n", protocol_string, family_string, dual_stack_string);
-    connect_redirect_test_wrapper(object, addresses.vip_address, addresses.remote_address, dual_stack);
+#define DECLARE_CONNECTION_AUTHORIZATION_TEST_FUNCTION(destination)                                              \
```
Comment (shankarseal) [inline tests/connect_redirect/connect_redirect_tests.cpp:492]: This diff should not be in this PR. You may want to rebase your topic branch.

File: tests/connect_redirect/connect_redirect_tests.cpp (hunk 8 above)
Comment (delaramamiri) [reply tests/connect_redirect/connect_redirect_tests.cpp]: Done

File: tests/socket/socket_tests.cpp (hunk 5 above)
Comment (delaramamiri) [reply tests/socket/socket_tests.cpp]: removed

File: tests/connect_redirect/connect_redirect_tests.cpp (hunk 9 above)
Comment (delaramamiri) [reply tests/connect_redirect/connect_redirect_tests.cpp]: updated

File: tests/connect_redirect/connect_redirect_tests.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (delaramamiri) [reply tests/connect_redirect/connect_redirect_tests.cpp]: updated

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 10]
```diff
@@ -297,15 +302,16 @@ _load_and_attach_ebpf_programs(_Outptr_ struct bpf_object** return_object)
...
         REQUIRE(connect_program_v6 != nullptr);
 
         result = bpf_prog_attach(
             bpf_program__fd(const_cast<const bpf_program*>(connect_program_v6)), 0, BPF_CGROUP_INET6_CONNECT, 0);
         REQUIRE(result == 0);
     }
 
-    *return_object = object;
+    //unique_object.reset(nullptr);
+    *return_object = object.get();
```
Comment (dthaler) [inline tests/connect_redirect/connect_redirect_tests.cpp:314]: Should not have commented out code.  I think this should be:
```suggestion
    *return_object = object.get();
    object.reset(nullptr);
```

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 11]
```diff
@@ -279,15 +279,20 @@ _validate_audit_map_entry(_In_ const struct bpf_object* object, uint64_t authent
...
 {
+    bpf_object_ptr object;
+
     int result;
-    struct bpf_object* object = bpf_object__open("cgroup_sock_addr2.o");
-    REQUIRE(object != nullptr);
+    struct bpf_object* raw_object = bpf_object__open("cgroup_sock_addr2.o");
+    REQUIRE(raw_object != nullptr);
+
+    REQUIRE(bpf_object__load(raw_object) == 0);
```
Comment (Alan-Jowett) [inline tests/connect_redirect/connect_redirect_tests.cpp:288]: Won't this still leak if the bpf_object__load fails?

**Review by dthaler — APPROVED** [review]

**Review by shpalani — DISMISSED** [review]

**Comment by dthaler** [comment]
@delaramamiri rebase to pick up scorecards fix

**Review by dthaler — APPROVED** [review]

**Review by shpalani — APPROVED** [review]
