### PR TITLE
Misc. code clean-up fixes, add some critical traces.

### LINKED ISSUE #2583: netebpfext code clean-up
### Describe the bug

Fix miscellaneous clean-up issues:
- Use of potentially invalid handle in `NmrDeregisterProvider`
- null pointer checks on attach/detach (resolution TBD: log and return error or fastfail?)
- other clean-up items as discovered.

### OS information

_No response_

### Steps taken to reproduce bug

Drive-by code review

### Expected behavior

N/A

### Actual outcome

N/A

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

Issues fixed:
- Check nmr binding handle validity prior to calling NmrDeregisterProvider
- Add some critical traces.

_Note: The `NetEbpfExt` extension can certainly use some more traces.  That task will be addressed in a subsequent PR._

## Testing

CI/CD run.

## Documentation

No doc changes required.

Fixes #2583

### CODE REVIEW

File: netebpfext/net_ebpf_ext_hook_provider.c [hunk 1]
```diff
@@ -433,11 +454,20 @@ net_ebpf_extension_hook_provider_unregister(_Frees_ptr_opt_ net_ebpf_extension_h
 {
     NET_EBPF_EXT_LOG_ENTRY();
     if (provider_context != NULL) {
-        NTSTATUS status = NmrDeregisterProvider(provider_context->nmr_provider_handle);
-        if (status == STATUS_PENDING) {
-            // Wait for clients to detach.
-            NmrWaitForProviderDeregisterComplete(provider_context->nmr_provider_handle);
+#pragma warning(push)
+#pragma warning(disable : 6001)
+        // Analyzer complains about provider_context 'not intialized before use' for the following line.
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext_hook_provider.c:459]: That's because line 453 uses incorrect SAL annotation.  It should also have `_In_` in addition to `_Frees_ptr_opt_`.
Once you add that, you should be able to remove these pragmas.

File: netebpfext/net_ebpf_ext_hook_provider.c [hunk 2]
```diff
@@ -484,6 +513,10 @@ net_ebpf_extension_hook_provider_register(
 
     status = NmrRegisterProvider(characteristics, local_provider_context, &local_provider_context->nmr_provider_handle);
     if (!NT_SUCCESS(status)) {
+
+        // The docs don't mention the (out) handle status on failure, so explicitly mark it as invalid.
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext_hook_provider.c:517]: Sure they do.
`typedef _Return_type_success_(return >= 0) LONG NTSTATUS;`
means that NTSTATUS is documented via the `_Return_type_success_` annotation as saying that on a failure, any Out fields cannot be assumed to be initialized.  It's ok to initialize them anyway but I don't think it's correct to say the docs don't mention it.

**Review by Alan-Jowett — APPROVED** [review]

File: netebpfext/net_ebpf_ext_prog_info_provider.c [hunk 3]
```diff
@@ -120,10 +123,19 @@ net_ebpf_extension_program_info_provider_unregister(
     _Frees_ptr_opt_ net_ebpf_extension_program_info_provider_t* provider_context)
 {
     if (provider_context != NULL) {
-        NTSTATUS status = NmrDeregisterProvider(provider_context->nmr_provider_handle);
-        if (status == STATUS_PENDING) {
-            NmrWaitForProviderDeregisterComplete(provider_context->nmr_provider_handle);
+#pragma warning(push)
+#pragma warning(disable : 6001)
+        // Analyzer complains about provider_context 'not intialized before use' for the following line.
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext_prog_info_provider.c:128]: As with comment in previous file, please fix line 123 instead.

File: netebpfext/net_ebpf_ext_prog_info_provider.c [hunk 4]
```diff
@@ -161,6 +172,10 @@ net_ebpf_extension_program_info_provider_register(
 
     status = NmrRegisterProvider(characteristics, local_provider_context, &local_provider_context->nmr_provider_handle);
     if (!NT_SUCCESS(status)) {
+
+        // The docs don't mention the (out) handle status on failure, so explicitly mark it as invalid.
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext_prog_info_provider.c:176]: See comment on previous file.

**Review by Alan-Jowett — CHANGES_REQUESTED** [review]
Waiting on the changes Dave suggested

File: netebpfext/net_ebpf_ext_hook_provider.c (hunk 2 above)
Comment (dv-msft) [reply netebpfext/net_ebpf_ext_hook_provider.c:517]: Ah. I was not aware of that.  I was referring to the more 'traditional' doc [source](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netioddk/nf-netioddk-nmrregisterprovider).  It does not mention the SAL enhancements.

Comment (dv-msft) [reply netebpfext/net_ebpf_ext_hook_provider.c:515]: Fixed.

**Review by dthaler — DISMISSED** [review]

**Review by shpalani — COMMENTED** [review]
Suggestion: These traces will be beneficial to add to the TroubleShootingGuide.md

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
