### PR TITLE
socket tests does not clean up bpf_object 

### LINKED ISSUE #2203: socket tests and redirection tests does not clean up bpf_object on failure
The socket and redirect tests allocate bpf object on heap during test variation setup. Since Catch2::REQUIRE throws an exception upon failure, the bpf_object does not get closed. This causes problem for the next variation that will fail to load the eBPF program as it is still loaded. So when one of these tests fail, all subsequent tests fail.

One solution could be to have a `std::unique_ptr` wrapper class around bpf_object used in these tests.

### PR DESCRIPTION
**Pull request by delaramamiri**
## Description

closes #2203 
This PR uses smart pointer to assign `bpf_object` . Since Catch2::REQUIRE throws an exception upon failure, the bpf_object does not get closed. This causes problem for the next variation that will fail to load the eBPF program as it is still loaded. So when one of these tests fail, all subsequent tests fail.

## Testing

Build passes. 
```
 socket_tests.exe 
_native_module_helper::get_file_name: cgroup_sock_addr.o
tuple.dst_ip.ipv4 = 100007f
tuple.dst_port = 1d23
_native_module_helper::get_file_name: cgroup_sock_addr.o
tuple.dst_port = 1d23
_native_module_helper::get_file_name: cgroup_sock_addr.o
tuple.dst_ip.ipv4 = 100007f
tuple.dst_port = 1d23
_native_module_helper::get_file_name: cgroup_sock_addr.o
tuple.dst_port = 1d23
_native_module_helper::get_file_name: cgroup_sock_addr.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
_native_module_helper::get_file_name: sockops.o
===============================================================================
All tests passed (146 assertions in 14 test cases)
```
## Documentation

N/A

### CODE REVIEW

File: tests/socket/socket_tests.cpp [hunk 1]
```diff
@@ -28,6 +28,12 @@ using namespace std::chrono_literals;
 #include <mstcpip.h>
 
 CATCH_REGISTER_LISTENER(_watchdog)
+typedef struct _test_globals
+{
+    bpf_object_ptr bpf_object;
+} test_globals_t;
+
+static test_globals_t _globals;
```
Comment (dthaler) [inline tests/socket/socket_tests.cpp:36]: why a global instead of a bpf_object_ptr that is local for each test case?
I suspect a global would show up as a leak if the usersim library were initialized/terminated for each test case to do leak detection.

Comment (delaramamiri) [reply tests/socket/socket_tests.cpp:31]: Moved `test_globals_t` to the `common_tests.h` header file to be used for multiple tests.

Comment (dthaler) [reply tests/socket/socket_tests.cpp:31]: As a reminder since it's been several days, I am still waiting for my comment to be addressed.   Moving a global to another file (which I don't see in this PR either) does not address my comment about the fact that I don't think it should be a global.

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]

File: tests/connect_redirect/connect_redirect_tests.cpp [hunk 2]
```diff
@@ -671,6 +654,7 @@ DECLARE_CONNECTION_REDIRECTION_V6_TEST_GROUP("dual_ipv6", socket_family_t::IPv6,
 int
 main(int argc, char* argv[])
 {
+    test_globals_t _globals;
```
Comment (saxena-anurag) [inline tests/connect_redirect/connect_redirect_tests.cpp:657]: I think this is incorrect. Instead of using a global variable, this PR is creating a stack variable and initializing it (in line 662). The actual tests will never be able to access this stack variable. All the tests should ideally fail in that case, and it looks like that is happening right now. 

Example failure:
https://github.com/microsoft/ebpf-for-windows/actions/runs/5756053268/job/15605278098

```
2023-08-03T22:39:38.2188711Z ===============================================================================
2023-08-03T22:39:38.2189145Z test cases:  80 |  0 passed | 80 failed
2023-08-03T22:39:38.2189817Z assertions: 101 | 21 passed | 80 failed
```



It looks like the tests are being marked as PASSED even if every test failed due to a different bug (Issue #2707)
