### PR TITLE
ensure native ebpf program's helper function count is non-zero before using it for allocation computations.

### LINKED ISSUE #2384: Kernel mode MT Stress tests - Assert in ebpfcore.sys
### Describe the bug

Running the kernel mode MT stress test `sockaddr_invoke_program_test` causes a kernel mode assert within the first 30 seconds.
This is a 100% repro.

This assert is seen _only_ if the 'extension restart' option is enabled for this test. 

### OS information

_No response_

### Steps taken to reproduce bug

With the kernel debugger attached, run the kernel mode stress test with the following command line:
`.\ebpf_stress_tests_km -tt=32 -td=2 -er=true sockaddr_invoke_program_test`

### Expected behavior

The test should pass without errors.

### Actual outcome

The kernel debugger flags an assert with this callstack:
```
*** Assertion failed: size
***   Source File: D:\wrk\ebpf-for-windows\libs\platform\kernel\ebpf_platform_kernel.c, line 50

Break repeatedly, break Once, Ignore, terminate Process, or terminate Thread (boipt)? O
Execute '.cxr FFFF88877D00DCA0' to dump context
Break instruction exception - code 80000003 (first chance)
nt!RtlAssert+0xee:
fffff806`3ba061fe cc              int     3
0: kd> k
 # Child-SP          RetAddr               Call Site
00 ffff8887`7d00dc50 fffff806`418190ac     nt!RtlAssert+0xee [minkernel\ntos\rtl\assert.c @ 132] 
01 ffff8887`7d00e1b0 fffff806`41812fd9     ebpfcore!ebpf_allocate_with_tag+0x4c [D:\wrk\ebpf-for-windows\libs\platform\kernel\ebpf_platform_kernel.c @ 50] 
02 ffff8887`7d00e1f0 fffff806`41812861     ebpfcore!_ebpf_program_update_helpers+0x49 [D:\wrk\ebpf-for-windows\libs\execution_context\ebpf_program.c @ 711] 
03 ffff8887`7d00e240 fffff806`4181d53c     ebpfcore!_ebpf_program_program_info_provider_changed+0x6d1 [D:\wrk\ebpf-for-windows\libs\execution_context\ebpf_program.c @ 207] 
04 ffff8887`7d00e570 fffff806`4181cbb7     ebpfcore!_ebpf_extension_client_notify_change+0x10c [D:\wrk\ebpf-for-windows\libs\platform\ebpf_extension.c @ 63] 
05 ffff8887`7d00e6a0 fffff806`3ddc616a     ebpfcore!_ebpf_extension_client_attach_provider+0x447 [D:\wrk\ebpf-for-windows\libs\platform\ebpf_extension.c @ 129] 
06 ffff8887`7d00e940 fffff806`3ddc6099     NETIO!NmrpProposeAttachment+0x8a [minio\netio\nmr\binding.c @ 564] 
07 ffff8887`7d00e990 fffff806`3ddc5d61     NETIO!NmrpAttachArray+0x3d [minio\netio\nmr\module.c @ 283] 
08 ffff8887`7d00e9c0 fffff806`3ddc5b80     NETIO!NmrpRegisterModule+0x8d [minio\netio\nmr\module.c @ 378] 
09 ffff8887`7d00ea20 fffff806`418c8091     NETIO!NmrRegisterProvider+0x70 [minio\netio\nmr\module.c @ 697] 
0a ffff8887`7d00ea60 fffff806`418cdb7f     netebpfext!net_ebpf_extension_program_info_provider_register+0x1b1 [D:\wrk\ebpf-for-windows\netebpfext\net_ebpf_ext_prog_info_provider.c @ 160] 
0b ffff8887`7d00eba0 fffff806`418c238d     netebpfext!net_ebpf_ext_sock_addr_register_providers+0x46f [D:\wrk\ebpf-for-windows\netebpfext\net_ebpf_ext_sock_addr.c @ 744] 
0c ffff8887`7d00ee20 fffff806`418d4843     netebpfext!net_ebpf_ext_register_providers+0xed [D:\wrk\ebpf-for-windows\netebpfext\net_ebpf_ext.c @ 734] 
0d ffff8887`7d00ef50 fffff806`418d419c     netebpfext!_net_ebpf_ext_driver_initialize_objects+0x183 [D:\wrk\ebpf-for-windows\netebpfext\sys\net_ebpf_ext_drv.c @ 125] 
0e ffff8887`7d00efe0 fffff806`418d4c1b     netebpfext!DriverEntry+0xec [D:\wrk\ebpf-for-windows\netebpfext\sys\net_ebpf_ext_drv.c @ 152] 
0f ffff8887`7d00f100 fffff806`418d4b50     netebpfext!FxDriverEntryWorker+0xbf [minkernel\wdf\framework\kmdf\src\dynamic\stub\stub.cpp @ 360] 
10 ffff8887`7d00f140 fffff806`3bc33790     netebpfext!FxDriverEntry+0x20 [minkernel\wdf\framework\kmdf\src\dynamic\stub\stub.cpp @ 249] 
11 ffff8887`7d00f170 fffff806`3bc333f9     nt!PnpCallDriverEntry+0x54 [minkernel\ntos\io\pnpmgr\enum.c @ 8804] 
12 ffff8887`7d00f1c0 fffff806`3bc759d3     nt!IopLoadDriver+0x529 [minkernel\ntos\io\iomgr\internal.c @ 5065] 
13 ffff8887`7d00f380 fffff806`3b67bf94     nt!IopLoadUnloadDriver+0x53 [minkernel\ntos\io\iomgr\internal.c @ 5602] 
14 ffff8887`7d00f3c0 fffff806`3b740a37     nt!ExpWorkerThread+0x1e4 [minkernel\ntos\ex\worker.c @ 4308] 
15 ffff8887`7d00f5b0 fffff806`3b8a5284     nt!PspSystemThreadStartup+0x57 [minkernel\ntos\ps\psexec.c @ 11736] 
16 ffff8887`7d00f600 00000000`00000000     nt!KiStartSystemThread+0x34 [minkernel\ntos\ke\amd64\threadbg.asm @ 87] 
```

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

This PR fixes the case where we were always assuming a non-zero count for the helper functions called by a native eBPF program.  It is quite valid for an ebpf program to perform its task(s) _without_ invoking any helper calls at all.

## Testing

1. Added a new kernel mode test multi-threaded test `ebpf_stress_tests_km.exe::sockaddr_invoke_program_test`.  The associated native ebpf program `cgroup_mt_connect6.sys` is an example of a non-trivial eBPF program that does not call any helper functions.
2. Ensured that the following test invocation passed successfully:
```
PS > Date; .\ebpf_stress_tests_km -tt=64 -td=5 -er=true sockaddr_invoke_program_test; Date

Thursday, April 27, 2023 6:25:38 PM
Filters: "sockaddr_invoke_program_test"
Randomness seeded to: 2479346546
test programs:
        cgroup_sock_addr
test threads per program    : 64
test duration (in minutes)  : 5
test verbose output         : false
test extension restart      : true
test extension restart delay: 1000 ms

Starting test *** sockaddr_invoke_program_test ***
waiting on 64 test threads...
**** Extension restart thread done. Exiting. ****
waiting on 1 extension restart threads...
===============================================================================
All tests passed (65 assertions in 1 test case)

Thursday, April 27, 2023 6:30:48 PM
```

## Documentation

Updated `docs\AutomatedTests.md` to mention user-mode and kernel-mode stress tests.

Fixes #2384, #1955

### CODE REVIEW

**Review by Alan-Jowett — DISMISSED** [review]

File: tests/stress/km/stress_tests_km.cpp [hunk 1]
```diff
@@ -693,8 +693,140 @@ _mt_prog_load_stress_test(ebpf_execution_type_t program_type, const test_control
...
+        REQUIRE(result == 0);
+    }
+    LOG_VERBOSE(
+        "{}({}) Attached program:{}, file_name:{}", __func__, thread_index, program->program_name, file_name.c_str());
+
+    object_ptr.reset(object_raw_ptr);
+    return std::make_pair(std::move(object_ptr), program_fd);
+}
+
+#if 1
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:792]: shouldn't use `#if 1`.  Needs cleanup.

File: tests/stress/km/stress_tests_km.cpp [hunk 2]
```diff
@@ -969,6 +1104,132 @@ _mt_invoke_prog_stress_test(ebpf_execution_type_t program_type, const test_contr
...
+                    "Next restart for {} extension after a delay of {} ms",
+                    extension_name,
+                    test_control_info.extension_restart_delay);
+                std::this_thread::sleep_for(std::chrono::milliseconds(test_control_info.extension_restart_delay));
+            }
+            LOG_INFO("**** Extension restart thread done. Exiting. ****");
+        }));
+    }
+
+    // wait for threads to terminate.
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:1219]:
```suggestion
    // Wait for threads to terminate.
```

File: tests/stress/km/stress_tests_km.cpp [hunk 3]
```diff
@@ -1060,3 +1321,29 @@ TEST_CASE("native_invoke_program_restart_extension_v4_test", "[mt_stress_test]")
...
+    // Test layout:
+    // 1. Load the "cgroup_mt_connect4.sys" native ebpf program
+    //    - This program monitors an IPv4 endpoint, 127.0.0.1:<target_port>. On every invocation, the program returns a
+    //      specific value per the following (arbitrary) algorithm:
+    //      > (target_port % 3 == 0) : BPF_SOCK_ADDR_VERDICT_REJECT
+    //        (target_port % 2 == 0) : BPF_SOCK_ADDR_VERDICT_PROCEED
+    //        else                   : BPF_SOCK_ADDR_VERDICT_REDIRECT
+    //
+    // 2. Create the specified # of threads and for the duration of test, each thread will:
+    //    - Attempt a TCP 'connect' to the remote endpoint 127.0.01:<target_port + thread_context.thread_index>
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:1336]:
```suggestion
    //    - Attempt a TCP 'connect' to the remote endpoint 127.0.0.1:<target_port + thread_context.thread_index>
```

File: tests/sample/cgroup_mt_connect4.c [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+    }
+
+    if (!(ntohs(ctx->user_port) % 2)) {
+        retval = BPF_SOCK_ADDR_VERDICT_PROCEED;
+        goto exit;
+    }
+
+    // For all other port values, redirect the port to some arbitrary value.
+    // REDIRECT uses the same return value as PROCEED except it updates the ip
+    // and/or port as reqired. (We only update the port here.)
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/sample/cgroup_mt_connect4.c]: fixed.

File: tests/stress/km/stress_tests_km.cpp [hunk 5]
```diff
@@ -693,8 +693,140 @@ _mt_prog_load_stress_test(ebpf_execution_type_t program_type, const test_control
...
+            "{}({}) FATAL ERROR: bpf_object__load({}) failed. errno:{}",
+            __func__,
+            thread_index,
+            file_name.c_str(),
+            errno);
+        REQUIRE(result == 0);
+    }
+    LOG_VERBOSE("{}({}) loaded file:{}", __func__, thread_index, file_name.c_str());
+
+    // Get program object for (the only) program in this file.
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed.

File: tests/stress/km/stress_tests_km.cpp (hunk 1 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed.

File: tests/sample/cgroup_mt_connect4.c [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+
+#include "bpf_endian.h"
+#include "bpf_helpers.h"
+#include "net/ip.h"
+#include "socket_tests_common.h"
+
+const uint16_t remote_port = SOCKET_TEST_PORT;
+const uint16_t redirect_offset = 1000;
+
+SEC("cgroup/connect4")
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/sample/cgroup_mt_connect4.c:22]: IPv6 works just fine.  It's just that we have an existing issue where we cannot have an IPv4 (CGROUP/CONNECT4) _and_ an IPv6 (CGROUPT/CONNECT6) program attached at the same time (Issue #2351).  This would have worked equally well with IPv6. I just _happened_ to pick IPv4 here.

File: tests/stress/km/stress_tests_km.cpp (hunk 2 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:1096]: fixed.

File: tests/stress/km/stress_tests_km.cpp (hunk 3 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed.

File: tests/stress/km/stress_tests_km.cpp [hunk 7]
```diff
@@ -1060,3 +1321,29 @@ TEST_CASE("native_invoke_program_restart_extension_v4_test", "[mt_stress_test]")
     local_test_control_info.extension_restart_enabled = true;
     _mt_invoke_prog_stress_test(EBPF_EXECUTION_NATIVE, local_test_control_info);
 }
+
+TEST_CASE("sockaddr_invoke_program_test", "[mt_stress_test]")
+{
+    // Test layout:
+    // 1. Load the "cgroup_mt_connect4.sys" native ebpf program
+    //    - This program monitors an IPv4 endpoint, 127.0.0.1:<target_port>. On every invocation, the program returns a
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:1206]: As mentioned in a previous response, IPv6 works fine.

File: tests/stress/km/stress_tests_km.cpp [hunk 8]
```diff
@@ -693,8 +693,140 @@ _mt_prog_load_stress_test(ebpf_execution_type_t program_type, const test_control
...
+    // Stash the object pointer as well need it at 'close' time.
+    auto [program_object, program_fd] = _load_attach_program(context.file_name, context.thread_index);
+    auto& entry = context.object_table[context.thread_index];
+    entry.object = std::move(program_object);
+    context.program_fd = program_fd;
+
+    if (map_usage == program_map_usage::USE_MAP) {
+
+        // Get the map fd for the map for this program.
+        // auto map_fd = bpf_object__find_map_fd_by_name(object_raw_ptr, context.map_name.c_str());
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed

File: tests/stress/km/stress_tests_km.cpp [hunk 9]
```diff
@@ -969,6 +1104,132 @@ _mt_invoke_prog_stress_test(ebpf_execution_type_t program_type, const test_contr
...
+
+    using sc = std::chrono::steady_clock;
+    auto endtime = sc::now() + std::chrono::minutes(context.duration);
+    while (sc::now() < endtime) {
+
+        // Now send out a small burst of TCP 'connect' attempts for the duration of the test.  We do this to increase
+        // the probability of a collision between the program invocation and the extension being restarted at the same
+        // time.
+        // Note: The burst size needs to be small as larger bursts seem to cause inordinately large delays in returning
+        // from the connect call (for the PROCEED and REDIRECT cases).
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:1010]: This is really on the TCP side.  In our specific use case, there's nobody listening so (per Shankar) apparently the corresponding ICMP error response packet is dropped by the tcp stack and thus connect _can_ get blocked for a bit.   If the 'burst' is small enough, the delays are small enough that our test durations are not affected.

File: tests/stress/km/stress_tests_km.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:1206]: BTW, I _can_ make the test IPv6, but do we support 'IPv4 only' machine configurations as well? As of now, we need to pick one or the other but not both.

[the remark this answers is not in the document]
Comment (dthaler) [reply tests/stress/km/stress_tests_km.cpp:1206]: No, we don't.  You can remove it from an interface, but not the loopback.

[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:1206]: I was referring to the CGROUP/CONNECT4, CGROUP/CONNECT6 issue #2351 that is (currently) necessitating this choice.

[the remark this answers is not in the document]
Comment (dthaler) [reply tests/stress/km/stress_tests_km.cpp:1206]: And I was commenting on why picking IPv6 is better than picking IPv4 for this test.

File: tests/sample/cgroup_mt_connect4.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/sample/cgroup_mt_connect4.c:22]: Added IPv6 sample program and test updated to use new program.

File: tests/stress/km/stress_tests_km.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp:1206]: While I've updated the test to use an IPv6 program, I'm genuinely confused/curious as why an IPv6 test program was preferrable for _this_ specific test, especially when the fix being tested _seems_ (at least to my noob eyes) orthogonal to the stream family.  I'm clearly missing something of import here, so I'll follow up offline.

**Review by Alan-Jowett — APPROVED** [review]

File: tests/sample/cgroup_mt_connect6.c [hunk 10]
```diff
@@ -0,0 +1,59 @@
...
+#include "bpf_helpers.h"
+#include "net/ip.h"
+#include "socket_tests_common.h"
+
+const uint16_t remote_port = SOCKET_TEST_PORT;
+const uint16_t redirect_offset = 1000;
+
+SEC("cgroup/connect6")
+int
+tcp_mt_connect6(bpf_sock_addr_t* ctx)
```
Comment (saxena-anurag) [inline tests/sample/cgroup_mt_connect6.c:24]: nit: maybe have both the v4 and v6 ebpf programs in a single file, and then use a common function for both the programs, as most of the below code is same for v4 and v6.

File: tests/stress/km/stress_tests_km.cpp [hunk 11]
```diff
@@ -693,127 +693,140 @@ _mt_prog_load_stress_test(ebpf_execution_type_t program_type, const test_control
...
     }
     LOG_VERBOSE(
-        "{}({}) Attached program:{}, file_name:{}",
-        __func__,
-        context.thread_index,
-        program->program_name,
-        context.file_name.c_str());
+        "{}({}) Attached program:{}, file_name:{}", __func__, thread_index, program->program_name, file_name.c_str());
+
+    object_ptr.reset(object_raw_ptr);
```
Comment (saxena-anurag) [inline tests/stress/km/stress_tests_km.cpp:788]: Should this be done at `line 732` as that will ensure the fd's are closed in case of any failure in this function?

File: tests/sample/cgroup_mt_connect6.c (hunk 10 above)
Comment (dv-msft) [reply tests/sample/cgroup_mt_connect6.c:24]: This was a deliberate decision.  The original idea was to be able to load 2 different programs (.sys) files just to make sure that there aren't (and a future regression does not cause) any issues loading multiple .sys files, each doing its own thing.   IMO, the fact that both happen to do the same work should be treated as a coincidence.

Granted, we can't do that right now due to the IPv4/IPv6 issue (#2351), but once we fix that, I was planning on enhancing this test to load an IPv4 and and IPv6 program (with some tweaks suggested by Dave and Alan).

File: tests/stress/km/stress_tests_km.cpp (hunk 2 above)
Comment (dthaler) [reply tests/stress/km/stress_tests_km.cpp:1096]: Doesn't look fixed but approving anyway.

File: tests/stress/km/stress_tests_km.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (dthaler) [reply tests/stress/km/stress_tests_km.cpp:1206]: line 1047 does use IPv6, lines 1210-1213 say it uses IPv4.  Shouldn't the comments match?

File: tests/stress/km/stress_tests_km.cpp (hunk 2 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: Fixed.

File: tests/stress/km/stress_tests_km.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed comments.

File: tests/stress/km/stress_tests_km.cpp (hunk 11 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed.

File: libs/execution_context/ebpf_program.c [hunk 12]
```diff
@@ -708,11 +708,19 @@ _Requires_lock_held_(program->lock) static ebpf_result_t _ebpf_program_update_he
...
     uintptr_t* helper_function_addresses = NULL;
     if (program->parameters.code_type == EBPF_CODE_NATIVE) {
-        helper_function_addresses =
-            ebpf_allocate_with_tag(program->helper_function_count * sizeof(uintptr_t), EBPF_POOL_TAG_PROGRAM);
-        if (helper_function_addresses == NULL) {
-            result = EBPF_NO_MEMORY;
-            goto Done;
+
+        // We _can_ have instances of ebpf programs that do not need to call any helper functions.
+        // The `tests\sample\cgroup_mt_connect4.c` sample/test program is one such non-trivial program that does not
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply libs/execution_context/ebpf_program.c]: fixed.

**Review by saxena-anurag — APPROVED** [review]

File: tests/stress/km/stress_tests_km.cpp [hunk 13]
```diff
@@ -1060,3 +1198,29 @@ TEST_CASE("native_invoke_program_restart_extension_v4_test", "[mt_stress_test]")
     local_test_control_info.extension_restart_enabled = true;
     _mt_invoke_prog_stress_test(EBPF_EXECUTION_NATIVE, local_test_control_info);
 }
+
+TEST_CASE("sockaddr_invoke_program_test", "[mt_stress_test]")
+{
+    // Test layout:
+    // 1. Load the "cgroup_mt_connect6.sys" native ebpf program.
+    //    - This program monitors an IPv6 endpoint, ::1:<target_port>. On every invocation, the program returns a
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:1206]:
```suggestion
    //    - This program monitors an IPv6 endpoint, [::1]:<target_port>. On every invocation, the program returns a
```

Comment (dthaler) [reply tests/stress/km/stress_tests_km.cpp:1206]: when using `<address>:<port>` syntax, IPv6 uses `[]` around the address

File: tests/stress/km/stress_tests_km.cpp [hunk 14]
```diff
@@ -1060,3 +1198,29 @@ TEST_CASE("native_invoke_program_restart_extension_v4_test", "[mt_stress_test]")
...
+    //      specific value per the following (arbitrary) algorithm:
+    //      > (target_port % 3 == 0) : BPF_SOCK_ADDR_VERDICT_REJECT
+    //        (target_port % 2 == 0) : BPF_SOCK_ADDR_VERDICT_PROCEED
+    //        else                   : BPF_SOCK_ADDR_VERDICT_REDIRECT
+    //
+    // 2. Create the specified # of threads and for the duration of test, each thread will:
+    //    - Attempt a TCP 'connect' to the remote endpoint ::1:<target_port + thread_context.thread_index>
```
Comment (dthaler) [inline tests/stress/km/stress_tests_km.cpp:1213]:
```suggestion
    //    - Attempt a TCP 'connect' to the remote endpoint [::1]:<target_port + thread_context.thread_index>
```

File: tests/stress/km/stress_tests_km.cpp (hunk 13 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: ah. ofc that makes sense.  fixed.

File: tests/stress/km/stress_tests_km.cpp (hunk 14 above)
Comment (dv-msft) [reply tests/stress/km/stress_tests_km.cpp]: fixed

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
