### PR TITLE
Replace ring_buffer and perf_buffer new with windows-specific versions

### LINKED ISSUE #4142: Use synchronous ring buffer and perf event array callbacks by default
### Describe the bug

The current behavior on Windows is to only support asynchronous callbacks for ring buffer and perf event array maps. The callback will be automatically invoked when data is available.

On Linux there are no asynchronous callbacks for ring buffers or perf event array and the callback is only called inside calls to `poll` and `consume`.

We should update the default `new` behavior to use synchronous callbacks and add support for flags to specify that automatic callbacks (the current behavior) should be invoked.

This will be a significant *breaking change* to the ring buffer and perf event array behavior, so should be put off until other API breaking changes are made. This also depends on #3848 and #4163 to have memory mapped consumer support.

### OS information

_No response_

### Steps taken to reproduce bug

1. Call `ring_buffer__new` (or `perf_buffer__new`).
2. Write events into map.
3. Callback will be automatically invoked after records are written.

### Expected behavior

Expected behaviour on linux is that callback is not called outside of calls to `poll` and `consume`. This should eventually become the Windows default to resolve this incompatibility.

### Actual outcome

On Windows there are only asynchronous callbacks right now, so the callback could be invoked as soon as it is attached.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by mikeagun**
## Description

Aligns default `ring_buffer__new` and `perf_buffer__new` behavior with Linux and adds new Windows constructor.
- Adds `ebpf_ring_buffer__new` which takes `ebpf_ring_buffer_opts` with flags for callback behavior.
  - Returns NOT_SUPPORTED if async events are not enabled currently.
  - `ring_buffer__new` updated to call `ebpf_ring_buffer__new` with default flags (synchronous behavior).
- Adds `ebpf_perf_buffer__new` which takes `ebpf_perf_buffer_opts` with flags for callback behavior.
  - Returns NOT_SUPPORTED if async events are not enabled currently.
  - `perf_buffer__new` updated to call `ebpf_perf_buffer__new` with default flags (synchronous behavior).
- Synchronous libbpf callbacks are _not_ implemented in this PR.
  - Only updates the default behavior and returns not implemented if automatic callbacks are not explicitly enabled.

NOTE: This is a breaking change. Callers expecting asynchronous callbacks should switch to `ebpf_ring_buffer__new`/`ebpf_perf_buffer__new` and pass opts with the `EBPF_..._FLAG_AUTO_CALLBACK` flag set.
- synchronous callback support will be implemented in follow-up work.

Closes #4142 

## Testing

_Do any existing tests cover this change? Are new tests needed?_

## Documentation

_Is there any documentation impact for this change?_

## Installation

_Is there any installer impact for this change?_

### CODE REVIEW

File: libs/api/libbpf_map.cpp [hunk 1]
```diff
@@ -359,10 +359,42 @@ bpf_map_get_next_id(uint32_t start_id, uint32_t* next_id)
 typedef struct ring_buffer
 {
     std::vector<ebpf_map_subscription_t*> subscriptions;
+
+    bool is_async_mode = false; // True for async callbacks, false for sync processing.
 } ring_buffer_t;
 
+// Helper function to convert ring_buffer_opts to ebpf_ring_buffer_opts.
+static inline struct ebpf_ring_buffer_opts
+_convert_to_ebpf_opts(const struct ring_buffer_opts* linux_opts)
```
Comment (dthaler) [inline libs/api/libbpf_map.cpp]:
```suggestion
_convert_to_ebpf_opts(_In_ const struct ring_buffer_opts* linux_opts)
```

File: libs/api/libbpf_map.cpp [hunk 2]
```diff
@@ -359,10 +359,42 @@ bpf_map_get_next_id(uint32_t start_id, uint32_t* next_id)
...
+{
+    // Linux ring buffer opts are currently empty (only sz field), so we use defaults (synchronous mode).
+    ebpf_ring_buffer_opts ebpf_opts{.sz = sizeof(ebpf_opts), .flags = 0};
+    UNREFERENCED_PARAMETER(linux_opts);
+    return ebpf_opts;
+}
+
+// Helper function to convert perf_buffer_opts to ebpf_perf_buffer_opts.
+static inline struct ebpf_perf_buffer_opts
+_convert_to_ebpf_perf_opts(const struct perf_buffer_opts* linux_opts)
```
Comment (dthaler) [inline libs/api/libbpf_map.cpp]:
```suggestion
_convert_to_ebpf_perf_opts(_In_ const struct perf_buffer_opts* linux_opts)
```

File: libs/api/libbpf_map.cpp [hunk 3]
```diff
@@ -374,20 +406,32 @@ ring_buffer__new(int map_fd, ring_buffer_sample_fn sample_cb, void* ctx, const s
 
     try {
         std::unique_ptr<ring_buffer_t> ring_buffer = std::make_unique<ring_buffer_t>();
-        ebpf_map_subscription_t* subscription = nullptr;
-        uint32_t cpu_id = 0;
 
-        result = ebpf_map_subscribe(map_fd, &cpu_id, 1, ctx, (void*)sample_cb, nullptr, &subscription);
+        // Determine callback type based on flags
```
Comment (dthaler) [inline libs/api/libbpf_map.cpp]:
```suggestion
        // Determine callback type based on flags.
```

File: libs/api/libbpf_map.cpp [hunk 4]
```diff
@@ -374,20 +406,32 @@ ring_buffer__new(int map_fd, ring_buffer_sample_fn sample_cb, void* ctx, const s
...
-        }
+        ring_buffer->is_async_mode = use_async_callbacks;
 
-        try {
-            ring_buffer->subscriptions.push_back(subscription);
-        } catch (const std::bad_alloc&) {
-            ebpf_map_unsubscribe(subscription);
-            result = EBPF_NO_MEMORY;
+        if (use_async_callbacks) {
+            // Use the existing async callback mechanism
```
Comment (dthaler) [inline libs/api/libbpf_map.cpp]:
```suggestion
            // Use the existing async callback mechanism.
```
nit: Use consistent comment style.

File: libs/api/libbpf_map.cpp [hunk 5]
```diff
@@ -438,6 +482,20 @@ perf_buffer__new(
     perf_buffer_lost_fn lost_cb,
     void* ctx,
     const struct perf_buffer_opts* opts)
+{
+    // Convert Linux opts to Windows opts with default synchronous behavior
```
Comment (dthaler) [inline libs/api/libbpf_map.cpp]:
```suggestion
    // Convert Linux opts to Windows opts with default synchronous behavior.
```
