### PR TITLE
Resolve NetEbpfExt service stop failure with workaround

### LINKED ISSUE #4186: Workflow failed - driver_ws2019
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/13195735600)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/29d9935ebb087bdb71c02ddf3023541d551f439d)
Test name - `driver_ws2019`

### PR DESCRIPTION
**Pull request by matthewige**
## Description
Our driver and stress tests are hitting issues with NetEbpfExt service stop hanging. After debugging, it has become apparent that when the WFP filter/callout is in use at the same time of filter deletion, it can sometimes cause a race condition which results in our driver never receiving the WFP delete notify callback.

This change works around that issue by updating the driver unload logic to additionally clean up any 'leaked' filter references it holds, allowing for cleanup and unload of the driver.

Note that doing premature cleanup of the filter_context objects can put us at risk of a bugcheck, if WFP is still using the object. Our cleanup is done after we have unregistered and deleted the callback, which reduces the risk of this occurring.

Changes:
- Adds a net_ebpf_extension_wfp_cleanup_state_t global structure to hold cleanup related state.
- Added retry logic in net_ebpf_extension_uninitialize_wfp_components for the WFP object cleanup operations. This is to reduce the risk of the initial deletion callback failing because the object is in use, which would put us at risk of prematurely doing our cleanup.
- When WFP filters are deleted, they are moved into the net_ebpf_extension_wfp_cleanup_state_t filter_cleanup_list. They are removed from this list once the last reference is removed.
- In net_ebpf_extension_uninitialize_wfp_components, new logic is added to wait 10 seconds for additional WFP filter delete callbacks. If they are not received, we proceed with iterating through the filter_cleanup_list to release any 'leaked' references from our missing WFP callbacks. 
- Moves provider cleanup rundown wait and provider rundown free into net_ebpf_extension_uninitialize_wfp_components, after the leaked reference cleanup.
- Added additional check in net_ebpf_ext_sock_addr, where one case for the deletion in progress check was missing.

Closes #4186 #4185 #4182 #4181 #3567 #4199

## Testing
- Minor refactoring of the SAFE_ACQUIRE handler
- Updated the netebpf_ext_helper test module logic by reordering initialization and cleanup steps to properly match what the driver is doing.
- Re-enabled the service stop in our tests

## Documentation
n/a

## Installation
n/a

### CODE REVIEW

File: netebpfext/net_ebpf_ext.c [hunk 1]
```diff
@@ -757,37 +771,73 @@ net_ebpf_extension_uninitialize_wfp_components(void)
 {
     size_t index;
     NTSTATUS status;
+    int max_retries = 10;
+    LARGE_INTEGER timeout = {0};
+    timeout.QuadPart = -100000000; // 10 seconds.
```
Comment (mtfriesen) [inline netebpfext/net_ebpf_ext.c:776]: Windows has macros such as `XMSTO100NS(_millis)`  to make it easier to read and write these values, and also make the units explicit. Eight zeros does seem correct for 10 seconds in 100-ns.

File: netebpfext/net_ebpf_ext.c [hunk 2]
```diff
@@ -806,6 +856,80 @@ net_ebpf_extension_uninitialize_wfp_components(void)
...
+            ExReleaseSpinLockExclusive(&_net_ebpf_ext_wfp_cleanup_state.lock, old_irql);
+
+            // Anything left in the NET_EBPF_EXT_WFP_FILTER_DELETING is considered leaked. Remove the references
+            // to allow for cleanup.
+            for (index = 0; index < filter_context->filter_ids_count; index++) {
+                net_ebpf_ext_wfp_filter_id_t* filter_id = &filter_context->filter_ids[index];
+                if (filter_id->state == NET_EBPF_EXT_WFP_FILTER_DELETING) {
+                    leaked_filter_count++;
+                    NET_EBPF_EXT_LOG_MESSAGE_UINT64(
+                        NET_EBPF_EXT_TRACELOG_LEVEL_VERBOSE,
```
Comment (mtfriesen) [inline netebpfext/net_ebpf_ext.c:897]: Should this be an error or warning level? Right now, it's considered unlikely for WFP to call back beyond 10 seconds, but the timing may change.

File: netebpfext/net_ebpf_ext.c [hunk 3]
```diff
@@ -998,4 +1127,37 @@ net_ebpf_ext_remove_client_context(
...
+    ExReleaseSpinLockExclusive(&_net_ebpf_ext_wfp_cleanup_state.lock, old_irql);
+}
+
+void
+net_ebpf_ext_remove_filter_context_from_cleanup_list(_Inout_ net_ebpf_extension_wfp_filter_context_t* filter_context)
+{
+    if (filter_context->in_cleanup_list) {
+        KIRQL old_irql = ExAcquireSpinLockExclusive(&_net_ebpf_ext_wfp_cleanup_state.lock);
+        RemoveEntryList(&filter_context->link);
+        filter_context->in_cleanup_list = FALSE;
```
Comment (mtfriesen) [inline netebpfext/net_ebpf_ext.c:1156]: Just an idea, but you maybe be able to eliminate this `in_cleanup_list` variable and avoid dangling pointers to the `filter_cleanup_list` by re-initializing the `link` to an empty list, and treating the empty list as a sentinel value.

(`RemoveEntryList` doesn't modify the provided list entry's pointer fields, only the pointers in the rest of the list.)

**Review by mtfriesen — APPROVED** [review]

File: netebpfext/net_ebpf_ext.c [hunk 4]
```diff
@@ -806,6 +856,80 @@ net_ebpf_extension_uninitialize_wfp_components(void)
...
+#pragma warning(pop)
+    }
+
+    // Iterate through the provider list and handle cleanup.
+    while (!IsListEmpty(&_net_ebpf_ext_wfp_cleanup_state.provider_context_cleanup_list)) {
+        PLIST_ENTRY entry = RemoveHeadList(&_net_ebpf_ext_wfp_cleanup_state.provider_context_cleanup_list);
+        net_ebpf_extension_hook_provider_t* provider_context =
+            CONTAINING_RECORD(entry, net_ebpf_extension_hook_provider_t, cleanup_list_entry);
+
+        // Release the lock as waiting for rundown can take time.
```
Comment (mtfriesen) [inline netebpfext/net_ebpf_ext.c:921]: Technically the wait also requires IRQL < dispatch, so the lock needs to be dropped even if the wait will be quick.

File: netebpfext/net_ebpf_ext.c [hunk 5]
```diff
@@ -23,6 +23,7 @@
 #include "net_ebpf_ext_sock_ops.h"
 #include "net_ebpf_ext_xdp.h"
 
+#define XMSTO100NS(x) ((x)*10000)
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext.c:26]:
```suggestion
#define MSTO100NS(x) ((x)*10000)
```
Recommend removing X which doesn't mean anything in the define name.

File: netebpfext/net_ebpf_ext.c [hunk 6]
```diff
@@ -48,6 +49,10 @@ static net_ebpf_ext_sublayer_info_t _net_ebpf_ext_sublayers[] = {
      0,
      SUBLAYER_WEIGHT_MAXIMUM}};
 
+// Global objects used to store filter contexts that are being cleaned up. This is currently only used in debug
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext.c:52]: Recommend splitting line after period.

File: netebpfext/net_ebpf_ext.c [hunk 7]
```diff
@@ -397,20 +404,24 @@ net_ebpf_extension_delete_wfp_filters(
...
+        filter_ids[index].state = NET_EBPF_EXT_WFP_FILTER_DELETING;
         status = FwpmFilterDeleteById(wfp_engine_handle, filter_ids[index].id);
+        filter_ids[index].error_code = status;
         if (!NT_SUCCESS(status)) {
-            NET_EBPF_EXT_LOG_NTSTATUS_API_FAILURE(
-                NET_EBPF_EXT_TRACELOG_KEYWORD_EXTENSION, "FwpmFilterDeleteById", status);
+            NET_EBPF_EXT_LOG_MESSAGE_UINT64_UINT64(
+                NET_EBPF_EXT_TRACELOG_LEVEL_ERROR,
+                NET_EBPF_EXT_TRACELOG_KEYWORD_EXTENSION,
+                "FwpmFilterDeleteById Failed to marked WFP filter for deletion.",
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext.c:414]:
```suggestion
                "FwpmFilterDeleteById failed to mark WFP filter for deletion.",
```
grammar nit

File: netebpfext/net_ebpf_ext.c [hunk 8]
```diff
@@ -757,37 +772,73 @@ net_ebpf_extension_uninitialize_wfp_components(void)
 {
     size_t index;
     NTSTATUS status;
+    int max_retries = 10;
+    LARGE_INTEGER timeout = {0};
+    timeout.QuadPart = -XMSTO100NS(10000); // 10 seconds
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext.c:777]: Since `XMSTO100NS` is only used here, the "MS" units doesn't seem interesting.
Maybe `SECONDSTO100NS(10)`?

File: netebpfext/net_ebpf_ext.c [hunk 9]
```diff
@@ -757,37 +772,73 @@ net_ebpf_extension_uninitialize_wfp_components(void)
...
+
+    NET_EBPF_EXT_LOG_ENTRY();
 
     if (_fwp_engine_handle != NULL) {
+        // WFP operations may fail if connections are in the middle of being classified and our WFP filters or callouts
+        // are in use. Prior to this function execution, it is expected that the WFP filter objects were removed,
+        // reducing the risk of this failure to occur. However, the following cleanup functions have retry logic built
+        // in to help ensure that the WFP objects are cleaned up properly.
+
         // Clean up the callouts
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext.c:787]:
```suggestion
        // Clean up the callouts.
```
If you update this file anyway, might as well fix a nit here.
Ok if you don't though.

**Review by dthaler — COMMENTED** [review]
Looks ok other than some nits.

File: netebpfext/net_ebpf_ext.c [hunk 10]
```diff
@@ -757,37 +771,73 @@ net_ebpf_extension_uninitialize_wfp_components(void)
 {
     size_t index;
     NTSTATUS status;
+    int max_retries = 10;
```
Comment (dthaler) [inline netebpfext/net_ebpf_ext.c:774]: is max_retries intended to be a constant?  If so, use either `const int max_retries` or a `#define` instead of a mutable variable.

**Review by mikeagun — APPROVED** [review]

**Review by dthaler — APPROVED** [review]
