### PR TITLE
XDP: complete TX clones upon injection failure

### LINKED ISSUE #2012: system bugchecks after unloading XDP program
### Describe the bug

We hit a 0x7c bugcheck after unloading `reflect_packet` due to leaking NBLs from the WFP callout.

### OS information

N/A.

### Steps taken to reproduce bug

1. Install XDPMP, or any NIC with high RX/sec.
2. Attach `reflect_packet` to the XDP layer.
3. Delete the program from the XDP layer.
4. Wait a few minutes for the system to bugcheck due to the stuck NBLs.

### Expected behavior

The XDP program can be deleted in a timely fashion without bugchecks.

### Actual outcome

The network adapter hangs and then bugchecks.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by mtfriesen**
## Description

The XDP hook leaks clone NBLs along with the original NBL when WFP fails to inject the clone. This fix invokes the completion routine manually in the error case.
Resolves #2012 

## Testing

Tested locally. Automation requires stress coverage, e.g., #1933.

## Documentation

N/A.

### CODE REVIEW

**Comment by dthaler** [comment]
> ## Testing
> Locally.

Please add a test case to the unit tests

**Comment by mtfriesen** [comment]
> Please add a test case to the unit tests

I've updated the description to indicate this can only be hit under stress/fuzz conditions and referenced the outstanding issue tracking that lack of coverage.

**Review by Alan-Jowett — APPROVED** [review]

**Comment by dthaler** [comment]
> > Please add a test case to the unit tests
> 
> I've updated the description to indicate this can only be hit under stress/fuzz conditions and referenced the outstanding issue tracking that general lack of coverage.

If it can be fuzzed then you can add a unit test.  That's why we have netebpfext_unit.

**Review by dthaler — COMMENTED** [review]
We don't want to rely on stress tests (which won't run on every PR, only daily) to verify things like this.  I checked the code and it looks straightforward to add a unit test for as noted in my comment above.  Can it be done in this PR?

**Comment by mtfriesen** [comment]
> We don't want to rely on stress tests (which won't run on every PR, only daily) to verify things like this. I checked the code and it looks straightforward to add a unit test for as noted in my comment above. Can it be done in this PR?

I do not like checking in code without test coverage, however, my task is to replace this WFP-based callout, not invest further time and effort on it. This bug (along with several others I have found) is _extremely_ easy to repro with any code that exercises the data path.

As there is clearly a huge gap in coverage, precluding loading this WFP callout on any non-idle test system, I believe any time spent on this legacy callout should be spent validating such a basic user scenario end-to-end, not attempting to add edge/failure cases to substantially incomplete unit tests. I expect the time required to add all the missing unit test coverage is substantially higher than the time required to spin up an attach+detach test with network traffic running in the background; the latter reflecting the real-world scenario customers care about, and sufficient to catch a multitude of serious bugs.

That said, we already have that coverage, and much more, in the xdp-for-windows project. I'm happy to contribute bugfixes to this WFP callout, but cannot prioritize closing serious test gaps in the WFP callout being replaced.

**Comment by mtfriesen** [comment]
I've filed #2028 to ensure the test gap eventually gets closed.

File: netebpfext/net_ebpf_ext_xdp.c [hunk 1]
```diff
@@ -562,6 +563,7 @@ _net_ebpf_ext_handle_xdp_tx(
 
     if (status != STATUS_SUCCESS) {
         NET_EBPF_EXT_LOG_NTSTATUS_API_FAILURE(NET_EBPF_EXT_TRACELOG_KEYWORD_XDP, "FwpsInjectMacSendAsync", status);
+        _net_ebpf_ext_l2_inject_send_complete((void*)(uintptr_t)cloned_packet, nbl, FALSE);
```
Comment (Alan-Jowett) [inline netebpfext/net_ebpf_ext_xdp.c:566]: Shouldn't this pass through the dispatch flag?

**Review by Alan-Jowett — CHANGES_REQUESTED** [review]
Don't we need to preserve the dispatch flag?

File: netebpfext/net_ebpf_ext_xdp.c (hunk 1 above)
Comment (mtfriesen) [reply netebpfext/net_ebpf_ext_xdp.c:566]: You're right.

Originally, I didn't spot a handy "is at dispatch level" flag here, and the meaning of a dispatch level flag in networking is conventionally "TRUE only if known to be at dispatch level" rather than "TRUE if and only if at dispatch level". However, WFP is sometimes a bit different (if the current IRQL is known, why not design the API to simply provide the current IRQL?) and I assumed the conventional rather than WFP meaning here, which was incorrect.

However, now that you've made me look more closely at this function, it appears the `FwpsFreeCloneNetBufferList` call above is passing an incorrect parameter: the second parameter is a reserved flags field, not a dispatch level boolean. Since the dispatch level flag is therefore redundant in practice, we can fix this by either adding an IRQL check (i.e., passing the correct value) or adding one layer of indirection to the cleanup routine. Since this is an edge case and we're not micro-optimizing performance in this driver, I'll go with querying the current IRQL.

File: netebpfext/net_ebpf_ext_xdp.c [hunk 2]
```diff
@@ -562,6 +565,8 @@ _net_ebpf_ext_handle_xdp_tx(
 
     if (status != STATUS_SUCCESS) {
         NET_EBPF_EXT_LOG_NTSTATUS_API_FAILURE(NET_EBPF_EXT_TRACELOG_KEYWORD_XDP, "FwpsInjectMacSendAsync", status);
+        _net_ebpf_ext_l2_inject_send_complete(
+            (void*)(uintptr_t)cloned_packet, nbl, KeGetCurrentIrql() == DISPATCH_LEVEL);
```
Comment (saxena-anurag) [inline netebpfext/net_ebpf_ext_xdp.c:569]: nit: Since `dispatch_level` is not used in `_net_ebpf_ext_l2_inject_send_complete`, do we need to call KeGetCurrentIrql() to query the current irql.

Comment (mtfriesen) [reply netebpfext/net_ebpf_ext_xdp.c:569]: Right, we technically do not need to. In another comment thread I posted:

> Since the dispatch level flag is therefore redundant in practice, we can fix this by either adding an IRQL check (i.e., passing the correct value) or adding one layer of indirection to the cleanup routine. Since this is an edge case and we're not micro-optimizing performance in this driver, I'll go with querying the current IRQL.

If we agree with this logic, should I add a code comment? A small refactor to avoid the need for the dispatch query is also fine.

Comment (saxena-anurag) [reply netebpfext/net_ebpf_ext_xdp.c:569]: If the refactor is small, I think we can remove an extra call to `KeGetCurrentIrql()` as it is not needed.

Comment (shankarseal) [reply netebpfext/net_ebpf_ext_xdp.c:569]: Thanks for catching the leak. Why is the dispatchLevel no longer required in the FreeClone API?

Comment (mtfriesen) [reply netebpfext/net_ebpf_ext_xdp.c:569]: The [documentation](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsfreeclonenetbufferlist0) for FwpsFreeCloneNetBufferList says the second parameter is a flags bitmask, and all flags are publicly reserved. I imagine this routine was conflated for a different routine that takes a dispatch flag.

**Review by shankarseal — APPROVED** [review]

**Review by shankarseal — APPROVED** [review]
