### PR TITLE
Pickup latest ebpf-verifier to resolve #630 

### LINKED ISSUE #630: netsh ebpf show disassembly should also show the corresponding C code (if available)
llvm-objdump when used with "-S" option dumps the original C code along with the disassembly. That makes it easier to find out the corresponding C code when verification fails.

netsh ebpf show disassembly can also possibly have similar feature to dump this info, if the .o is compiled using "-g" flag, and the source file is available.

### PR DESCRIPTION
**Pull request by Alan-Jowett**
Pick up the latest ebpf-verifier.

Signed-off-by: Alan Jowett <alanjo@microsoft.com>

### CODE REVIEW

**Comment by Alan-Jowett** [comment]
> ebpf-for-windows is currently pointing at: url = https://github.com/dthaler/ebpf-verifier.git branch = twostackvars to pick up other changes. Does this PR change that? I would think a PR against my fork would be needed first to pull in the prevail PR you posted against the upstream.

This was primarily to run this through the CI/CD pipeline to make sure the path munging in the netsh tests worked correctly on different build environments.

**Comment by Alan-Jowett** [comment]
@dthaler the BTF parsing code has been merged up stream. Can you rebase or merge your branch? I can then point this pr to your branch.

**Review by dthaler — APPROVED** [review]

File: libs/api/windows_platform.cpp [hunk 1]
```diff
@@ -18,9 +18,11 @@ parse_maps_section_windows(
     std::vector<EbpfMapDescriptor>& verifier_map_descriptors,
     const char* data,
     size_t size,
+    int map_count,
     const struct ebpf_platform_t*,
     ebpf_verifier_options_t)
 {
+    UNREFERENCED_PARAMETER(map_count);
```
Comment (shankarseal) [inline libs/api/windows_platform.cpp:25]: used in line 37.

**Review by shankarseal — APPROVED** [review]
