### PR TITLE
Fix closing native program / maps handles in system worker thread. 

### LINKED ISSUE #2457: bpf_object__load hangs indefinitely if a native driver fails to load
### Describe the bug

The `bpf_object__load` API hangs indefinitely if a native driver fails to load. In this case, `pass.sys` is unloading and waiting for the NMR provider (in eBPF) to detach. Killing the process causes the native driver to unload.

```
        THREAD ffffb705995e9080  Cid 0c64.1010  Teb: 00000043baef2000 Win32Thread: 0000000000000000 WAIT: (WrLpcReply) UserMode Non-Alertable
            ffffb705995e96c8  Semaphore Limit 0x1
        Waiting for reply to ALPC Message ffffa304e44bdad0 : queued at port ffffb70595da7d30 : owned by process ffffb705961c1340
        Not impersonating
        DeviceMap                 ffffa304e32418a0
        Owning Process            ffffb7059814c080       Image:         spinxsk.exe
        Attached Process          N/A            Image:         N/A
        Wait Start TickCount      9729           Ticks: 979 (0:00:00:15.296)
        Context Switch Count      66             IdealProcessor: 3             
        UserTime                  00:00:00.000
        KernelTime                00:00:00.046
        Win32 Start Address spinxsk!ILT+985(XskFuzzerWorkerFn) (0x00007ff73a82b3de)
        Stack Init ffffdb8b8168fc10 Current ffffdb8b8168f390
        Base ffffdb8b81690000 Limit ffffdb8b81689000 Call 0000000000000000
        Priority 10 BasePriority 10 PriorityDecrement 0 IoPriority 2 PagePriority 5
*** WARNING: Unable to verify checksum for EbpfApi.dll
        Child-SP          RetAddr               Call Site
        ffffdb8b`8168f3d0 fffff805`236238e7     nt!KiSwapContext+0x76 [minkernel\ntos\ke\amd64\ctxswap.asm @ 133] 
        ffffdb8b`8168f510 fffff805`23623459     nt!KiSwapThread+0x297 [minkernel\ntos\ke\thredsup.c @ 10281] 
        ffffdb8b`8168f5d0 fffff805`236221e0     nt!KiCommitThreadWait+0x549 [minkernel\ntos\ke\waitsup.c @ 773] 
        ffffdb8b`8168f670 fffff805`23697472     nt!KeWaitForSingleObject+0x520 [minkernel\ntos\ke\wait.c @ 679] 
        (Inline Function) --------`--------     nt!AlpcpWaitForSingleObject+0x33 (Inline Function @ fffff805`23697472) [minkernel\ntos\lpc\alpc\alpcp.h @ 8351] 
        ffffdb8b`8168f740 fffff805`23c07716     nt!AlpcpSignalAndWait+0x222 [minkernel\ntos\lpc\alpc\alpcmsg.c @ 5159] 
        ffffdb8b`8168f7e0 fffff805`23c07225     nt!AlpcpReceiveSynchronousReply+0x56 [minkernel\ntos\lpc\alpc\alpcmsg.c @ 5487] 
        ffffdb8b`8168f840 fffff805`23c05652     nt!AlpcpProcessSynchronousRequest+0x3a5 [minkernel\ntos\lpc\alpc\alpcmsg.c @ 8358] 
        ffffdb8b`8168f950 fffff805`237ceff5     nt!NtAlpcSendWaitReceivePort+0x1e2 [minkernel\ntos\lpc\alpc\alpcmsg.c @ 8732] 
        ffffdb8b`8168fa10 00007ffb`f4d51924     nt!KiSystemServiceCopyEnd+0x25 (TrapFrame @ ffffdb8b`8168fa80) [minkernel\ntos\ke\amd64\trap.asm @ 3320] 
        00000043`bb7fde18 00007ffb`f4a3c642     ntdll!ZwAlpcSendWaitReceivePort+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 1283] 
        (Inline Function) --------`--------     RPCRT4!RpcpAlpcSendWaitReceivePort+0x32 (Inline Function @ 00007ffb`f4a3c642) [minio\rpc\runtime\shared\rpcpalpc.hxx @ 481] 
        (Inline Function) --------`--------     RPCRT4!LRPC_CASSOCIATION::AlpcSendWaitReceivePort+0x6d (Inline Function @ 00007ffb`f4a3c642) [minio\rpc\runtime\mtrt\lpcclnt.hxx @ 2692] 
        00000043`bb7fde20 00007ffb`f4a39b91     RPCRT4!LRPC_BASE_CCALL::DoSendReceive+0x112 [minio\rpc\runtime\mtrt\lpccall.cxx @ 3639] 
        (Inline Function) --------`--------     RPCRT4!LRPC_BASE_CCALL::SendReceive+0x26 (Inline Function @ 00007ffb`f4a39b91) [minio\rpc\runtime\mtrt\lpccall.cxx @ 648] 
        00000043`bb7fded0 00007ffb`f4a31d09     RPCRT4!LRPC_CCALL::SendReceive+0x51 [minio\rpc\runtime\mtrt\lpccall.cxx @ 8272] 
        (Inline Function) --------`--------     RPCRT4!I_RpcSendReceive+0x3a (Inline Function @ 00007ffb`f4a31d09) [minio\rpc\runtime\mtrt\msgapi.cxx @ 94] 
        (Inline Function) --------`--------     RPCRT4!NdrSendReceive+0x5a (Inline Function @ 00007ffb`f4a31d09) [minio\rpc\ndr20\auxilary.cxx @ 842] 
        00000043`bb7fdf20 00007ffb`f4a11473     RPCRT4!NdrpSendReceive+0x69 [minio\rpc\ndr20\mulsyntx.cxx @ 1914] 
        00000043`bb7fdf50 00007ffb`f4a119ef     RPCRT4!NdrpClientCall2+0x463 [minio\rpc\ndr20\cltcall.cxx @ 1107] 
        00000043`bb7fe590 00007ffb`f4b4a733     RPCRT4!NdrClientCall2+0x1f [minio\rpc\ndr20\cltcall.cxx @ 928] 
        (Inline Function) --------`--------     sechost!RControlService+0x1f (Inline Function @ 00007ffb`f4b4a733) [minkernel\screg\sc\idl\objfre\amd64\svcctl_c.c @ 112] 
        00000043`bb7fe5c0 00007ffb`c79d7c7c     sechost!ControlService+0x23 [minkernel\screg\sc\client\lib\minwin\scwrap.cxx @ 305] 
        (Inline Function) --------`--------     EbpfApi!Platform::_stop_service+0x27 (Inline Function @ 00007ffb`c79d7c7c) [D:\a\ebpf-for-windows\ebpf-for-windows\libs\thunk\windows\platform.cpp @ 294] 
        00000043`bb7fe610 00007ffb`c79e23fc     EbpfApi!_ebpf_program_load_native+0x223c [D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\ebpf_api.cpp @ 3168] 
        00000043`bb7feee0 00007ffb`c79feff9     EbpfApi!ebpf_object_load+0x1fc [D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\ebpf_api.cpp @ 2732] 
        00000043`bb7fef80 00007ff7`3a833368     EbpfApi!bpf_object__load+0x9 [D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\libbpf_object.cpp @ 127] 
        00000043`bb7fefb0 00007ff7`3a833d81     spinxsk!AttachXdpEbpfProgram+0x6c8 [D:\xdp\test\spinxsk\spinxsk.c @ 467] 
        00000043`bb7ff3c0 00007ff7`3a8364eb     spinxsk!AttachXdpProgram+0x181 [D:\xdp\test\spinxsk\spinxsk.c @ 567] 
        00000043`bb7ff630 00007ff7`3a83ceb2     spinxsk!FuzzSocketMisc+0x46b [D:\xdp\test\spinxsk\spinxsk.c @ 1457] 
        00000043`bb7ffa30 00007ffb`f44c7ad4     spinxsk!XskFuzzerWorkerFn+0x1f2 [D:\xdp\test\spinxsk\spinxsk.c @ 1891] 
        00000043`bb7ffba0 00007ffb`f4d0a371     KERNEL32!BaseThreadInitThunk+0x14 [base\win32\client\thread.c @ 64] 
        00000043`bb7ffbd0 00000000`00000000     ntdll!RtlUserThreadStart+0x21 [minkernel\ntdll\rtlstrt.c @ 1163] 
```

**[Dump and symbols](https://1drv.ms/u/s!Au_lmmNH35OUgY0r_1aSEPskmxzA8w?e=tccavj)**

### OS information

`17763.1.amd64fre.rs5_release.180914-1434`

### Steps taken to reproduce bug

[Run XDP spinxsk test](https://github.com/microsoft/xdp-for-windows/blob/main/docs/development.md#running-spinxsk) with eBPF enabled.

Actual repro command: `.\tools\spinxsk.ps1 -SuccessThresholdPercent 1 -XdpmpPollProvider FNDIS -Verbose -BreakOnWatchdog -EnableEbpf -QueueCount 1`

### Expected behavior

eBPF APIs should not block indefinitely.

### Actual outcome

An eBPF API blocks indefinitely when cleaning up a failed driver load.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #2457

## Description

Earlier fix done in PR #2395 was incomplete. The previous fix queued a workitem to close the program and map handles in the case of native module load failure. Closing the handles in system worker thread fails with `INVALID_HANDLE` as the handle is created for type `UserMode`, and the worker thread is running in system context.

The fix is to attach the current process to the worker thread to be able to close the handles. The new fix does the following:
1. take reference on the current process, and pass process info to the worker thread.
2. worker thread attaches process, closes handles, detaches process and release process reference.

## Testing

Added new kernel tests.

## Documentation

NA

### CODE REVIEW

File: libs/platform/kernel/ebpf_platform_kernel.c [hunk 1]
```diff
@@ -15,6 +15,11 @@ static uint32_t _ebpf_platform_maximum_processor_count = 0;
 extern DEVICE_OBJECT*
 ebpf_driver_get_device_object();
 
+typedef struct _ebpf_process_state
```
Comment (shankarseal) [inline libs/platform/kernel/ebpf_platform_kernel.c:18]: `typedef KAPC_STATE ebpf_process_state_t` ?

File: libs/platform/kernel/ebpf_platform_kernel.c [hunk 2]
```diff
@@ -920,3 +925,36 @@ ebpf_utf8_string_to_unicode(_In_ const ebpf_utf8_string_t* input, _Outptr_ wchar
...
+
+intptr_t
+ebpf_platform_reference_process()
+{
+    PEPROCESS process = PsGetCurrentProcess();
+    ObReferenceObject(process);
+    return (intptr_t)process;
+}
+
+_Ret_maybenull_ ebpf_process_state_t*
```
Comment (shankarseal) [inline libs/platform/kernel/ebpf_platform_kernel.c:937]: ?? what is the need for this function?

File: libs/execution_context/ebpf_native.c [hunk 3]
```diff
@@ -1285,6 +1293,13 @@ _ebpf_native_close_handles_work_item(_In_opt_ const void* context)
         }
     }
 
+    // Detach process from this worker thread.
+    ebpf_platform_detach_process(handle_info->process_state);
+
+    // Release the reference on the process object.
+    ebpf_platform_dereference_process(handle_info->process_handle);
```
Comment (shankarseal) [inline libs/execution_context/ebpf_native.c:1300]: Is this needed given line 1319 ?

Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c:1300]: Yes, 1319 line is for the cleanup path which is not called in this path.

File: libs/platform/kernel/ebpf_platform_kernel.c (hunk 2 above)
Comment (saxena-anurag) [reply libs/platform/kernel/ebpf_platform_kernel.c:937]: Since ebpf_platform.h only contains:
```typedef struct _ebpf_process_state ebpf_process_state_t;```
the file which includes this does not know the size of the struct -- so `sizeof(ebpf_process_state_t)` will give compiler error.

File: libs/execution_context/ebpf_native.c [hunk 4]
```diff
@@ -309,6 +311,7 @@ _Requires_exclusive_lock_held_(module->lock) static void _ebpf_native_acquire_re
 void
 ebpf_native_acquire_reference(_Inout_ ebpf_native_module_t* module)
 {
+    EBPF_LOG_ENTRY();
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.c:314]: I believe this macro must always be paired with another macro.
In this case, I think it's `EBPF_RETURN_VOID();` at the end.

But I think this is a hot path.  Do you really want to be introducing log calls into the hot path?  How much of a perf hit is it?

File: libs/execution_context/ebpf_native.c [hunk 5]
```diff
@@ -319,6 +322,7 @@ ebpf_native_acquire_reference(_Inout_ ebpf_native_module_t* module)
 void
 ebpf_native_release_reference(_In_opt_ _Post_invalid_ ebpf_native_module_t* module)
 {
+    EBPF_LOG_ENTRY();
```
Comment (dthaler) [inline libs/execution_context/ebpf_native.c:325]: missing matching EXIT macros.

File: libs/execution_context/ebpf_native.c (hunk 4 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c:314]: This is not in the hot path. Native module reference is acquired only when the native module is loaded, and released when the ebpf programs and/or the native module are unloaded.

But agree about pairing. I will change the tracing.

Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c]: Actually ended up removing this, as there is a reference history also maintained.

File: libs/execution_context/ebpf_native.c (hunk 5 above)
Comment (saxena-anurag) [reply libs/execution_context/ebpf_native.c]: same as above.

**Review by dthaler — APPROVED** [review]

File: libs/platform/user/ebpf_platform_user.cpp [hunk 6]
```diff
@@ -1408,3 +1413,37 @@ ebpf_utf8_string_to_unicode(_In_ const ebpf_utf8_string_t* input, _Outptr_ wchar
...
+{
+    ebpf_process_state_t* state = (ebpf_process_state_t*)ebpf_allocate(sizeof(ebpf_process_state_t));
+    return state;
+}
+
+intptr_t
+ebpf_platform_reference_process()
+{
+
+    HANDLE process = GetCurrentProcess();
```
Comment (matthewige) [inline libs/platform/user/ebpf_platform_user.cpp:1428]: Does this actually create a reference? If not, should this function be renamed to something else?

Comment (matthewige) [reply libs/platform/user/ebpf_platform_user.cpp:1428]: I see a bunch of functions below are not implemented - if that is by design, do we have an issue tracking the completion of this?

Comment (saxena-anurag) [reply libs/platform/user/ebpf_platform_user.cpp:1428]: It does not. This is just a user mode mock (same for the other APIs which do not have an implementation in user mode). These operations are not applicable for user mode, but the APIs are needed for the code to compile in the user mode.

Comment (saxena-anurag) [reply libs/platform/user/ebpf_platform_user.cpp:1428]: Yes, I will add comments as discussed.

File: libs/platform/user/ebpf_platform_user.cpp [hunk 7]
```diff
@@ -1408,3 +1413,37 @@ ebpf_utf8_string_to_unicode(_In_ const ebpf_utf8_string_t* input, _Outptr_ wchar
     ebpf_free(unicode_string);
     return retval;
 }
+
+_Ret_maybenull_ ebpf_process_state_t*
+ebpf_allocate_process_state()
```
Comment (shpalani) [inline libs/platform/user/ebpf_platform_user.cpp:1418]: Can you check Fault injection needed for all the new functions introduced?

I believe it is needed.

Comment (saxena-anurag) [reply libs/platform/user/ebpf_platform_user.cpp:1418]: This PR is adding the following APIs:

```
ebpf_allocate_process_state
ebpf_platform_reference_process
ebpf_platform_dereference_process
ebpf_platform_attach_process
ebpf_platform_detach_process
```
Only one of these APIs is expected to fail -- `ebpf_allocate_process_state`. And since that API calls `ebpf_allocate()`, it is already covered for fault injection.

Comment (shpalani) [reply libs/platform/user/ebpf_platform_user.cpp:1418]: Thanks for checking it. Please add a comment for ebpf_allocate_process_state with
Fault injection as skipped.

**Review by shpalani — DISMISSED** [review]

File: libs/platform/user/ebpf_platform_user.cpp (hunk 7 above)
Comment (saxena-anurag) [reply libs/platform/user/ebpf_platform_user.cpp:1418]: Added.

File: libs/platform/user/ebpf_platform_user.cpp (hunk 6 above)
Comment (saxena-anurag) [reply libs/platform/user/ebpf_platform_user.cpp:1429]: Added.

**Review by shpalani — APPROVED** [review]

**Review by dthaler — APPROVED** [review]
