### PR TITLE
Fuzzing bug fixes

### LINKED ISSUE #3992: Directory.Build.Props uses %(AdditionalOptions) instead of $(AdditionalOptions)
When expanding additional options, MSBuild only does replacement for $(AdditionalOptions) and not %(AdditionalOptions), so as a result subsequent additional options don't inherit correctly.

### LINKED ISSUE #4010: Potential security issues found by fuzzing
Sometime back, a through security review was conducted on the eBPF code base; along with running fuzz testing that unearthed quite a few bugs that could have potential security implications. Here are the list of issues that are copied from the titles of ADO tasks in an internal project. The line numbers of the source could be off as these are dated information.

- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1966 in ebpf_program_get_info
- [ ] Heap Buffer Overflow in `ebpf_program_get_info()` (ebpf_program.c:1870)
- [ ] Heap Buffer Overflow in `ebpf_program_get_info()` (ebpf_program.c:1870)  
- [ ] Arbitrary write -- ebpf_program_get_info (ebpf_program.c:1888)  
- [ ] Controlled Allocation -- ebpf_maps.c :3.  
- [ ] Access Violation -- libs\execution_context\ebpf_program.c:1511 in _ebpf_program_get_helper_function_address  
- [ ] Divide by Zero -- libs\execution_context\ebpf_core.c: in _ebpf_core_protocol_map_delete_element_batch  
- [ ] Access Violation -- external\ubpf\vm\ubpf_vm.c:289 in ubpf_exec  
- [ ] Heap Buffer Overflow -- libs\runtime\ebpf_hash_table.c:138 in _ebpf_murmur3_32  
- [ ] Access Violation -- libs\execution_context\ebpf_program.c:1483 in _ebpf_program_get_helper_function_address  
- [ ] Use After Free -- libs\execution_context\ebpf_core.c:1178 in _ebpf_core_protocol_program_test_run_complete  
- [ ] Heap Buffer Overflow -- libs\runtime\ebpf_hash_table.c:122 in _ebpf_murmur3_32  
- [ ] Heap Buffer Overflow -- ebpf-for-windows\netebpfext\net_ebpf_ext_bind.c:223 in _net_ebpf_ext_resource_truncate_appid  
- [ ] fake crash site  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\external\ubpf\vm\ubpf_vm.c:197 in ubpf_load  
- [ ] AddressSanitizer: access-violation D:\a\1\s\libs\execution_context\ebpf_maps.c:1678 in _next_lpm_map_key_and_value  
- [ ] AddressSanitizer: access-violation on unknown address 0xffffffffffffffff (pc 0x7ff74525e5 bp 0x12bd5... [57364FF1]  
- [ ] Heap Buffer Overflow (read)ebpf_program_get_info (ebpf_program.c:1870)  
- [ ] Arbitrary write -- ebpf_program_get_info (ebpf_program.c:1888)  
- [ ] Controlled Allocation -- bpf_maps.c :3.  
- [ ] Access Violation -- libs\execution_context\ebpf_program.c:1511 in _ebpf_program_get_helper_function_address  
- [ ] Divide by Zero -- libs\execution_context\ebpf_core.c: in _ebpf_core_protocol_map_delete_element_batch  
- [ ] Heap Buffer Overflow -- libs\runtime\ebpf_hash_table.c:138 in _ebpf_murmur3_32  
- [ ] Access Violation -- libs\execution_context\ebpf_program.c:1483 in _ebpf_program_get_helper_function_address  
- [ ] Use After Free -- libs\execution_context\ebpf_core.c:1178 in _ebpf_core_protocol_program_test_run_complete  
- [ ] Heap Buffer Overflow -- libs\runtime\ebpf_hash_table.c:122 in _ebpf_murmur3_32  
- [ ] Heap Buffer Overflow -- netebpfext\net_ebpf_ext_bind.c:223 in _net_ebpf_ext_resource_truncate_appid  Security
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1966 in ebpf_program_get_info  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1967 in ebpf_program_get_info  
- [ ] AddressSanitizer: int-divide-by-zero D:\a\1\s\libs\execution_context\ebpf_core.c: in _ebpf_core_pr... [3E8AFE]  
- [ ] libFuzzer: out-of-memory  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1923 in ebpf_program_get_info  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1922 in ebpf_program_get_info  
- [ ] AddressSanitizer: int-divide-by-zero D:\a\1\s\libs\execution_context\ebpf_core.c:1021 in _ebpf_core_pr... [865938E3]  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1976 in ebpf_program_get_info  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:1977 in ebpf_program_get_info  
- [ ] AddressSanitizer: int-divide-by-zero D:\a\1\s\libs\execution_context\ebpf_core.c:1005 in _ebpf_core_pr... [BB894F3F]  
- [ ] libFuzzer: deadly signal  
- [ ] Possible null pointer deref in _ebpf_program_get_helper_function_address  
- [ ] Lack of code_type validation in ebpf_program.c  
- [ ] Potential out of bound writes on ebpf_map_definition.type parameter in ebpf_maps.c  
- [ ] Potential heap buffer-over read in _net_ebpf_ext_resource_truncate_appid()  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:21 in ebpf_program_get_info  New  
- [ ] AddressSanitizer: heap-buffer-overflow D:\a\1\s\libs\execution_context\ebpf_program.c:22 in ebpf_program_get_info  New

### PR DESCRIPTION
**Pull request by shankarseal**
## Description

This PR fixes #4010. These are a collection of bugs found by fuzz testing.
This PR also fixes #3992, #3998 and #4001.

## Testing

New fuzz tests were added.

## Documentation

No.

## Installation

No.

### CODE REVIEW

**Review by Alan-Jowett — APPROVED** [review]

**Review by dthaler — COMMENTED** [review]
In my view "These are a collection of bug fixes found by fuzz testing." is not a sufficient PR description.  I don't know how to review this since I don't know what's being fixed so I can't tell whether it fixes them right.  (And I suspect not since the tests appear to be failing.)

File: libs/execution_context/ebpf_core.c [hunk 1]
```diff
@@ -2124,6 +2176,11 @@ _ebpf_core_map_find_element(ebpf_map_t* map, const uint8_t* key)
 {
     ebpf_result_t retval;
     uint8_t* value;
+    // Workaround for bug in ebpf-verifier that permits NULL map. Remove when fixed.
```
Comment (dthaler) [inline libs/execution_context/ebpf_core.c:2179]: Add issue number to comment so one can track when it's fixed.
Same in line 2195 etc.

File: libs/execution_context/ebpf_program.c [hunk 2]
```diff
@@ -2569,6 +2588,11 @@ ebpf_program_execute_test_run(
     test_run_context->completion_context = completion_context;
     test_run_context->completion_callback = callback;
 
+    // Limit maximum test runs to 1024 while fuzzing to prevent timeouts.
+#if defined(FUZZER_BUILD)
+    test_run_context->options->repeat_count = min(test_run_context->options->repeat_count, 1024);
+#endif
```
Comment (dthaler) [inline libs/execution_context/ebpf_program.c:2594]: To me this seems the wrong place to put test-specific ifdefs.
Why can't this be in the fuzzer code itself instead of in the execution context?
Or alternatively, why is it fuzzer specific?

File: libs/runtime/ebpf_bitmap.c [hunk 3]
```diff
@@ -100,6 +103,26 @@ ebpf_bitmap_start_forward_search(_In_ const ebpf_bitmap_t* bitmap, _Out_ ebpf_bi
     internal_cursor->current_block_copy = bitmap->data[BIT_TO_BLOCK(internal_cursor->next_bit_offset)];
 }
 
+void
+ebpf_bitmap_start_forward_search_at(
```
Comment (dthaler) [inline libs/runtime/ebpf_bitmap.c:107]: This looks like new logic.  [The project contributing guidelines](https://github.com/microsoft/ebpf-for-windows/blob/main/CONTRIBUTING.md#contributing-code) state:
> For all but the absolute simplest changes, first [submit a GitHub Issue](https://github.com/microsoft/ebpf-for-windows/issues/new)

What issue is this addressing?

File: libs/runtime/ebpf_bitmap.h [hunk 4]
```diff
@@ -101,4 +137,4 @@ extern "C"
 
 #ifdef __cplusplus
 }
-#endif
+#endif
```
Comment (dthaler) [inline libs/runtime/ebpf_bitmap.h:140]: Why is this line changed?

File: scripts/config_test_vm.psm1 [hunk 5]
```diff
@@ -1,4 +1,4 @@
-﻿# Copyright (c) eBPF for Windows contributors
+# Copyright (c) eBPF for Windows contributors
```
Comment (dthaler) [inline scripts/config_test_vm.psm1:1]: I can't tell... what is the change in this line?

File: scripts/run_driver_tests.psm1 [hunk 6]
```diff
@@ -1,4 +1,4 @@
-﻿# Copyright (c) eBPF for Windows contributors
+# Copyright (c) eBPF for Windows contributors
```
Comment (dthaler) [inline scripts/run_driver_tests.psm1:1]: I can't tell... what is the change in this line?

File: tests/libfuzzer/include/fuzz_helper_function.hpp [hunk 7]
```diff
@@ -0,0 +1,560 @@
...
+        ebpf_core_terminate();
+    }
+
+    /**
+     * @brief Fuzz the helper function with the supplied data.
+     *
+     * @param[in] data_left The data to use when fuzzing the helper function.
+     * @param[in] data_left_size The size of the data to use when fuzzing the helper function.
+     * @return 0 - Add this to the corpus.
+     * @return -1 - Discard this input.
```
Comment (dthaler) [inline tests/libfuzzer/include/fuzz_helper_function.hpp:99]:
```suggestion
     * @retval 0 Add this to the corpus.
     * @retval -1 Discard this input.
```

File: tests/libfuzzer/include/fuzz_helper_function.hpp [hunk 8]
```diff
@@ -0,0 +1,560 @@
...
+
+        // Call into the helper.
+        switch (arg_count) {
+        case 0:
+            ((function0_t)helper_function_address)();
+            break;
+        case 1:
+            ((function1_t)helper_function_address)(argument[0]);
+            break;
+
```
Comment (dthaler) [inline tests/libfuzzer/include/fuzz_helper_function.hpp:267]: Remove blank line for consistency, or else add blank lines to the other cases.

File: tests/libfuzzer/include/fuzz_helper_function.hpp [hunk 9]
```diff
@@ -0,0 +1,560 @@
...
+    typedef uint64_t (*function1_t)(uint64_t r1);
+    typedef uint64_t (*function2_t)(uint64_t r1, uint64_t r2);
+    typedef uint64_t (*function3_t)(uint64_t r1, uint64_t r2, uint64_t r3);
+    typedef uint64_t (*function4_t)(uint64_t r1, uint64_t r2, uint64_t r3, uint64_t r4);
+    typedef uint64_t (*function5_t)(uint64_t r1, uint64_t r2, uint64_t r3, uint64_t r4, uint64_t r5);
+
+    // Consume the next output_size bytes from the input data and save them in the supplied output buffer.
+    bool
+    consume_data(
+        const uint8_t** input, size_t* input_size, _Out_writes_(output_size) uint8_t* output, size_t output_size)
```
Comment (dthaler) [inline tests/libfuzzer/include/fuzz_helper_function.hpp:455]: missing SAL annotations on input, input_size

File: tests/libfuzzer/include/fuzz_helper_function.hpp [hunk 10]
```diff
@@ -0,0 +1,560 @@
...
+            wrapper->helper_prototypes[helper_prototype->helper_id] = helper_prototype;
+            wrapper->helper_functions_addresses[helper_prototype->helper_id] =
+                wrapper->program_data->program_type_specific_helper_function_addresses->helper_function_address[i];
+        }
+
+        return STATUS_SUCCESS;
+    }
+
+    static NTSTATUS
+    _program_information_detach_provider(void* client_binding_context)
```
Comment (dthaler) [inline tests/libfuzzer/include/fuzz_helper_function.hpp:518]: missing SAL annotation.  If intentional, add a comment saying so.

File: tests/sample/sample.vcxproj.filters [hunk 11]
```diff
@@ -1,4 +1,4 @@
-﻿<?xml version="1.0" encoding="utf-8"?>
+<?xml version="1.0" encoding="utf-8"?>
```
Comment (dthaler) [inline tests/sample/sample.vcxproj.filters:1]: I can't tell, what is the change in this line?

Comment (shankarseal) [reply tests/sample/sample.vcxproj.filters:1]: There are many such lines that the tool is showing as diff, but there arent any changes - not even white spaces. Not sure what to do about these. So I kept them.

Comment (dthaler) [reply tests/sample/sample.vcxproj.filters:1]: If there are no changes, you remove them from the changelist.

**Comment by Alan-Jowett** [comment]
> In my view "These are a collection of bug fixes found by fuzz testing." is not a sufficient PR description. I don't know how to review this since I don't know what's being fixed so I can't tell whether it fixes them right. (And I suspect not since the tests appear to be failing.)

I second this. As much as it is going to be painful to do, we should file each internally found bug in github, and fix them in the open.

File: libs/runtime/ebpf_bitmap.h (hunk 4 above)
Comment (shankarseal) [reply libs/runtime/ebpf_bitmap.h:140]: I am resolving this and other similar comments about the diff tool reporting changes when apparently no changes occurred, including white space.

File: tests/sample/sample.vcxproj.filters (hunk 11 above)
Comment (shankarseal) [reply tests/sample/sample.vcxproj.filters:1]: @dthaler all of these are removing the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). I could ignore these changes or keep them. Preference?

File: libs/execution_context/ebpf_program.c (hunk 2 above)
Comment (shankarseal) [reply libs/execution_context/ebpf_program.c]: Fixed.

File: tests/sample/sample.vcxproj.filters (hunk 11 above)
Comment (shankarseal) [reply tests/sample/sample.vcxproj.filters]: I have removed this and other files with only BOM changes.

Comment (dthaler) [reply tests/sample/sample.vcxproj.filters]: Actually I'd say remove the BOM changes since they're not part of "Fuzzing bug fixes".

**Comment by dthaler** [comment]
Issue #4001 is fixed by PR #4002 so I'd recommend that be merged first and this be rebased, or else remove it from this PR.

**Comment by dthaler** [comment]
Issue #3992 is fixed by PR #3991 so I'd recommend that be merged first and this be rebased, or else remove it from this PR.

**Comment by dthaler** [comment]
Issue #3998 is just a perf optimization according to that issue, and is apparently non-trivial, so should be separated from security bug fixes.  The principle is that a fix for #4010 would be a backport candidate (e.g., to v.0.19.1) but a PR for #3998 would not be since it doesn't fix any security issue that affects production.

File: libs/runtime/ebpf_bitmap.c (hunk 3 above)
Comment (mikeagun) [reply libs/runtime/ebpf_bitmap.c:107]: `reverse_search_at` was added to fix some of the Heap Buffer Overflows in _ebpf_murmur3_32 mentioned in #4010 

The forward search function was just added at the same time, but is not currently needed (could be removed).

The problem was that reverse search could return a bit past the key length, so to initialize search at a point other than the start/end we need to clear the bits before/after the start index in the start block.

**Comment by shankarseal** [comment]
> Issue #3998 is just a perf optimization according to that issue, and is apparently non-trivial, so should be separated from security bug fixes. The principle is that a fix for #4010 would be a backport candidate (e.g., to v.0.19.1) but a PR for #3998 would not be since it doesn't fix any security issue that affects production.

0.19.1 already has these changes that are being merged to main. Without fix to 3998 first, many of the issues would not be even found, that this PR is fixing as otherwise the fuzz tests took too long to run and often timed out without finding any issues.

Hopefully, this is the first and last time where we have to merge so many fixes together. Please approve so that we can get this important payload merged.

**Comment by shankarseal** [comment]
> > In my view "These are a collection of bug fixes found by fuzz testing." is not a sufficient PR description. I don't know how to review this since I don't know what's being fixed so I can't tell whether it fixes them right. (And I suspect not since the tests appear to be failing.)
> 
> I second this. As much as it is going to be painful to do, we should file each internally found bug in github, and fix them in the open.

Due to special circumstances we had to take these set of changes this way, after discussing with Microsoft security experts. Hopefully we will only rarely get security bugs, which we will fix according to the [MSRC ](https://www.microsoft.com/en-us/msrc/?msockid=1f59c79472266e9504e0d29373e16fb2&oneroute=true) process.

File: libs/execution_context/ebpf_core.c (hunk 1 above)
Comment (shankarseal) [reply libs/execution_context/ebpf_core.c]: Fixed.

File: libs/runtime/ebpf_bitmap.c (hunk 3 above)
Comment (shankarseal) [reply libs/runtime/ebpf_bitmap.c]: I have removed the dead code `_forward_search_at`.

**Comment by shankarseal** [comment]
> Issue #3992 is fixed by PR #3991 so I'd recommend that be merged first and this be rebased, or else remove it from this PR.

#3991 is changed to draft.

**Comment by shankarseal** [comment]
> In my view "These are a collection of bug fixes found by fuzz testing." is not a sufficient PR description. I don't know how to review this since I don't know what's being fixed so I can't tell whether it fixes them right. (And I suspect not since the tests appear to be failing.)

PR description is updated with more context and a new issue #4010 is created that lists all the defects found by fuzzing

File: scripts/run_driver_tests.psm1 (hunk 6 above)
Comment (shankarseal) [reply scripts/run_driver_tests.psm1]: file removed from PR.

**Review by mikeagun — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
