### PR TITLE
Bail if we can't enter rundown in WFP classify callbacks

### LINKED ISSUE #3097: Workflow failed - km_mt_stress_tests_restart_extension
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/7057389704)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/33f8f29d1fbc1374dec127f88588d2d2e80f7b3e)
Test name - `km_mt_stress_tests_restart_extension`

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

In certain instances, inability to enter rundown does not indicate a fatal error.  It just means that we lost the race to get there, so we should just exit.

## Testing

CI/CD  only (Bug cannot be repro'd locally)

## Documentation

No doc changes.

## Installation

No installer changes.

Fixes #3097

### CODE REVIEW

File: netebpfext/net_ebpf_ext_bind.c [hunk 1]
```diff
@@ -273,7 +273,19 @@ net_ebpf_ext_resource_allocation_classify(
     }
 
     attached_client = (net_ebpf_extension_hook_client_t*)filter_context->client_context;
-    ENTER_HOOK_CLIENT_RUNDOWN(attached_client);
+    if (!net_ebpf_extension_hook_client_enter_rundown(attached_client)) {
+        // In some stress-testing related edge cases (especially where we unload/reload this extension rapidly) we end
```
Comment (shankarseal) [inline netebpfext/net_ebpf_ext_bind.c:277]: This comment should be removed from here IMO. If you must, put it inside `net_ebpf_extension_hook_client_enter_rundown` .

Comment (dv-msft) [reply netebpfext/net_ebpf_ext_bind.c:277]: I waffled between the two for a bit, but thought it seemed to make more sense _here_ as this is where we take the specific _action_ based on the return value.  IMO, the `net_ebpf_extension_hook_client_enter_rundown` ought to just return the result of the operation ('mechanism') as opposed to the processing thereof ('policy') which is best determined by the caller.

Case in point is the call from the `net_ebpf_extension_wfp_filter_context_create` where we end up calling `fastfail` in response to the error result.  

To my mind, inability to acquire a rundown is serious enough an event that it deserves a comment _where-ever_ it occurs, hence IMO the repetition is justified.  Also, the comment may seem overly repetitive in _this_ PR, but in reality, the affected code file(s) lie in different contexts. 

Thoughts?

Comment (Alan-Jowett) [reply netebpfext/net_ebpf_ext_bind.c:277]: I really don't like having multiple copies of something, be it comment or code. It will invariably end up getting out of synch. Maybe turn it into a macro?

Comment (dv-msft) [reply netebpfext/net_ebpf_ext_bind.c]: Removed the comment ( A macro did not really buy anything significant).

**Review by shankarseal — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
