### PR TITLE
Fix sock_ops code flow and test

### LINKED ISSUE #4584: sock_ops_thread_function triggers assert in usersim by deleting invalid flow
Assert here:
```
15 0000002f`27dff510 00007ffa`c1be43c6     ucrtbased!_wassert+0x2f [minkernel\crts\ucrt\src\appcrt\startup\assert.cpp @ 444] 
16 0000002f`27dff540 00007ffa`c1be82e3     usersim!fwp_engine_t::delete_flow_context+0x216 [D:\a\1\s\external\usersim\src\fwp_um.h @ 123] 
17 0000002f`27dff680 00007ffa`c1be8586     usersim!fwp_engine_t::test_remove_flow_context+0x103 [D:\a\1\s\external\usersim\src\fwp_um.cpp @ 227] 
18 0000002f`27dff700 00007ffa`c1be9b2f     usersim!fwp_engine_t::test_sock_ops_v4_remove_flow_context+0x36 [D:\a\1\s\external\usersim\src\fwp_um.cpp @ 203] 
19 0000002f`27dff730 00007ff6`b0b09a8a     usersim!usersim_fwp_sock_ops_v4_remove_flow_context+0x2f [D:\a\1\s\external\usersim\src\fwp_um.cpp @ 1038] 
1a 0000002f`27dff770 00007ff6`b0b07018     netebpfext_unit!_netebpf_ext_helper::test_sock_ops_v4_remove_flow_context+0x1a [D:\a\1\s\tests\netebpfext_unit\netebpf_ext_helper.h @ 98] 
1b 0000002f`27dff7a0 00007ff6`b0ad9bb0     netebpfext_unit!sock_ops_thread_function+0x298 [D:\a\1\s\tests\netebpfext_unit\netebpfext_unit.cpp @ 1141] 
1c 0000002f`27dff880 00007ff6`b0ad207f     netebpfext_unit!std::invoke<void (__cdecl*)(std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,unsigned __int64,unsigned char,unsigned short,unsigned short,enum _sock_ops_test_action),std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,int,int,unsigned short,unsigned short,enum _sock_ops_test_action>+0x150 [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits @ 1680] 
1d 0000002f`27dff940 00007ffa`ca5b2ef5     netebpfext_unit!std::thread::_Invoke<std::tuple<void (__cdecl*)(std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,unsigned __int64,unsigned char,unsigned short,unsigned short,enum _sock_ops_test_action),std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,int,int,unsigned short,unsigned short,enum _sock_ops_test_action>,0,1,2,3,4,5,6,7,8,9>+0x18f [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\thread @ 61] 
1e 0000002f`27dffa30 00007ffa`ee6f4cb0     ucrtbased!thread_start<unsigned int (__cdecl*)(void *),1>+0xa5 [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 97] 
1f 0000002f`27dffa90 00007ffa`f05bedcb     kernel32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
20 0000002f`27dffac0 00000000`00000000     ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 
```

This is triggered in fault injection, with the failing call stack being:
```
    [0]              : "_cxplat_fault_injection::is_new_stack + 277 D:\a\1\s\external\usersim\cxplat\src\cxplat_winuser\fault_injection.cpp 245" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [1]              : "_cxplat_fault_injection::inject_fault + 32 D:\a\1\s\external\usersim\cxplat\src\cxplat_winuser\fault_injection.cpp 213" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [2]              : "cxplat_fault_injection_inject_fault + 58 D:\a\1\s\external\usersim\cxplat\src\cxplat_winuser\fault_injection.cpp 408" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [3]              : "FwpsFlowAssociateContext0 + 43 D:\a\1\s\external\usersim\src\fwp_um.cpp 734" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [4]              : "net_ebpf_extension_sock_ops_flow_established_classify + 852 D:\a\1\s\netebpfext\net_ebpf_ext_sock_ops.c 535" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [5]              : "fwp_engine_t::test_callout + 680 D:\a\1\s\external\usersim\src\fwp_um.cpp 198" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [6]              : "fwp_engine_t::test_sock_ops_v4 + 360 D:\a\1\s\external\usersim\src\fwp_um.cpp 432" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [7]              : "usersim_fwp_sock_ops_v4 + 57 D:\a\1\s\external\usersim\src\fwp_um.cpp 1019" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [8]              : "_netebpf_ext_helper::test_sock_ops_v4 + 36 D:\a\1\s\tests\netebpfext_unit\netebpf_ext_helper.h 87" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [9]              : "sock_ops_thread_function + 333 D:\a\1\s\tests\netebpfext_unit\netebpfext_unit.cpp 1113" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [10]             : "std::invoke<void (__cdecl*)(std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,unsigned __int64,unsigned char,unsigned short,unsigned short,enum _sock_ops_test_action),std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,int,int,unsigned short,unsigned short,enum _sock_ops_test_action> + 336 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits 1680" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [11]             : "std::thread::_Invoke<std::tuple<void (__cdecl*)(std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,unsigned __int64,unsigned char,unsigned short,unsigned short,enum _sock_ops_test_action),std::stop_token,_netebpf_ext_helper *,_fwp_classify_parameters *,std::atomic<unsigned __int64> *,int,int,unsigned short,unsigned short,enum _sock_ops_test_action>,0,1,2,3,4,5,6,7,8,9> + 399 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\i... [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [12]             : "register_onexit_function + 245" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [13]             : "BaseThreadInitThunk + 16" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [14]             : "RtlUserThreadStart + 43" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
```

### PR DESCRIPTION
**Pull request by LakshK98**
## Description

- Currently the sock_ops classifyfn invokes the attached bpf program even if FwpsFlowAssociateContext0 has failed. Changed the logic to exit when FwpsFlowAssociateContext0 fails.

- When fault injection is enabled calls to FwpsFlowAssociateContext0 can fail. When this happens a call to test_sock_ops_v4_remove_flow_context will trigger an assert. [This pr](https://github.com/microsoft/usersim/pull/272) in usersim updates remove_flow_context and now it only deletes flow context if it exists. Bumping usersim to include this change

Closes #4584 

## Testing

CICD
## Documentation

NA
## Installation

NA

### CODE REVIEW

File: tests/netebpfext_unit/netebpfext_unit.cpp [hunk 1]
```diff
@@ -1123,22 +1123,22 @@ sock_ops_thread_function(
         count++;
 
         if (result != expected_result) {
-            // If fault injection is enabled, then id can be 0 and lead to crash when trying to remove the flow context.
-            if (fault_injection_enabled && flow_id == 0) {
+            // If fault injection is enabled, results can be different.
+            if (fault_injection_enabled) {
```
Comment (matthewige) [inline tests/netebpfext_unit/netebpfext_unit.cpp]: Is fault_injection_enabled the right check here? Is it possible to instead check something else, such as utilizing the return value from one of the above calls, to determine if a fault was actually triggered?

If we always skip the rest of the logic here when fault injection is enabled, are we losing out on validating some scenarios?

Comment (lakshk98) [reply tests/netebpfext_unit/netebpfext_unit.cpp]: test_sock_ops_v4   invokes the sock_ops classify function which invokes FwpsFlowAssociateContext0 

when fault injection is enabled FwpsFlowAssociateContext0 can fail but the  sock_ops classify function will still return FWP_ACTION_PERMIT 

 so there is no way for the caller of test_sock_ops_v4 to know whether the flow context association has failed. So I think a conditional deletion test based on result of FwpsFlowAssociateContext0 is not possible here

Comment (lakshk98) [reply tests/netebpfext_unit/netebpfext_unit.cpp]: took a change to usersim and updated logic here accordingly

**Review by mikeagun — APPROVED** [review]
