### PR TITLE
Ensure valid shift values for *SH* instructions.

### LINKED ISSUE #2465: bpf2c incorrectly handles LSH, RSH and ARSH operations
After pulling in an update to ebpf-verifier, the bpf2c conformance tests fail:
```
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\arsh64-imm-high.data" Plugin returned incorrect return value ffffffffffffffff
 expected 18446744073709551608
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\arsh64-imm-neg.data" Plugin returned incorrect return value ffffffffffffffff
 expected 18446744073709551608
PASS: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\arsh64-imm.data"
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\arsh64-reg-high.data" Plugin returned incorrect return value ffffffffffffffff
 expected 18446744073709551608
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\arsh64-reg-neg.data" Plugin returned incorrect return value ffffffffffffffff
 expected 18446744073709551608
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh32-imm-high.data" Plugin returned incorrect return value 0
 expected 268435456
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh32-imm-neg.data" Plugin returned incorrect return value 0
 expected 268435456
PASS: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh32-imm.data"
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh32-reg-high.data" Plugin returned incorrect return value 0
 expected 268435456
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh32-reg-neg.data" Plugin returned incorrect return value 0
 expected 268435456
PASS: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh32-reg.data"
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh64-imm-high.data" Plugin returned incorrect return value 0
 expected 16
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh64-imm-neg.data" Plugin returned incorrect return value 0
 expected 16
PASS: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh64-imm.data"
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh64-reg-high.data" Plugin returned incorrect return value 0
 expected 16
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\lsh64-reg-neg.data" Plugin returned incorrect return value 0
 expected 16
 FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\rsh64-imm-high.data" Plugin returned incorrect return value 0
 expected 1
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\rsh64-imm-neg.data" Plugin returned incorrect return value 0
 expected 1
PASS: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\rsh64-imm.data"
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\rsh64-reg-high.data" Plugin returned incorrect return value 0
 expected 1
FAIL: "D:\\a\\ebpf-for-windows\\ebpf-for-windows\\external\\ebpf-verifier\\external\\bpf_conformance\\tests\\rsh64-reg-neg.data" Plugin returned incorrect return value 0
 expected 1
 ```

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

Shifts of >= 64 bits on 64-bit values and >= 32 bits on 32-bits values result in undefined behavior so we need to mask off the msb of the shift size.

## Testing

Ensure that all latest 'bpf_conformance' tests pass.

`bpf_conformance_runner.exe --test_file_directory D:\wrk\bpf_conformance\tests --exclude_regex lock* --plugin_path .\bpf2c_plugin.exe --plugin_options "--include d:\wrk\ebpf-for-windows\include"`

_Note: The above command-line refers to a local directory `D:\wrk\bpf_conformance\tests` cloned from the master bpf_conformance [repo](https://github.com/Alan-Jowett/bpf_conformance)._

## Documentation

_Is there any documentation impact for this change?_

No doc changes.

Fixes #2465

### CODE REVIEW

**Comment by Alan-Jowett** [comment]
Can you format the generated code using format-code.ps1? This should eliminate spurious whitespaces changes.

File: tools/bpf2c/bpf_code_generator.cpp [hunk 1]
```diff
@@ -600,7 +600,23 @@ bpf_code_generator::encode_instructions(const bpf_code_generator::unsafe_string&
                 output.lines.push_back(std::format("{} &= {};", destination, source));
                 break;
             case AluOperations::Lsh:
-                output.lines.push_back(std::format("{} <<= {};", destination, source));
+                if (is64bit) {
+
+                    // Shifts of >= 64 bits on 64-bit values result in undefined behavior so mask off the msb of the
+                    // shift size, i.e. the 'source' in this case.
```
Comment (dthaler) [inline tools/bpf2c/bpf_code_generator.cpp:606]:
```suggestion
                    // shift size, i.e., the 'source' in this case.
```

File: tools/bpf2c/bpf_code_generator.cpp [hunk 2]
```diff
@@ -600,7 +600,23 @@ bpf_code_generator::encode_instructions(const bpf_code_generator::unsafe_string&
...
+                    // Note: The 'duplication' of the following two lines for the 32-bit variant is deliberate as this
+                    // allows the use of the (applicable) native size for the shift_mask variable, thus doing away with
+                    // 'casting' that would otherwise be required. This alwso makes the code more readble.
```
Comment (dthaler) [inline tools/bpf2c/bpf_code_generator.cpp:609]:
```suggestion
                    // 'casting' that would otherwise be required. This also makes the code more readable.
```

File: tools/bpf2c/bpf_code_generator.cpp [hunk 3]
```diff
@@ -600,7 +600,23 @@ bpf_code_generator::encode_instructions(const bpf_code_generator::unsafe_string&
...
+                    uint64_t shift_mask = 0x3F;
+                    output.lines.push_back(std::format("{} <<= ({} & {});", destination, source, shift_mask));
+                } else {
+
+                    // Shifts of >= 32 bits on 32-bit values result in undefined behavior so mask off the msb of the
+                    // shift size, i.e. the 'source' in this case.
```
Comment (dthaler) [inline tools/bpf2c/bpf_code_generator.cpp:615]:
```suggestion
                    // shift size, i.e., the 'source' in this case.
```

File: tools/bpf2c/bpf_code_generator.cpp (hunk 1 above)
Comment (dv-msft) [reply tools/bpf2c/bpf_code_generator.cpp]: fixed.

File: tools/bpf2c/bpf_code_generator.cpp (hunk 2 above)
Comment (dv-msft) [reply tools/bpf2c/bpf_code_generator.cpp]: fixed.

**Comment by dv-msft** [comment]
> Can you format the generated code using format-code.ps1? This should eliminate spurious whitespaces changes.

As discussed, this code was already formatted by that script.  It looks like either the originals were committed without the script formatting pass or the formatting was changed at a date later than the original commit date.

**Review by Alan-Jowett — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Comment by dthaler** [comment]
@dv-msft please resolve conflicts

**Review by dthaler — DISMISSED** [review]

**Review by dthaler — APPROVED** [review]
