### PR TITLE
wait for all events.

### LINKED ISSUE #3361: Workflow failed - driver_ws2019
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/8306397884)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/37613367a007b6340d5e40d0fbb900f6851a2eb2)
Test name - `driver_ws2019`

### PR DESCRIPTION
**Pull request by shankarseal**
## Description

This fixes #3361.
This is related to #3354 which introduced a flaky test, which can fail intermittently like [this](https://github.com/microsoft/ebpf-for-windows/actions/runs/8318926167/job/22761743245).
The new `test_ringbuffer_wraparound` does not wait for all the callbacks to be completed before checking the goal state is reached. The fix was to add a `std::promise` that is satisfied when the expected event count is reached.

## Testing

`test_ringbuffer_wraparound`.

## Documentation

No.

## Installation

No.

### CODE REVIEW

**Review by gtrevi — APPROVED** [review]

**Review by matthewige — APPROVED** [review]

**Comment by dthaler** [comment]
```
    51>D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(1238): error C26495: Variable '_ring_buffer_test_context::event_count' is uninitialized. Always initialize a member variable (type.6). [D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.vcxproj]
```

File: tests/api_test/api_test.cpp [hunk 1]
```diff
@@ -1229,12 +1230,19 @@ TEST_CASE("ioctl_stress", "[stress]")
     bpf_object__close(object);
 }
 
+struct _ring_buffer_test_context
+{
+    uint32_t event_count;
+    uint32_t expected_event_count;
```
Comment (dthaler) [inline tests/api_test/api_test.cpp:1236]:
```suggestion
    uint32_t event_count = 0;
    uint32_t expected_event_count = 0;
```

File: tests/api_test/api_test.cpp [hunk 2]
```diff
@@ -1254,14 +1262,21 @@ TEST_CASE("test_ringbuffer_wraparound", "[stress]")
     REQUIRE(max_iterations % thread_count == 0);
     uint32_t iterations_per_thread = max_iterations / thread_count;
 
+    // Initialize context.
+    context.event_count = 0;
```
Comment (dthaler) [inline tests/api_test/api_test.cpp:1266]:
```suggestion
```

**Review by dthaler — COMMENTED** [review]
I think this is how you fix the analysis failure

**Review by saxena-anurag — APPROVED** [review]

**Review by matthewige — APPROVED** [review]
