### PR TITLE
fix LRU user/kernel behavior tests

### LINKED ISSUE #4962: Flaky test: lru_map_user_vs_kernel_access fails intermittently in CI
## Description

The `lru_map_user_vs_kernel_access` test in `tests/api_test/api_test.cpp` is failing intermittently in CI. This test was added in PR #4893 ("Skip updating lru hotlist for user mode map reads").

## Failure Details

```
-------------------------------------------------------------------------------
lru_map_user_vs_kernel_access
-------------------------------------------------------------------------------
D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(2387): FAILED:
  REQUIRE( bpf_map_lookup_elem(map_fd, &lookup_key, &value) != 0 )
with expansion:
  0 != 0
```

**Location:** `tests/api_test/api_test.cpp` line 2387

## Expected Behavior

The test expects that:
1. User-mode reads via `bpf_map_lookup_elem` should NOT affect LRU order
2. When inserting key 4 into a full 4-entry LRU map, the oldest entry (key 0) should be evicted
3. Looking up key 0 after eviction should fail (return non-zero)

## Actual Behavior

The lookup of key 0 succeeds (returns 0), indicating key 0 was NOT evicted. This suggests either:
- User-mode reads ARE affecting LRU order (contrary to the fix in #4893)
- There's a race condition or timing issue in the LRU hotlist implementation
- The eviction policy is non-deterministic under certain conditions

## Reproduction

Failed in CI run: https://github.com/microsoft/ebpf-for-windows/actions/runs/21500181412/job/61946482515?pr=4923

This failure is blocking unrelated PRs (e.g., #4923 which only adds TLA+ models).

## Related

- PR #4893 - Added this test along with the LRU user-mode read fix
- Issue #4808 - Original issue about LRU behavior

### LINKED ISSUE #4969: Fix lru_map_user_update_affects_lru test flaky assumption about LRU eviction order
## Description

The test \lru_map_user_update_affects_lru\ in \	ests/api_test/api_test.cpp\ is failing intermittently on ARM64 and Server 2025 CI runs. The test assumes deterministic LRU eviction ordering, but the actual implementation uses a hot/cold list algorithm where eviction is non-deterministic.

## Failure Details

**Test**: \lru_map_user_update_affects_lru\
**File**: \	ests/api_test/api_test.cpp:2665\
**Error**:
\\\
REQUIRE( bpf_map_lookup_elem(map_fd, &lookup_key, &value) != 0 )
with expansion: 0 != 0
\\\

The test expects key 1 to be evicted after updating key 0 and inserting key 4, but the LRU implementation may evict any "cold" entry, not necessarily the oldest one.

## Recent Failed Runs
- [Run #21509118884](https://github.com/microsoft/ebpf-for-windows/actions/runs/21509118884) - driver_native_only_arm64
- [Run #21470696783](https://github.com/microsoft/ebpf-for-windows/actions/runs/21470696783) - driver_tests server2025

## Fix

Apply the same pattern as PR #4965 which fixed the similar \lru_map_user_vs_kernel_access\ test:
1. Don't assume a specific key will be evicted
2. Verify that exactly one of the "cold" entries was evicted
3. Verify the recently-used key (0) is still present

## Related
- PR #4965 - Fixes similar issue in \lru_map_user_vs_kernel_access\
- Issue #4889 - Tracks driver_native_only_arm64 failures (now primarily this LRU test)

---
> [!NOTE]
> Copilot: Please fix this test following the same pattern as PR #4965.

### PR DESCRIPTION
**Pull request by mikeagun**
## Description

Updates the LRU user/kernel lookup behavior tests to properly account for LRU behavior.

The original tests added in #4893 were based on incorrect assumptions about LRU behavior.

#4965 / #4970 attempted to fix the tests but tried to use user-mode updates to touch LRU timestamp so failed to resolve the test failures.
- Neither user nor kernel mode updates touch LRU timestamp / add entries to hotlist.
- Only kernel mode lookups affect eviction order.

The new single test `lru_map_user_vs_kernel_access`:
1. Fills an LRU map (of size 100) with 100 entries.
2. Reads 80 of them from a bpf program (updating entry timestamps).
3. Reads 20 of them from userspace (should not affect eviction order).
4. Writes 20 new entries.
5. Scans key range -- the 20 entries read from user-space should be evicted even though they were read most recently.

Fixes #4969, Fixes #4962

## Testing

Replaces 2 flaky tests that didn't validate the behavior with 1 new test that validates the intended behavior.

## Documentation

Updates LRU algorithm description in `ebpf_maps.c` to describe when entry timestamps are / are not updated.

## Installation

N/A

### CODE REVIEW

File: tests/api_test/api_test.cpp [hunk 1]
```diff
@@ -2357,59 +2357,120 @@ TEST_CASE("ebpf_pinned_path_apis", "[ebpf_api]")
...
+    bpf_test_run_opts test_run_opts = {0};
+    test_run_opts.ctx_in = ctx;
+    test_run_opts.ctx_size_in = sizeof(*ctx);
+    test_run_opts.ctx_out = ctx;
+    test_run_opts.ctx_size_out = sizeof(*ctx);
+    test_run_opts.repeat = 1;
+
+    int result = bpf_prog_test_run_opts(program_fd, &test_run_opts);
+    REQUIRE(result == 0);
+    REQUIRE((uint32_t)test_run_opts.retval >= 0);              // Should find all 80 keys.
```
[the remark this answers is not in the document]
Comment (mikeagun) [reply tests/api_test/api_test.cpp]: I fixed it to cast to `int32_t` so if there is an error returned from program it shows as signed.

File: tests/sample/lru_map_test.c [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+SEC("bind")
+bind_action_t
+lru_lookup_program(bind_md_t* context)
+{
+    // Look up keys in LRU map starting from context->process_id (start key).
+    uint32_t key = (uint32_t)context->process_id;
+    uint64_t num_keys = (uint64_t)context->socket_address_length;
+    if (num_keys >= 250) { // Limit for verification.
+        return (bind_action_t)-1;
```
[the remark this answers is not in the document]
Comment (mikeagun) [reply tests/sample/lru_map_test.c]: The test code interprets the return value as signed for error checking, whereas returning zero means there were no failures but we didn't find any of the keys.

File: tests/sample/lru_map_test.c [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+} lru_map SEC(".maps");
+
+SEC("bind")
+bind_action_t
+lru_lookup_program(bind_md_t* context)
+{
+    // Look up keys in LRU map starting from context->process_id (start key).
+    uint32_t key = (uint32_t)context->process_id;
+    uint64_t num_keys = (uint64_t)context->socket_address_length;
+    if (num_keys >= 250) { // Limit for verification.
```
[the remark this answers is not in the document]
Comment (mikeagun) [reply tests/sample/lru_map_test.c]: I had verifier failures with 254/255 - I updated the limit to 253 and added a comment.

**Comment by mikeagun** [comment]
Making 1 change - disabled auto-merge.

Edit: change completed -- I'll re-enable auto-merge after CICD completes.

File: tests/api_test/api_test.cpp [hunk 4]
```diff
@@ -2357,59 +2357,101 @@ TEST_CASE("ebpf_pinned_path_apis", "[ebpf_api]")
...
-    uint32_t key_count = 0;
-    for (uint32_t i = 1; i < max_entries; i++) {
+    // Verify evictions: user-mode accessed keys (0-19) should be evicted,
+    // kernel-mode accessed keys (20-99) should survive.
+    for (uint32_t i = 0; i < max_entries; i++) {
         uint32_t value = 0;
-        if (bpf_map_lookup_elem(map_fd, &i, &value) == 0) {
-            key_count++;
-            REQUIRE(value == (100 + i));
+        bool found = (bpf_map_lookup_elem(map_fd, &i, &value) == 0);
```
Comment (shankarseal) [inline tests/api_test/api_test.cpp]: consider batch lookup - saves on the loop.

Comment (mikeagun) [reply tests/api_test/api_test.cpp]: It seems in this case that wouldn't save much code because then we would also need to create the vectors of keys+values.

Batch lookups would also mean less granular output in case of a failure (binary pass/fail instead of counts for each of the key groups).

File: tests/api_test/api_test.cpp [hunk 5]
```diff
@@ -2357,59 +2357,119 @@ TEST_CASE("ebpf_pinned_path_apis", "[ebpf_api]")
...
+    REQUIRE(lru_map != nullptr);
+    map_fd = bpf_map__fd(lru_map);
     REQUIRE(map_fd > 0);
 
-    // Populate map with 4 entries (keys 0-3, values 100-103).
+    // Fill map completely (keys 0-99).
     for (uint32_t i = 0; i < max_entries; i++) {
-        uint32_t value = 100 + i;
+        uint32_t value = 1000 + i;
         REQUIRE(bpf_map_update_elem(map_fd, &i, &value, BPF_ANY) == 0);
```
Comment (lakshk98) [inline tests/api_test/api_test.cpp:2414]: would 99 be the lru entry after filling the map? That would mean even without kernel mode updating entries, first 20 would get evicted. Should we get kernel mode to update first 20 entries instead ?

Comment (mikeagun) [reply tests/api_test/api_test.cpp:2414]: That is a good call.

That shouldn't make a difference (entries are not inserted into hotlist on update), but swapping the order seems to have uncovered a possible bug.

I'm still investigating the root cause of the now failing test.

Comment (mikeagun) [reply tests/api_test/api_test.cpp:2414]: Actually, because of how the per-cpu hot lists work, the test was correct before swapping the order, and incorrect after swapping the order.

My earlier understanding was wrong -- initializing entries does insert them into the hot list for the current partition (cpu), so by just swapping the key order the test becomes non-deterministic.
- If the bpf program touches the key from the same cpu it was initialized from, the timestamp **will not** be updated because it is already in the hot list.
  - This breaks the test because the kernel mode reads will not actually update the timestamp of all the entries it reads.
- If the bpf program touches the key from a different cpu, the test will succeed because the timestamps will have been updated.

To ensure the bpf program actually updates the timestamps, we need to read enough keys first to force a generation rollover.

I updated the test to:
1. Fill the map.
2. **Read the user-mode keys from kernel mode to force a generation rollover**.
3. Read the kernel-mode keys (will update timestamp because of the previous rollover).
4. Read the kernel-mode keys (will not update timestamp).
5. Scan and validate the keys in the map.

Comment (mikeagun) [reply tests/api_test/api_test.cpp:2414]: Actually, depending on CPU scheduling the test can still be non-deterministic as above depending on how exactly the reads get scheduled.

I'm updating the test to pin everything to cpu zero for deterministic hot list behavior.

Comment (mikeagun) [reply tests/api_test/api_test.cpp:2414]: I've updated the test to pin both the test thread and the bpf program to cpu zero so they are deterministically in the same LRU partition -- this resolves the nondeterminism introduced by flipping the key ranges around.

File: libs/execution_context/ebpf_maps.c [hunk 6]
```diff
@@ -63,10 +63,24 @@ typedef struct _ebpf_core_object_map
...
+ *   - If the entry is in the cold list: Update generation to current, update timestamp, move to hot list.
+ *   - If the entry is already in the hot list: No changes (generation and timestamp remain unchanged).
+ *   - If the entry is uninitialized in this partition: Initialize with current generation and timestamp, add to hot
+ * list.
+ * - User-mode accesses (from user-space applications, without EBPF_MAP_FLAG_HELPER):
+ *   - Do NOT update the entry's generation or timestamp.
+ *   - Do NOT move the entry between lists.
+ *   - This allows diagnostic tools to enumerate LRU maps without polluting the cache.
+ *
+ * When the hot list reaches max_entries/EBPF_LRU_GENERATION_COUNT, the hot list is merged into the cold list,
```
Comment (lakshk98) [inline libs/execution_context/ebpf_maps.c]: should this be max_entries/EBPF_LRU_GENERATION_COUNT*partition_count?

Comment (mikeagun) [reply libs/execution_context/ebpf_maps.c]: Updated the comment

**Review by Alan-Jowett — APPROVED** [review]
