### PR TITLE
Fix ring buffer test subscriber logic.

### LINKED ISSUE #1287: Ring buffer test logic frees already freed ring buffer causing UM crash
`ring_buffer_test_event_handler` can result in `ring_buffer__free` to be invoked on an already freed ring buffer causing a crash with the followng callstack:

```
EbpfApi!std::vector<_ebpf_ring_buffer_subscription *,std::allocator<_ebpf_ring_buffer_subscription *> >::begin
EbpfApi!ring_buffer__free
socket_tests!_ring_buffer_test_event_context::~_ring_buffer_test_event_context
socket_tests!_ring_buffer_test_event_context::`scalar deleting destructor'
socket_tests!ring_buffer_test_event_handler
EbpfApi!_ebpf_ring_buffer_map_async_query_completion
EbpfApi!`initialize_async_ioctl_operation'::`2'::<lambda_1>::operator()
EbpfApi!_Closure_wrapper_2994ade3_1::<lambda_invoker_cdecl>
ntdll!TppExecuteWaitCallback
ntdll!TppWorkerThread
kernel32!BaseThreadInitThunk
ntdll!RtlUserThreadStart
```

### PR DESCRIPTION
**Pull request by shankarseal**
## Description

Fixes #1287 .

There was a bug in ring buffer test subscriber logic that caused it to call ebpf_ring__free on an already freed ring buffer. This causes api_test and socket_tests in driver test CICD to crash,.

The fix is to make sure ebpf_ring__free is called only once and delete test subscription object once the final callback arrives from eBPF.

Other changes include adding some trace statements in ring buffer API code and change some tracing macro.

## Testing

driver test.

## Documentation

N/A

### CODE REVIEW

File: tests/libs/common/common_tests.cpp [hunk 1]
```diff
@@ -115,21 +115,21 @@ ring_buffer_test_event_handler(_In_ void* ctx, _In_opt_ void* data, size_t size)
...
     ring_buffer_test_event_context_t* event_context = reinterpret_cast<ring_buffer_test_event_context_t*>(ctx);
 
-    if (event_context->canceled) {
-        // Ring buffer subscription is canceled.
-        // The test handler expects this callback due to unsubscribe call.
+    if ((data == nullptr) || (size == 0)) {
+        // eBPF ring buffer will invoke this callback with NULL data indicating the subscription is canceled.
         // Free the callback context and return error so that no further callback is made.
         delete event_context;
-        return -1;
```
Comment (dthaler) [inline tests/libs/common/common_tests.cpp:123]: Line 120 says "return error" but this is changed to return success, is it not?
I suspect the comment in line 120 needs to be updated now, as the error case is line 127.

**Review by dthaler — APPROVED** [review]

**Review by dthaler — APPROVED** [review]
