### PR TITLE
Fixes inconsistent behavior in sample_ext prog_test_run

### LINKED ISSUE #4552: Inconsistent behavior for sample_ext prog_test_run/invoke
### Describe the bug

For the sample extension, data_start/data_end can be passed to the bpf program by invoking the sample_ext IOCTL, but cannot be passed to the program via prog_test_run (because `_sample_context_create` does not support data).

### OS information

_No response_

### Steps taken to reproduce bug

1. Invoke sample_ext IOCTL with data (tests\sample\ext\app\sample_ext_app.cpp does this) -- **works**
2. Set data_in and data_size_in in the `bpf_test_run_opts` and invoke with `bpf_prog_test_run_opts` -- **doesn't work**

### Expected behavior

Similar behavior between prog_test_run and invoking the sample extension.

### Actual outcome

Can pass data when invoking the extension, but not with prog_test_run.

### Additional details

`_sample_context_create` should support passing data to the sample_ext bpf program.

### PR DESCRIPTION
**Pull request by houha2**
## Description

Fixes #4552  - See bug description for more context. essentially prog_test_run did not have the same behavior with the sample extension driver as using the ioctl commands when pushing data through data_in/data_out. This worked in the ioctl because we are directly passing the buffers into `DeviceIoControl` while in `_sample_context_create` we bailed out of the function early if `data_in` was populated or if `data_in_size != 0`. 

## Testing
Adds a test that verifies prog_test_run in the sample extension context works with data_in and data_out as well as with a null data_in. 

## Documentation

_Is there any documentation impact for this change?_
No

## Installation

No changes to installation

### CODE REVIEW

**Comment by houha2** [comment]
Failing case in the pipeline passes locally, as seen in the picture below. The changes here are up to date with my local branch minus the bpf2c_tests\expected generated files; as the diff looks like it's just deleting comments

image

File: tests/sample/ext/app/sample_ext_app.cpp [hunk 1]
```diff
@@ -136,6 +136,61 @@ sample_ebpf_ext_test(_In_ const struct bpf_object* object)
...
+    REQUIRE(map != nullptr);
+    map_fd = bpf_map__fd(map);
+    REQUIRE(map_fd > 0);
+
+    for (uint32_t key = 0; key < EBPF_COUNT_OF(strings); key++) {
+        std::copy(strings[key], strings[key] + strlen(strings[key]), map_entry_buffers[key].begin());
+        REQUIRE(bpf_map_update_elem(map_fd, &key, map_entry_buffers[key].data(), EBPF_ANY) == EBPF_SUCCESS);
+    }
+
+    // Get the program fd
```
Comment (dthaler) [inline tests/sample/ext/app/sample_ext_app.cpp]:
```suggestion
    // Get the program fd.
```
nit: be consistent with ending punctuation (line 167 has period, others don't).  Usual convention in this repo is to end in punctuation.  Good to fix throughout (183, 186, 153)

Comment (houha2) [reply tests/sample/ext/app/sample_ext_app.cpp]: Addressed with commit 70da750

**Review by mikeagun — APPROVED** [review]
