### PR TITLE
km stress test hang investigation - Add book-keeping info and traces for post-mortem debugging.

### LINKED ISSUE #3161: Workflow failed - km_mt_stress_tests_restart_extension
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/7458270850)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/a2ece4ba2639851abc476211468c9f06c4a56faf)
Test name - `km_mt_stress_tests_restart_extension`

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

This PR adds some additional book-keeping info and traces to further debug this issue.    This issue is inconsistently seen in CI/CD runs and not repro'd locally.

## Testing

Issue seen in existing test, so no new tests needed.

## Documentation

No doc impact.

## Installation

No Installer Impact.

Fixes #3161

### CODE REVIEW

File: netebpfext/net_ebpf_ext.c [hunk 1]
```diff
@@ -353,18 +351,27 @@ net_ebpf_extension_get_callout_id_for_hook(net_ebpf_extension_hook_id_t hook_id)
...
+            filter_ids[index].state = NET_EBPF_EXT_WFP_FILTER_DELETED;
+            NET_EBPF_EXT_LOG_MESSAGE_UINT64_UINT64(
+                NET_EBPF_EXT_TRACELOG_LEVEL_VERBOSE,
+                NET_EBPF_EXT_TRACELOG_KEYWORD_EXTENSION,
+                "Deleted WFP filter: ",
+                index,
+                filter_ids[index].id);
         }
     }
-    ExFreePool(filter_ids);
```
Comment (Alan-Jowett) [inline netebpfext/net_ebpf_ext.c:367]: When does this get freed?

File: .github/workflows/cicd.yml [hunk 2]
```diff
@@ -530,7 +530,8 @@ jobs:
   # against the kernel mode eBPF sub-system.
   km_mt_stress_tests:
     needs: regular
-    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+    if: github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'merge_group' || github.event_name == 'workflow_dispatch'
```
[the remark this answers is not in the document]
Comment (dv-msft) [reply .github/workflows/cicd.yml:533]: GAH!!! That was for my PR smoke testing! :-P will remove stat.

File: netebpfext/net_ebpf_ext.c (hunk 1 above)
Comment (dv-msft) [reply netebpfext/net_ebpf_ext.c:367]: In the `DEREFERENCE_FILTER_CONTEXT` macro (`net_ebpf_ext.h`)

**Review by shankarseal — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
