### PR TITLE
Fix for failing 'Full fault injection' test.

### LINKED ISSUE #2557: Workflow failed - fault_injection_full
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/5204733810)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/10735e577c676f6adebe04c35de6041bec0823d8)
Test name - `fault_injection_full`

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

Fixes in this PR:
1. Replace the global 'fault injection state' flag with a call to a `usersim` function that returns this state.
2. Fix a post-crash memory leak in test code.

## Testing
CI/CD

## Documentation
No documentation changes needed.

## Installation

No

Fixes #2557

### CODE REVIEW

File: libs/platform/kernel/ebpf_platform_kernel.c [hunk 1]
```diff
@@ -365,3 +365,11 @@ _IRQL_requires_max_(PASSIVE_LEVEL) _Must_inspect_result_ ebpf_result_t
...
     return EBPF_SUCCESS;
 }
+
+BOOLEAN
+usersim_fault_injection_is_enabled(void)
+{
+    // Kernel mode replacement (for call from usersim).
+    // As of now, fault injection is not supported in kernel mode.
+    return FALSE;
+}
```
Comment (dthaler) [inline libs/platform/kernel/ebpf_platform_kernel.c:375]: FYI, this will interfere with my usersim changes, which compiles ebpf_platform_kernel.c (from a separate project) and links with usersim.  I'd recommend putting it into a separate .c file.

Comment (dv-msft) [reply libs/platform/kernel/ebpf_platform_kernel.c]: Fixed.

**Review by Alan-Jowett — DISMISSED** [review]

File: libs/platform/ebpf_platform.c [hunk 2]
```diff
@@ -4,8 +4,6 @@
 #include "ebpf_platform.h"
 #include "ebpf_tracelog.h"
 
-bool ebpf_fuzzing_enabled = false;
```
Comment (saxena-anurag) [inline libs/platform/ebpf_platform.c:7]: nit: why did we remove `ebpf_fuzzing_enabled`?

File: libs/platform/ebpf_platform.h [hunk 3]
```diff
@@ -1076,6 +1074,16 @@ extern "C"
     ebpf_result_t
     ebpf_utf8_string_to_unicode(_In_ const ebpf_utf8_string_t* input, _Outptr_ wchar_t** output);
 
+    /**
+     * @brief Check if fault injection is enabled. (Fault injection
+     *        is not supported in kernel mode.)
```
Comment (dthaler) [inline libs/platform/ebpf_platform.h:1079]:
```suggestion
     *        is not supported in kernel mode.)
     * TODO(#2677): move this prototype to another project.
```

Comment (dthaler) [reply libs/platform/ebpf_platform.h:1079]: Add a reminder to me to clean this up once my later work is done.

File: libs/platform/kernel/ebpf_fault_injection_kernel.c [hunk 4]
```diff
@@ -0,0 +1,12 @@
+// Copyright (c) Microsoft Corporation
+// SPDX-License-Identifier: MIT
+
+#include "ebpf_platform.h"
+
+BOOLEAN
```
Comment (dthaler) [inline libs/platform/kernel/ebpf_fault_injection_kernel.c:6]:
```suggestion
// TODO(#2677): Update this prototype.
BOOLEAN
```

File: libs/platform/unit/platform_unit_test.cpp [hunk 5]
```diff
@@ -96,9 +96,21 @@ class _test_helper
     bool state_initiated = false;
 };
 
+struct ebpf_hash_table_destroyer_t
+{
+    void
+    operator()(_In_opt_ _Post_invalid_ ebpf_hash_table_t* table)
+    {
+        if (table != nullptr) {
```
Comment (dthaler) [inline libs/platform/unit/platform_unit_test.cpp:104]: remove the `if` test.  ebpf_ apis that do frees should always be ok to pass nullptr to, and removing it decreases the number of distinct code paths and hence improves complexity and code coverage.

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]
