### PR TITLE
Remove JIT and interpreter code from NativeOnly builds

### LINKED ISSUE #2030: Disable JIT code when the related build option is specified.
### Describe the feature you'd like supported

Following up on the work done for #1883, JIT code paths should be disabled when the new `DisableJIT` build option is specified on msbuild.

### LINKED ISSUE #2488: redist-package fails to build with VS Community Edition
### Describe the bug

ebpf-for-windows-redist.nuspec.in hard codes file paths and depends on Enterprise edition being installed in a specific path.
Building with Community edition (which GettingStarted.md says should work) thus fails.

### OS information

_No response_

### Steps taken to reproduce bug

Install Community edition of VS instead of Enterprise edition
Try to build ebpf-for-windows

### Expected behavior

Build should succeed

### Actual outcome

Build fails

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by dthaler**
## Description

Remove JIT and interpreter code from NativeOnly builds

Fixes #2030 (security cleanup)
Fixes #2488 (bug)

Also fixes version number typo in GettingStarted.md

## Testing

Updated CI/CD

Note that issue #2281 only updated kernel tests to use sys files, it did not update the user-mode tests in `tests/unit/libbpf_test.cpp` and `tests/end_to_end/end_to_end.cpp`, so in this PR the relevant ones are commented out.  Issue #1121 covers updating the relevant ones to use dlls, and also covers updating port_quota.exe.

## Documentation

Updated docs

### CODE REVIEW

**Review by Alan-Jowett — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]

File: libs/api/libbpf_program.cpp [hunk 1]
```diff
@@ -25,6 +25,7 @@ bpf_load_program_xattr(const struct bpf_load_program_attr* load_attr, char* log_
         return libbpf_err(-EINVAL);
     }
 
+#if !defined(CONFIG_BPF_JIT_DISABLED) && !defined(CONFIG_BPF_INTERPRETER_DISABLED)
```
Comment (saxena-anurag) [inline libs/api/libbpf_program.cpp:28]: nit: why do we want to block this at API layer also if it is already blocked in ebpfcore? Anyone can modify and recompile this dll to override this.

Comment (saxena-anurag) [reply libs/api/libbpf_program.cpp:28]: Will having the checks in user mode block us to test the ebpfcore code where it fails the jit and interpret IOCTL calls for native_only case?

Comment (dthaler) [reply libs/api/libbpf_program.cpp:28]: answer: just reducing footprint.

Comment (dthaler) [reply libs/api/libbpf_program.cpp:28]: > nit: why do we want to block this at API layer also if it is already blocked in ebpfcore? Anyone can modify and recompile this dll to override this.

footprint reduction, and also changes the error return from "invalid value" to the more specific "not supported" meaning.

Comment (dthaler) [reply libs/api/libbpf_program.cpp:28]: > Will having the checks in user mode block us to test the ebpfcore code where it fails the jit and interpret IOCTL calls for native_only case?

The UM unit tests test that code path.

File: tests/end_to_end/end_to_end.cpp [hunk 2]
```diff
@@ -1139,6 +1158,7 @@ DECLARE_CGROUP_SOCK_ADDR_LOAD_TEST(
 DECLARE_CGROUP_SOCK_ADDR_LOAD_TEST(
     SAMPLE_PATH "cgroup_sock_addr", "authorize_recv_accept6", EBPF_ATTACH_TYPE_CGROUP_INET6_RECV_ACCEPT);
 
+#if !defined(CONFIG_BPF_JIT_DISABLED)
```
Comment (saxena-anurag) [inline tests/end_to_end/end_to_end.cpp:1161]: nit: instead of removing these tests from native build, we could possibly use `native_module_helper_t` helper to get an appropriate file name (.sys or .o) based on whether JIT is enabled or disabled.

Comment (dthaler) [reply tests/end_to_end/end_to_end.cpp:1161]: Yes that's what #1121 already covers.

File: libs/api/ebpf_api.cpp [hunk 3]
```diff
@@ -2528,6 +2538,7 @@ _Requires_lock_not_held_(_ebpf_state_mutex) static ebpf_result_t
     EBPF_RETURN_RESULT(result);
 }
 
+#if !defined(CONFIG_BPF_JIT_DISABLED) && !defined(CONFIG_BPF_INTERPRETER_DISABLED)
```
[the remark this answers is not in the document]
Comment (dthaler) [reply libs/api/ebpf_api.cpp:2541]: no.  I think you're saying the `&&` should be `||` and I think you're right

[the remark this answers is not in the document]
Comment (dthaler) [reply libs/api/ebpf_api.cpp]: Done

**Review by Alan-Jowett — APPROVED** [review]

File: libs/execution_context/ebpf_protocol.h [hunk 4]
```diff
@@ -9,11 +9,17 @@
 
 typedef enum _ebpf_operation_id
 {
+#if !defined(CONFIG_BPF_JIT_DISABLED)
```
Comment (saxena-anurag) [inline libs/execution_context/ebpf_protocol.h:12]: nit: removing the operation ids from the middle will cause the value of the other ids to change. So the same operation ID will have different value in native-only vs. regular build. Not sure if this can cause any issues.

**Review by saxena-anurag — APPROVED** [review]

File: libs/execution_context/ebpf_protocol.h (hunk 4 above)
Comment (dthaler) [reply libs/execution_context/ebpf_protocol.h:12]: Since the IDs are not used in apps (they should be calling libbpf) it's ok to have breaking changes in my view
