### PR TITLE
Fix native module unit tests for low memory simulation scenario

### LINKED ISSUE #2024: OOM failure in ebpf_native_load causes native module to not unload - version 1
Asserting stack:
```
0:000> k100
 # Child-SP          RetAddr               Call Site
00 000000b0`8d8f0df8 00007ff9`085b3733     ntdll!ZwWaitForMultipleObjects+0x14
01 000000b0`8d8f0e00 00007ff9`085b364e     KERNELBASE!WaitForMultipleObjectsEx+0xd3
02 000000b0`8d8f10e0 00007ff9`0a5c39f6     KERNELBASE!WaitForMultipleObjects+0xe
03 000000b0`8d8f1120 00007ff9`0a5c34aa     kernel32!WerpLaunchAeDebug+0x38c6
04 000000b0`8d8f1230 00007ff9`0864d0ed     kernel32!WerpLaunchAeDebug+0x337a
05 000000b0`8d8f1270 00007ff9`0b21a33b     KERNELBASE!lstrcpyn+0x223ad
06 000000b0`8d8f1390 00007ff9`0b2002e7     ntdll!strncpy+0x266b
07 000000b0`8d8f13d0 00007ff9`0b21619f     ntdll!_C_specific_handler+0x97
08 000000b0`8d8f1440 00007ff9`0b1933c8     ntdll!_chkstk+0xff
09 000000b0`8d8f1470 00007ff9`0b1baacf     ntdll!RtlImageRvaToSection+0x3f8
0a 000000b0`8d8f1bd0 00007ff9`085d3a1c     ntdll!RtlRaiseException+0x16f
*** WARNING: Unable to verify checksum for unit_tests.exe
0b 000000b0`8d8f2a70 00007ff7`70410e05     KERNELBASE!RaiseException+0x6c
0c 000000b0`8d8f2b50 00007ff8`319e6e31     unit_tests!_wer_report_test::_terminate_hook+0x25 [E:\ebpf-for-windows\tests\libs\util\wer_report.hpp @ 92] 
0d 000000b0`8d8f2b80 00007ff8`319e5610     ucrtbased!VCrtDbgReportW+0x841
0e 000000b0`8d8facc0 00007ff8`319d2fa1     ucrtbased!CrtDbgReportW+0x60
0f 000000b0`8d8fad20 00007ff8`319d3153     ucrtbased!_threadid+0x51
10 000000b0`8d8fad70 00007ff8`319eae2d     ucrtbased!_threadid+0x203
11 000000b0`8d8fadd0 00007ff8`319f0c6f     ucrtbased!abort+0x1d
12 000000b0`8d8fae10 00007ff8`319eeba1     ucrtbased!get_wide_winmain_command_line+0x21bf
13 000000b0`8d8fae70 00007ff8`319f18af     ucrtbased!get_wide_winmain_command_line+0xf1
14 000000b0`8d8faeb0 00007ff7`7059c406     ucrtbased!wassert+0x2f
15 000000b0`8d8faee0 00007ff7`705a41fa     unit_tests!_nmr::remove<std::map<void *,_nmr::client_registration,std::less<void *>,std::allocator<std::pair<void * const,_nmr::client_registration> > > >+0x1d6 [E:\ebpf-for-windows\libs\platform\user\nmr_impl.cpp @ 306] 
16 000000b0`8d8fb030 00007ff7`705856ad     unit_tests!_nmr::wait_for_deregister_client+0x2a [E:\ebpf-for-windows\libs\platform\user\nmr_impl.cpp @ 73] 
17 000000b0`8d8fb060 00007ff7`70568695     unit_tests!NmrWaitForClientDeregisterComplete+0x2d [E:\ebpf-for-windows\libs\platform\user\nmr_um.cpp @ 100] 
18 000000b0`8d8fb0b0 00007ff7`703a6e26     unit_tests!ebpf_extension_unload+0x125 [E:\ebpf-for-windows\libs\platform\ebpf_extension.c @ 335] 
19 000000b0`8d8fb2c0 00007ff7`7039ac58     unit_tests!_unload_all_native_modules+0xe6 [E:\ebpf-for-windows\tests\end_to_end\test_helper.cpp @ 286] 
1a 000000b0`8d8fb4a0 00007ff7`70769abc     unit_tests!_test_helper_end_to_end::~_test_helper_end_to_end+0x3f8 [E:\ebpf-for-windows\tests\end_to_end\test_helper.cpp @ 671] 
1b 000000b0`8d8fb7e0 00007ff9`05b71030     unit_tests!`CATCH2_INTERNAL_TEST_163'::`1'::dtor$0+0x1c
1c 000000b0`8d8fb820 00007ff9`05b742a7     VCRUNTIME140_1D+0x1030
1d 000000b0`8d8fb850 00007ff9`05b7668b     VCRUNTIME140_1D!_NLG_Return2+0x3157
1e 000000b0`8d8fb960 00007ff9`05b72cd2     VCRUNTIME140_1D!_NLG_Return2+0x553b
1f 000000b0`8d8fb9a0 00007ff9`05b72f57     VCRUNTIME140_1D!_NLG_Return2+0x1b82
20 000000b0`8d8fba70 00007ff9`05b76ddb     VCRUNTIME140_1D!_NLG_Return2+0x1e07
21 000000b0`8d8fbad0 00007ff7`705cdbe0     VCRUNTIME140_1D!_CxxFrameHandler4+0xfb
22 000000b0`8d8fbb60 00007ff9`0b21621f     unit_tests!__GSHandlerCheck_EH4+0x90 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlereh4.cpp @ 73] 
23 000000b0`8d8fbbb0 00007ff9`0b1938d4     ntdll!_chkstk+0x17f
24 000000b0`8d8fbbe0 00007ff9`05b76a5f     ntdll!RtlUnwindEx+0x274
25 000000b0`8d8fc310 00007ff9`05b71c1e     VCRUNTIME140_1D!_NLG_Return2+0x590f
26 000000b0`8d8fc410 00007ff9`05b7218b     VCRUNTIME140_1D!_NLG_Return2+0xace
27 000000b0`8d8fc4b0 00007ff9`05b72ec5     VCRUNTIME140_1D!_NLG_Return2+0x103b
28 000000b0`8d8fc690 00007ff9`05b72f57     VCRUNTIME140_1D!_NLG_Return2+0x1d75
29 000000b0`8d8fc760 00007ff9`05b76ddb     VCRUNTIME140_1D!_NLG_Return2+0x1e07
2a 000000b0`8d8fc7c0 00007ff7`705cdbe0     VCRUNTIME140_1D!_CxxFrameHandler4+0xfb
2b 000000b0`8d8fc850 00007ff9`0b21619f     unit_tests!__GSHandlerCheck_EH4+0x90 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlereh4.cpp @ 73] 
2c 000000b0`8d8fc8a0 00007ff9`0b1933c8     ntdll!_chkstk+0xff
2d 000000b0`8d8fc8d0 00007ff9`0b1baacf     ntdll!RtlImageRvaToSection+0x3f8
2e 000000b0`8d8fd030 00007ff9`085d3a1c     ntdll!RtlRaiseException+0x16f
2f 000000b0`8d8fded0 00007ff9`039ab760     KERNELBASE!RaiseException+0x6c
30 000000b0`8d8fdfb0 00007ff7`7041fbe8     VCRUNTIME140D!CxxThrowException+0x120
31 000000b0`8d8fe040 00007ff7`7041943e     unit_tests!Catch::throw_test_failure_exception+0x28 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_test_failure_exception.cpp @ 21] 
32 000000b0`8d8fe080 00007ff7`70320035     unit_tests!Catch::AssertionHandler::complete+0x4e [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_assertion_handler.cpp @ 53] 
33 000000b0`8d8fe0c0 00007ff7`7043b7f2     unit_tests!CATCH2_INTERNAL_TEST_163+0x745 [E:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp @ 2464] 
34 000000b0`8d8fe730 00007ff7`70429351     unit_tests!Catch::TestInvokerAsFunction::invoke+0x12 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_test_case_registry_impl.cpp @ 150] 
35 000000b0`8d8fe760 00007ff7`704293a7     unit_tests!Catch::TestCaseHandle::invoke+0x21 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_test_case_info.hpp @ 116] 
36 000000b0`8d8fe790 00007ff7`70429f30     unit_tests!Catch::RunContext::invokeActiveTestCase+0x47 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_run_context.cpp @ 535] 
37 000000b0`8d8fe7e0 00007ff7`7042a37c     unit_tests!Catch::RunContext::runCurrentTest+0x250 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_run_context.cpp @ 500] 
38 000000b0`8d8feb60 00007ff7`707321d3     unit_tests!Catch::RunContext::runTest+0x2bc [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_run_context.cpp @ 236] 
39 000000b0`8d8ff030 00007ff7`707331b9     unit_tests!Catch::`anonymous namespace'::TestGroup::execute+0xf3 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.cpp @ 110] 
3a 000000b0`8d8ff1b0 00007ff7`70732d40     unit_tests!Catch::Session::runInternal+0x409 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.cpp @ 335] 
3b 000000b0`8d8ff650 00007ff7`705d11b2     unit_tests!Catch::Session::run+0x50 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.cpp @ 263] 
3c 000000b0`8d8ff690 00007ff7`705d1221     unit_tests!Catch::Session::run<char>+0x52 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.hpp @ 41] 
3d 000000b0`8d8ff6d0 00007ff7`705ce119     unit_tests!main+0x61 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_main.cpp @ 36] 
3e 000000b0`8d8ff8f0 00007ff7`705ce06e     unit_tests!invoke_main+0x39 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 79] 
3f 000000b0`8d8ff940 00007ff7`705cdf2e     unit_tests!__scrt_common_main_seh+0x12e [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
40 000000b0`8d8ff9b0 00007ff7`705ce18e     unit_tests!__scrt_common_main+0xe [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
41 000000b0`8d8ff9e0 00007ff9`0a56163d     unit_tests!mainCRTStartup+0xe [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 17] 
42 000000b0`8d8ffa10 00007ff9`0b1bd6f8     kernel32!BaseThreadInitThunk+0x1d
43 000000b0`8d8ffa40 00000000`00000000     ntdll!RtlUserThreadStart+0x28
```

Failed allocation:
```
0:000> dx -r1 (*((unit_tests!std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > *)0x1f4ffc189a0))
(*((unit_tests!std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > *)0x1f4ffc189a0))                 : { size=16 } [Type: std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >]
    [<Raw View>]     [Type: std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >]
    [capacity]       : 19
    [allocator]      : allocator [Type: std::_Compressed_pair<std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::_Vector_val<std::_Simple_types<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >,1>]
    [0]              : "_ebpf_low_memory_test::fail_stack_allocation + 97 E:\ebpf-for-windows\libs\platform\user\ebpf_low_memory_test.cpp 76" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [1]              : "ebpf_allocate + 106 E:\ebpf-for-windows\libs\platform\user\ebpf_platform_user.cpp 376" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [2]              : "ebpf_allocate_preemptible_work_item + 38 E:\ebpf-for-windows\libs\platform\user\ebpf_platform_user.cpp 898" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [3]              : "ebpf_native_load + 428 E:\ebpf-for-windows\libs\execution_context\ebpf_native.c 1174" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [4]              : "_ebpf_core_protocol_load_native_module + 428 E:\ebpf-for-windows\libs\execution_context\ebpf_core.c 586" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [5]              : "ebpf_core_invoke_protocol_handler + 691 E:\ebpf-for-windows\libs\execution_context\ebpf_core.c 2324" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [6]              : "GlueDeviceIoControl + 693 E:\ebpf-for-windows\tests\end_to_end\test_helper.cpp 443" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [7]              : "std::invoke<int (__cdecl*&)(void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *),void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *> + 161 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\type_traits 1587" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [8]              : "std::_Invoker_ret<int>::_Call<int (__cdecl*&)(void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *),void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *> + 115 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\functional 674" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [9]              : "std::_Func_impl_no_alloc<int (__cdecl*)(void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *),int,void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *>::_Do_call + 269 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\functional 834" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [10]             : "std::_Func_class<int,void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *>::operator() + 353 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\functional 875" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [11]             : "Platform::DeviceIoControl + 115 E:\ebpf-for-windows\libs\thunk\mock\mock.cpp 32" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [12]             : "invoke_ioctl<std::vector<unsigned char,std::allocator<unsigned char> >,_ebpf_operation_load_native_module_reply> + 207 E:\ebpf-for-windows\libs\api_common\device_helper.hpp 99" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [13]             : "test_ioctl_load_native_module + 359 E:\ebpf-for-windows\tests\libs\util\ioctl_helper.cpp 47" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [14]             : "CATCH2_INTERNAL_TEST_163 + 1715 E:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp 2464" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [15]             : "Catch::TestInvokerAsFunction::invoke + 18 E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_test_case_registry_impl.cpp 150" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
```

### LINKED ISSUE #2025: OOM failure in ebpf_native_load causes native module to not unload - version 2
Asserting stack:
```
0:000> k100
 # Child-SP          RetAddr               Call Site
00 000000dd`eb730d78 00007ff9`085b3733     ntdll!ZwWaitForMultipleObjects+0x14
01 000000dd`eb730d80 00007ff9`085b364e     KERNELBASE!WaitForMultipleObjectsEx+0xd3
02 000000dd`eb731060 00007ff9`0a5c39f6     KERNELBASE!WaitForMultipleObjects+0xe
03 000000dd`eb7310a0 00007ff9`0a5c34aa     kernel32!WerpLaunchAeDebug+0x38c6
04 000000dd`eb7311b0 00007ff9`0864d0ed     kernel32!WerpLaunchAeDebug+0x337a
05 000000dd`eb7311f0 00007ff9`0b21a33b     KERNELBASE!lstrcpyn+0x223ad
06 000000dd`eb731310 00007ff9`0b2002e7     ntdll!strncpy+0x266b
07 000000dd`eb731350 00007ff9`0b21619f     ntdll!_C_specific_handler+0x97
08 000000dd`eb7313c0 00007ff9`0b1933c8     ntdll!_chkstk+0xff
09 000000dd`eb7313f0 00007ff9`0b1baacf     ntdll!RtlImageRvaToSection+0x3f8
0a 000000dd`eb731b50 00007ff9`085d3a1c     ntdll!RtlRaiseException+0x16f
0b 000000dd`eb7329f0 00007ff7`70410e05     KERNELBASE!RaiseException+0x6c
0c 000000dd`eb732ad0 00007ff8`319e6e31     unit_tests!_wer_report_test::_terminate_hook+0x25 [E:\ebpf-for-windows\tests\libs\util\wer_report.hpp @ 92] 
0d 000000dd`eb732b00 00007ff8`319e5610     ucrtbased!VCrtDbgReportW+0x841
0e 000000dd`eb73ac40 00007ff8`319d2fa1     ucrtbased!CrtDbgReportW+0x60
0f 000000dd`eb73aca0 00007ff8`319d3153     ucrtbased!_threadid+0x51
10 000000dd`eb73acf0 00007ff8`319eae2d     ucrtbased!_threadid+0x203
11 000000dd`eb73ad50 00007ff8`319f0c6f     ucrtbased!abort+0x1d
12 000000dd`eb73ad90 00007ff8`319eeba1     ucrtbased!get_wide_winmain_command_line+0x21bf
13 000000dd`eb73adf0 00007ff8`319f18af     ucrtbased!get_wide_winmain_command_line+0xf1
14 000000dd`eb73ae30 00007ff7`7059c406     ucrtbased!wassert+0x2f
15 000000dd`eb73ae60 00007ff7`705a41fa     unit_tests!_nmr::remove<std::map<void *,_nmr::client_registration,std::less<void *>,std::allocator<std::pair<void * const,_nmr::client_registration> > > >+0x1d6 [E:\ebpf-for-windows\libs\platform\user\nmr_impl.cpp @ 306] 
16 000000dd`eb73afb0 00007ff7`705856ad     unit_tests!_nmr::wait_for_deregister_client+0x2a [E:\ebpf-for-windows\libs\platform\user\nmr_impl.cpp @ 73] 
17 000000dd`eb73afe0 00007ff7`70568695     unit_tests!NmrWaitForClientDeregisterComplete+0x2d [E:\ebpf-for-windows\libs\platform\user\nmr_um.cpp @ 100] 
18 000000dd`eb73b030 00007ff7`703a6e26     unit_tests!ebpf_extension_unload+0x125 [E:\ebpf-for-windows\libs\platform\ebpf_extension.c @ 335] 
19 000000dd`eb73b240 00007ff7`7039ac58     unit_tests!_unload_all_native_modules+0xe6 [E:\ebpf-for-windows\tests\end_to_end\test_helper.cpp @ 286] 
1a 000000dd`eb73b420 00007ff7`70769abc     unit_tests!_test_helper_end_to_end::~_test_helper_end_to_end+0x3f8 [E:\ebpf-for-windows\tests\end_to_end\test_helper.cpp @ 671] 
1b 000000dd`eb73b760 00007ff9`05b71030     unit_tests!`CATCH2_INTERNAL_TEST_163'::`1'::dtor$0+0x1c
1c 000000dd`eb73b7a0 00007ff9`05b742a7     VCRUNTIME140_1D+0x1030
1d 000000dd`eb73b7d0 00007ff9`05b7668b     VCRUNTIME140_1D!_NLG_Return2+0x3157
1e 000000dd`eb73b8e0 00007ff9`05b72cd2     VCRUNTIME140_1D!_NLG_Return2+0x553b
1f 000000dd`eb73b920 00007ff9`05b72f57     VCRUNTIME140_1D!_NLG_Return2+0x1b82
20 000000dd`eb73b9f0 00007ff9`05b76ddb     VCRUNTIME140_1D!_NLG_Return2+0x1e07
21 000000dd`eb73ba50 00007ff7`705cdbe0     VCRUNTIME140_1D!_CxxFrameHandler4+0xfb
22 000000dd`eb73bae0 00007ff9`0b21621f     unit_tests!__GSHandlerCheck_EH4+0x90 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlereh4.cpp @ 73] 
23 000000dd`eb73bb30 00007ff9`0b1938d4     ntdll!_chkstk+0x17f
24 000000dd`eb73bb60 00007ff9`05b76a5f     ntdll!RtlUnwindEx+0x274
25 000000dd`eb73c290 00007ff9`05b71c1e     VCRUNTIME140_1D!_NLG_Return2+0x590f
26 000000dd`eb73c390 00007ff9`05b7218b     VCRUNTIME140_1D!_NLG_Return2+0xace
27 000000dd`eb73c430 00007ff9`05b72ec5     VCRUNTIME140_1D!_NLG_Return2+0x103b
28 000000dd`eb73c610 00007ff9`05b72f57     VCRUNTIME140_1D!_NLG_Return2+0x1d75
29 000000dd`eb73c6e0 00007ff9`05b76ddb     VCRUNTIME140_1D!_NLG_Return2+0x1e07
2a 000000dd`eb73c740 00007ff7`705cdbe0     VCRUNTIME140_1D!_CxxFrameHandler4+0xfb
2b 000000dd`eb73c7d0 00007ff9`0b21619f     unit_tests!__GSHandlerCheck_EH4+0x90 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlereh4.cpp @ 73] 
2c 000000dd`eb73c820 00007ff9`0b1933c8     ntdll!_chkstk+0xff
2d 000000dd`eb73c850 00007ff9`0b1baacf     ntdll!RtlImageRvaToSection+0x3f8
2e 000000dd`eb73cfb0 00007ff9`085d3a1c     ntdll!RtlRaiseException+0x16f
2f 000000dd`eb73de50 00007ff9`039ab760     KERNELBASE!RaiseException+0x6c
30 000000dd`eb73df30 00007ff7`7041fbe8     VCRUNTIME140D!CxxThrowException+0x120
31 000000dd`eb73dfc0 00007ff7`7041943e     unit_tests!Catch::throw_test_failure_exception+0x28 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_test_failure_exception.cpp @ 21] 
32 000000dd`eb73e000 00007ff7`70320035     unit_tests!Catch::AssertionHandler::complete+0x4e [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_assertion_handler.cpp @ 53] 
33 000000dd`eb73e040 00007ff7`7043b7f2     unit_tests!CATCH2_INTERNAL_TEST_163+0x745 [E:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp @ 2464] 
34 000000dd`eb73e6b0 00007ff7`70429351     unit_tests!Catch::TestInvokerAsFunction::invoke+0x12 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_test_case_registry_impl.cpp @ 150] 
35 000000dd`eb73e6e0 00007ff7`704293a7     unit_tests!Catch::TestCaseHandle::invoke+0x21 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_test_case_info.hpp @ 116] 
36 000000dd`eb73e710 00007ff7`70429f30     unit_tests!Catch::RunContext::invokeActiveTestCase+0x47 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_run_context.cpp @ 535] 
37 000000dd`eb73e760 00007ff7`7042a37c     unit_tests!Catch::RunContext::runCurrentTest+0x250 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_run_context.cpp @ 500] 
38 000000dd`eb73eae0 00007ff7`707321d3     unit_tests!Catch::RunContext::runTest+0x2bc [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_run_context.cpp @ 236] 
39 000000dd`eb73efb0 00007ff7`707331b9     unit_tests!Catch::`anonymous namespace'::TestGroup::execute+0xf3 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.cpp @ 110] 
3a 000000dd`eb73f130 00007ff7`70732d40     unit_tests!Catch::Session::runInternal+0x409 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.cpp @ 335] 
3b 000000dd`eb73f5d0 00007ff7`705d11b2     unit_tests!Catch::Session::run+0x50 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.cpp @ 263] 
3c 000000dd`eb73f610 00007ff7`705d1221     unit_tests!Catch::Session::run<char>+0x52 [E:\ebpf-for-windows\external\Catch2\src\catch2\catch_session.hpp @ 41] 
3d 000000dd`eb73f650 00007ff7`705ce119     unit_tests!main+0x61 [E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_main.cpp @ 36] 
3e 000000dd`eb73f870 00007ff7`705ce06e     unit_tests!invoke_main+0x39 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 79] 
3f 000000dd`eb73f8c0 00007ff7`705cdf2e     unit_tests!__scrt_common_main_seh+0x12e [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
40 000000dd`eb73f930 00007ff7`705ce18e     unit_tests!__scrt_common_main+0xe [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
41 000000dd`eb73f960 00007ff9`0a56163d     unit_tests!mainCRTStartup+0xe [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 17] 
42 000000dd`eb73f990 00007ff9`0b1bd6f8     kernel32!BaseThreadInitThunk+0x1d
43 000000dd`eb73f9c0 00000000`00000000     ntdll!RtlUserThreadStart+0x28
```

Failed allocation:
```
0:000> dx -r1 (*((unit_tests!std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > *)0x1ecef67b820))
(*((unit_tests!std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > *)0x1ecef67b820))                 : { size=16 } [Type: std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >]
    [<Raw View>]     [Type: std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >]
    [capacity]       : 19
    [allocator]      : allocator [Type: std::_Compressed_pair<std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::_Vector_val<std::_Simple_types<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >,1>]
    [0]              : "_ebpf_low_memory_test::fail_stack_allocation + 97 E:\ebpf-for-windows\libs\platform\user\ebpf_low_memory_test.cpp 76" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [1]              : "ebpf_allocate + 106 E:\ebpf-for-windows\libs\platform\user\ebpf_platform_user.cpp 376" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [2]              : "ebpf_native_load + 337 E:\ebpf-for-windows\libs\execution_context\ebpf_native.c 1167" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [3]              : "_ebpf_core_protocol_load_native_module + 428 E:\ebpf-for-windows\libs\execution_context\ebpf_core.c 586" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [4]              : "ebpf_core_invoke_protocol_handler + 691 E:\ebpf-for-windows\libs\execution_context\ebpf_core.c 2324" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [5]              : "GlueDeviceIoControl + 693 E:\ebpf-for-windows\tests\end_to_end\test_helper.cpp 443" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [6]              : "std::invoke<int (__cdecl*&)(void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *),void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *> + 161 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\type_traits 1587" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [7]              : "std::_Invoker_ret<int>::_Call<int (__cdecl*&)(void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *),void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *> + 115 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\functional 674" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [8]              : "std::_Func_impl_no_alloc<int (__cdecl*)(void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *),int,void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *>::_Do_call + 269 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\functional 834" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [9]              : "std::_Func_class<int,void *,unsigned long,void *,unsigned long,void *,unsigned long,unsigned long *,_OVERLAPPED *>::operator() + 353 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\functional 875" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [10]             : "Platform::DeviceIoControl + 115 E:\ebpf-for-windows\libs\thunk\mock\mock.cpp 32" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [11]             : "invoke_ioctl<std::vector<unsigned char,std::allocator<unsigned char> >,_ebpf_operation_load_native_module_reply> + 207 E:\ebpf-for-windows\libs\api_common\device_helper.hpp 99" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [12]             : "test_ioctl_load_native_module + 359 E:\ebpf-for-windows\tests\libs\util\ioctl_helper.cpp 47" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [13]             : "CATCH2_INTERNAL_TEST_163 + 1715 E:\ebpf-for-windows\tests\end_to_end\end_to_end.cpp 2464" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [14]             : "Catch::TestInvokerAsFunction::invoke + 18 E:\ebpf-for-windows\external\Catch2\src\catch2\internal\catch_test_case_registry_impl.cpp 150" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
    [15]             : "Catch::TestCaseHandle::invoke + 33 E:\ebpf-for-windows\external\Catch2\src\catch2\catch_test_case_info.hpp 116" [Type: std::basic_string<char,std::char_traits<char>,std::allocator<char> >]
```

### LINKED ISSUE #2046: Workflow failed - low_memory_full
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/4118206856)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/e3c62b2a91f36e47cb597ef9caecf4a6b7e3697c)
Test name - `low_memory_full`

### PR DESCRIPTION
**Pull request by saxena-anurag**
## Description

Fixes #2046
Fixes #2024 
Fixes #2025

Native module unit tests were failing in low memory simulation tests, as some module handles were not being closed when the test failed. This PR wraps the handles in an object, so that the handles are closed when objects are destroyed.

## Testing

This PR fixes tests.

## Documentation

NA

### CODE REVIEW

File: tests/end_to_end/test_helper.hpp [hunk 1]
```diff
@@ -32,6 +32,21 @@ class _test_helper_libbpf
     _single_instance_hook* cgroup_inet4_connect_hook;
 };
 
+class _test_handle_helper
```
Comment (Alan-Jowett) [inline tests/end_to_end/test_helper.hpp:35]: This has a few issues (implicit copy constructor / assignment operator etc). Have you considered using [std::unique with a deleter](https://en.cppreference.com/w/cpp/memory/unique_ptr)?

**Review by Alan-Jowett — CHANGES_REQUESTED** [review]
Please fix issues with _test_handle_helper or replace with std::unique_ptr.

**Comment by saxena-anurag** [comment]
> Please fix issues with _test_handle_helper or replace with std::unique_ptr.

Fixed.

**Comment by saxena-anurag** [comment]
> Please fix issues with _test_handle_helper or replace with std::unique_ptr.

Fixed

File: tests/end_to_end/test_helper.hpp (hunk 1 above)
Comment (saxena-anurag) [reply tests/end_to_end/test_helper.hpp:35]: Fixed the copy constructor and assignment operator.

Comment (Alan-Jowett) [reply tests/end_to_end/test_helper.hpp:35]: Just set them = delete. That disables them

Comment (Alan-Jowett) [reply tests/end_to_end/test_helper.hpp:35]: Just set them = delete. That disables them

Comment (saxena-anurag) [reply tests/end_to_end/test_helper.hpp:35]: Fixed.

**Review by Alan-Jowett — APPROVED** [review]

**Review by dthaler — APPROVED** [review]
